fix: add check for address 1 in gateway:get_storage_at
starkware-libs/papyrus pull request #1000
Opened 2023-08-08 08:22 UTC by Yael-Starkware

When handling a get_storage_at request in the gateway, need to check first if the contract address is 1,
the contract address for the block hash table.
If it is, we need to return a value and not a ContractNotFound error.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-08-08 10:33 UTC, OmriEshhar1 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000)* status: all files reviewed, 1 unresolved discussion (waiting on @DvirYo-starkware and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NbJgtFLCT2C47TjLzTc:-NbJgtFLCT2C47TjLzTd:b-3vp2lx) (no related file):*
I see that there are other places in the code that check is a contract exists (e.g. fn verify_contract_exists() in papyrus_execution).
Is the check of "contract1" relevant for it too?
If it is, we should probably put this logic in one common place instead of doing it in multiple places.

___


<!-- Sent from Reviewable.io -->

2023-08-14 13:50 UTC, DvirYo-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NbJgtFLCT2C47TjLzTc:-NboHGNlEYImlM6rVk0g:bjq7vft) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

I see that there are other places in the code that check is a contract exists (e.g. fn verify_contract_exists() in papyrus_execution).
Is the check of "contract1" relevant for it too?
If it is, we should probably put this logic in one common place instead of doing it in multiple places.
</blockquote></details>

This is irrelevant to the execution.

___
___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboHbBf3Q5YlFW5p6uy):*
Add () after the" fix" and consider changing "address != 1" to "address != 0x1"
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboGFuT4zmUxVPgXKhE:-NboGFuT4zmUxVPgXKhF:bwvv332) ([raw file](https://github.com/starkware-libs/papyrus/blob/961b718afcb8a15db5bbf22ca8df84b683a1bc5b/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L57)):*
> ```XML
>     ContinuationTokenAsStruct,
> };
> pub const BLOCK_HASH_TABLE_CONTRACT_ADDRESS: &str = "0x1";
> ```

Instead of creating the ContractAddress from this string every time, create it only one time. Try to create this using a const function or using the lazy_static macro.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboGdM71LZzgu5hw88o:-NboGdM71LZzgu5hw88p:bychjz0) ([raw file](https://github.com/starkware-libs/papyrus/blob/961b718afcb8a15db5bbf22ca8df84b683a1bc5b/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L137)):*
> ```XML
>             .get_storage_at(state, &contract_address, &key)
>             .map_err(internal_server_error);
>         if res == Ok(StarkFelt::default()) {
> ```

Document what is special in this contract.
In addition, consider using only one if statement with two conditions.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 1116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboGz4C-1ucuwUgbk3Z:-NboGz4C-1ucuwUgbk3_:bjai9ur) ([raw file](https://github.com/starkware-libs/papyrus/blob/961b718afcb8a15db5bbf22ca8df84b683a1bc5b/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L1116)):*
> ```XML
> }
> 
> #[tokio::test]
> ```

Why not add this to the already existing test "get_storage_at"?


<!-- Sent from Reviewable.io -->

2023-08-16 10:07 UTC, DvirYo-starkware requested changes
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NbxmQjW5X7DLycCd8Ks:-NbxmQjW5X7DLycCd8Kt:bhxrogm) ([raw file](https://github.com/starkware-libs/papyrus/blob/a19fe86b6be4ce2a6c8edddd0da94c038660485c/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L59)):*
> ```XML
> 
> //TODO(yael): implement address 0x1 as a const function in starknet_api.
> lazy_static! {
> ```

Consider putting this in the function get_storage_at because this constant is only used there.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 140 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NbxmBrqCBT9pa_ZUPJ8:-NbxmBrqCBT9pa_ZUPJ9:btc6kor) ([raw file](https://github.com/starkware-libs/papyrus/blob/a19fe86b6be4ce2a6c8edddd0da94c038660485c/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L140)):*
> ```XML
>         let res = state_reader
>             .get_storage_at(state, &contract_address, &key)
>             .map_err(internal_server_error);
> ```

Why don't you return the error if it exists? like in line 148.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 1107 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NbxnXoC1Qji6XzNCb00:-NbxnXoC1Qji6XzNCb01:b4q07id) ([raw file](https://github.com/starkware-libs/papyrus/blob/a19fe86b6be4ce2a6c8edddd0da94c038660485c/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L1107)):*
> ```XML
>     ));
> 
>     // Ask for storage at address 1 - the block hash table contract address
> ```

Consider putting this with the successful scenarios.


<!-- Sent from Reviewable.io -->

2023-08-16 10:22 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @DvirYo-starkware and @OmriEshhar1)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboHbBf3Q5YlFW5p6uy):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Add () after the" fix" and consider changing "address != 1" to "address != 0x1"
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboGFuT4zmUxVPgXKhE:-NbxrG4U54FGrx0Du0MG:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/961b718afcb8a15db5bbf22ca8df84b683a1bc5b/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L57)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Instead of creating the ContractAddress from this string every time, create it only one time. Try to create this using a const function or using the lazy_static macro.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 137 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboGdM71LZzgu5hw88o:-NbxrUaC9gU8PtUG38Ix:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/961b718afcb8a15db5bbf22ca8df84b683a1bc5b/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L137)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Document what is special in this contract.
In addition, consider using only one if statement with two conditions.
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NbxmQjW5X7DLycCd8Ks:-NbxrBT_7AB6Ek6PUQUH:b8x54ch) ([raw file](https://github.com/starkware-libs/papyrus/blob/a19fe86b6be4ce2a6c8edddd0da94c038660485c/crates/papyrus_gateway/src/v0_3_0/api/api_impl.rs#L59)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider putting this in the function get_storage_at because this constant is only used there.
</blockquote></details>

it is also being used in the test.
___
*[`crates/papyrus_gateway/src/v0_3_0/api/test.rs` line 1116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-NboGz4C-1ucuwUgbk3Z:-NbxrWUW6AthZXroLhBT:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/961b718afcb8a15db5bbf22ca8df84b683a1bc5b/crates/papyrus_gateway/src/v0_3_0/api/test.rs#L1116)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why not add this to the already existing test "get_storage_at"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-16 11:32 UTC, DvirYo-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-:-Nby6Tb5AVt4XRX7EFg1:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2023-08-16 12:44 UTC, DvirYo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-:-NbyN1-uEI42cq9mAyga:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2023-08-16 13:18 UTC, OmriEshhar1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 5 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1000#-:-NbyUg2k5IRrmbGf2oD6:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2023-08-16 13:26 UTC, merged