chore: execution config by block
starkware-libs/papyrus pull request #1109
Opened 2023-08-27 08:18 UTC by OmriEshhar1

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-08-27 15:35 UTC, yair-starkware requested changes
> Reviewed 7 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 13 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_execution/config_files/default.json` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrAcFPBgoyj6XyWzJR:-NcrAcFPBgoyj6XyWzJS:bwr4yz5) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/config_files/default.json#L1)):*
> ```JSON
> {
> ```

I think the config files should match the networks (mainnet / goerli / integration)
___
*[`crates/papyrus_execution/config_files/default.json` line 4 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrApdHABpNRM9Mu56G:-NcrApdHABpNRM9Mu56H:bewkszo) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/config_files/default.json#L4)):*
> ```JSON
>     "execution_config_segments": [
>         {
>             "from_block": 0,
> ```

Should be the first block of 0.12.1



_Code quote:_
```JSON
0
```
___
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-NcrYD7q0hwfuN0KhaZq:bf2ph5h) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/config_files/test.json#L2)):*
> ```JSON
> {
>     "execution_config_segments": [
> ```

Rename the file - maybe test_config.json?
___
*[`crates/papyrus_execution/src/execution_test.rs` line 608 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYlo6C7NCFit7gzOY:-NcrYlo6C7NCFit7gzOZ:biaub7z) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/execution_test.rs#L608)):*
> ```XML
>         keccak_builtin: 20.48_f64,
>     };
>     let execution_config_segment =
> ```

Shouldn't the test load the configuration from the file?
___
*[`crates/papyrus_execution/src/lib.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrXpfy0gwvHUdpsBDl:-NcrXpfy0gwvHUdpsBDm:b-ub9i0s) ([raw file](https://github.com/starkware-libs/papyrus/blob/48c6400fcc4cb8dc9d3b17cbc9389ad6fd662850/crates/papyrus_execution/src/lib.rs#L172)):*
> ```XML
> }
> 
> impl SerializeConfig for BlockExecutionConfig {
> ```

We don't need to implement this trait for BlockExecutionConfig anymore



_Code quote:_
```XML
impl SerializeConfig for BlockExecutionConfig {
```
___
*[`crates/papyrus_execution/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrBDWZDbIhuDPSwOar:-NcrBDWZDbIhuDPSwOas:b-yami19) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L74)):*
> ```XML
> pub const DEFAULT_CONFIG_PATH: &str = "config_files/default.json";
> /// The path to the test execution config file.
> pub const TEST_CONFIG_PATH: &str = "config_files/test.json";
> ```

Why is it here?



_Code quote:_
```XML
/// The path to the test execution config file.
pub const TEST_CONFIG_PATH: &str = "config_files/test.json";
```
___
*[`crates/papyrus_execution/src/lib.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrBiXI4Vhp51c-s9lt:-NcrBiXI4Vhp51c-s9lu:bzd509y) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L78)):*
> ```XML
> /// Returns the absolute path of the execution config file.
> pub fn get_absolute_config_file_path(relative_path: &str) -> PathBuf {
>     let absolute_path = env!("CARGO_MANIFEST_DIR", "crates/papyrus_execution");
> ```

The second argument in the macro is an error message in case the env var doesn't exist, right?
Please write a better error message.

Also, I thing that in k8 the env variable doesn't exist. 
Consider moving the file to the config dir (where the default_config.json file is) and load it like [here](https://github.com/starkware-libs/papyrus/blob/81468a8c7c255edb6e94b0055428492735f72889/crates/papyrus_node/src/config/mod.rs#L78)



_Code quote:_
```XML
"crates/papyrus_execution"
```
___
*[`crates/papyrus_execution/src/lib.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrDeOX5thSyzkYBLA7:-NcrDeOX5thSyzkYBLA8:b-497494) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L86)):*
> ```XML
> /// Parameters that are needed for execution.
> // TODO(yair): Find a way to get them from the Starknet general config.
> pub struct BlockExecutionConfig {
> ```

The parameters themselve might change between SN versions (not just the values).
Perhaps the data should be stored in a mapping, and define getters using traits.

For example:
```
sturct BlockExecutionConfig {
   parameters: BTreeMap<String, json::value>
}

impl ExecutionConfigV0_12_1 for BlockExecutionConfig {
    fn pedersen_builtin(&self) -> f64 {
        serde_json::from_value(&self.parameters["pedersen_builtin"])
    }
   ...
}

trait ExecutionConfigV0_12_1 {
    fn pedersen_builtin(&self) -> f64;
    ...
}
```
___
*[`crates/papyrus_execution/src/lib.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrFr3kC7CWLo7kE7XN:-NcrFr3kC7CWLo7kE7XO:bj51ibi) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L116)):*
> ```XML
> #[allow(missing_docs)]
> pub struct ExecutionConfig {
>     pub execution_config_segments: Vec<ExecutionConfigSegment>,
> ```

Consider using map



_Code quote:_
```XML
pub execution_config_segments: Vec<ExecutionConfigSegment>,
```
___
*[`crates/papyrus_execution/src/lib.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrZgQ313FcVCq99D7G:-NcrZgQ313FcVCq99D7H:b-e4ctuw) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L131)):*
> ```XML
> pub struct ExecutionConfigFile {
>     pub config_file_path: String,
> }
> ```

Why do we need this struct?



_Code quote:_
```XML
pub struct ExecutionConfigFile {
    pub config_file_path: String,
}
```
___
*[`crates/papyrus_execution/src/lib.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrGMld9WaE9UWbX0lt:-NcrGMld9WaE9UWbX0lu:b5w988q) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L148)):*
> ```XML
> 
> /// Returns the execution config for a given block number.
> pub fn get_execution_config_for_block(
> ```

There should be some kind of function such as lower_bound (maybe if the data was stored in a BTreeMap)
___
*[`crates/papyrus_execution/src/lib.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrcNCkBqWj4i_6ywT4:-NcrcNCkBqWj4i_6ywT5:b-sqojd4) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L148)):*
> ```XML
> 
> /// Returns the execution config for a given block number.
> pub fn get_execution_config_for_block(
> ```

Consider making this function a method of ExecutionConfig



_Code quote:_
```XML
get_execution_config_for_block
```
___
*[`crates/papyrus_rpc/src/lib.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcratLB3zPGHzztW2-j:-NcratLB3zPGHzztW2-k:b-xb334s) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_rpc/src/lib.rs#L105)):*
> ```XML
>         self_params_dump.append(&mut retry_config_dump);
>         let mut execution_config_dump =
>             append_sub_config_name(self.execution_config_file_ [...]

2023-08-27 15:36 UTC, yair-starkware commented
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrcooN1qGBAh55kTlE):*
I think feat(execution) is more suitable



_Code quote:_
```
chore: execution config by block
```


<!-- Sent from Reviewable.io -->

2023-08-27 15:37 UTC, yair-starkware commented
*[`crates/papyrus_execution/src/execution_test.rs` line 613 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Ncrd62x2cKtnIysAe2A:-Ncrd62x2cKtnIysAe2B:b-ss393w) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/execution_test.rs#L613)):*
> ```XML
>         ExecutionConfig { execution_config_segments: vec![execution_config_segment] };
>     assert_eq!(expected_config, ExecutionConfig::default());
> }
> ```

Missing a test that loads different configurations according to a given block


<!-- Sent from Reviewable.io -->

2023-08-27 15:45 UTC, yair-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 19 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_execution/src/lib.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Ncrdp--AJEcydi1C3n1:-Ncrdp--AJEcydi1C3n2:bc32vln) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L129)):*
> ```XML
> #[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
> #[allow(missing_docs)]
> pub struct ExecutionConfigFile {
> ```

I think this struct should be called ExecutionConfig, and ExecutionConfig should be something like ExecutionConfigByBlock or something like that



_Code quote:_
```XML
ExecutionConfigFile
```
___
*[`crates/papyrus_execution/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcreIyGA498jrjQHs3j:-NcreIyGA498jrjQHs3k:b-6ffq9c) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L140)):*
> ```XML
> 
> /// Returns the execution config from the config file.
> pub fn get_execution_config(execution_config_file_path: &ExecutionConfigFile) -> ExecutionConfig {
> ```

Implement this function as a try_from (` impl TryFrom<ExecutionConfigFile> for ExecutionConfig`)



_Code quote:_
```XML
get_execution_config
```
___
*[`crates/papyrus_execution/src/lib.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcredMJ7i0N2MvMSil7:-NcredMJ7i0N2MvMSil8:bkwoptp) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L144)):*
> ```XML
>         fs::File::open(get_absolute_config_file_path(&execution_config_file_path.config_file_path))
>             .unwrap();
>     serde_json::from_reader(config_file).unwrap()
> ```

Return error



_Code quote:_
```XML
unwrap()
```
___
*[`crates/papyrus_execution/src/lib.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrekXJ4mFOMn3abEWU:-NcrekXJ4mFOMn3abEWV:b8v9qvq) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L154)):*
> ```XML
>     let segments = &execution_config.execution_config_segments;
>     assert!(!segments.is_empty(), "Execution config is empty.");
>     assert!(segments[0].from_block == BlockNumber(0), "First segment must start at block 0.");
> ```

Return errors



_Code quote:_
```XML
    assert!(!segments.is_empty(), "Execution config is empty.");
    assert!(segments[0].from_block == BlockNumber(0), "First segment must start at block 0.");
```
___
*[`crates/papyrus_execution/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcreqOY0BHLNyKGoJFS:-NcreqOY0BHLNyKGoJFT:bx0yhpp) ([raw file](https://github.com/starkware-libs/papyrus/blob/d686b873134b8866707ede46a30f99b2d1df00c0/crates/papyrus_execution/src/lib.rs#L157)):*
> ```XML
>     for (segment_number, segment) in segments.iter().enumerate() {
>         if block_number < segment.from_block {
>             return segments[segment_number - 1].block_execution_config.clone();
> ```

Can we avoid cloning?



_Code quote:_
```XML
.clone();
```


<!-- Sent from Reviewable.io -->

2023-08-28 12:24 UTC, OmriEshhar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 18 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/config_files/default.json` line 1 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrAcFPBgoyj6XyWzJR:-Ncum2jO6HZBSwKwPJBv:b9m6ute) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/default.json#L1)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the config files should match the networks (mainnet / goerli / integration)
</blockquote></details>

I agree. The default one is temporary. Will add new configs in later PR.
___
*[`crates/papyrus_execution/config_files/default.json` line 4 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrApdHABpNRM9Mu56G:-NcumIW09LvSr6-PO6ZP:b-47v0zg) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/default.json#L4)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Should be the first block of 0.12.1
</blockquote></details>

I'll do the correct configuration in a later PRs.
___
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-NcunH4m2x0fL-rT32JM:b5akirn) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/test.json#L2)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rename the file - maybe test_config.json?
</blockquote></details>

OK. Changed the file names to test_config.json and default_config.json.
___
*[`crates/papyrus_execution/src/execution_test.rs` line 608 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYlo6C7NCFit7gzOY:-Ncuo14IAQgDDZydOu5l:b-b0lmjo) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/execution_test.rs#L608)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't the test load the configuration from the file?
</blockquote></details>

It is. 
ExecutionConfig::default() reads it from the file (last line of the function).
Added documentation.
___
*[`crates/papyrus_execution/src/execution_test.rs` line 613 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Ncrd62x2cKtnIysAe2A:-NcunRtK5inhUtzNpwcT:bsyrbm4) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/execution_test.rs#L613)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Missing a test that loads different configurations according to a given block
</blockquote></details>

Yes. I know. Will do in a separate PR. (Added a TODO).
___
*[`crates/papyrus_execution/src/lib.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrBDWZDbIhuDPSwOar:-NcuobgJBCZMAOMN9DsL:b-r72wfx) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L74)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why is it here?
</blockquote></details>

Done.
Moved to crates/papyrus_rpc/src/test_utils.rs
___
*[`crates/papyrus_execution/src/lib.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrBiXI4Vhp51c-s9lt:-Ncuon3_-r-I1b6fgmsQ:b-6hzf5y) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L78)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The second argument in the macro is an error message in case the env var doesn't exist, right?
Please write a better error message.

Also, I thing that in k8 the env variable doesn't exist. 
Consider moving the file to the config dir (where the default_config.json file is) and load it like [here](https://github.com/starkware-libs/papyrus/blob/81468a8c7c255edb6e94b0055428492735f72889/crates/papyrus_node/src/config/mod.rs#L78)
</blockquote></details>

Oh. OK. I thought that the second parameter is a default if the env var was not found :(
(I struggled with it, because I didn't have the CARGO_MANIFEST_DIR in one of the tests that runs without cargo, but this solved it for some reason.)
* Anyway, I'll move the config files as you suggested.
** Actually, I see that tests fail. I'll see how this should be fixed.
** OK, looks like a relative path is still needed. I have a (slightly ugly) solution. I put a TODO to improve it.
___
*[`crates/papyrus_execution/src/lib.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrZgQ313FcVCq99D7G:-Ncw4umB7OIBVRu--c43:bf4hqy2) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L131)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need this struct?
</blockquote></details>

This struct is part of the system configuration. 
Previously, the system configuration contained all the execution-config params, now it just holds the name of the config file that hold the params.
This is the intention of your design, right?


<!-- Sent from Reviewable.io -->

2023-08-29 14:23 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: 3 of 15 files reviewed, 14 unresolved discussions (waiting on @OmriEshhar1 and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrXpfy0gwvHUdpsBDl:-Nd0OpAw1mvhv7-tcjs8:b-9unw5o) ([raw file](https://github.com/starkware-libs/papyrus/blob/48c6400fcc4cb8dc9d3b17cbc9389ad6fd662850/crates/papyrus_execution/src/lib.rs#L172)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We don't need to implement this trait for BlockExecutionConfig anymore
</blockquote></details>

deleted
___
*[`crates/papyrus_execution/src/lib.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrDeOX5thSyzkYBLA7:-Nd-7IKY4MKfVVCifn7l:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The parameters themselve might change between SN versions (not just the values).
Perhaps the data should be stored in a mapping, and define getters using traits.

For example:
```
sturct BlockExecutionConfig {
   parameters: BTreeMap<String, json::value>
}

impl ExecutionConfigV0_12_1 for BlockExecutionConfig {
    fn pedersen_builtin(&self) -> f64 {
        serde_json::from_value(&self.parameters["pedersen_builtin"])
    }
   ...
}

trait ExecutionConfigV0_12_1 {
    fn pedersen_builtin(&self) -> f64;
    ...
}
```
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrFr3kC7CWLo7kE7XN:-Nd-72C5BMUk_SGzT-L7:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L116)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider using map
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 129 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Ncrdp--AJEcydi1C3n1:-Nd-CYNtDscmuJ1UyJPj:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L129)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think this struct should be called ExecutionConfig, and ExecutionConfig should be something like ExecutionConfigByBlock or something like that
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 140 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcreIyGA498jrjQHs3j:-Nd-H-oW3-hOPzZ3DpMX:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L140)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Implement this function as a try_from (` impl TryFrom<ExecutionConfigFile> for ExecutionConfig`)
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcredMJ7i0N2MvMSil7:-Nd-H0ss8CpTRV2Mqxsh:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L144)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Return error
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrcNCkBqWj4i_6ywT4:-Nd-YrPc85THz_rx4gUT:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L148)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider making this function a method of ExecutionConfig
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrGMld9WaE9UWbX0lt:-Nd0GSNG854r-PpuPQJr:b-b5hq6h) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L148)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

There should be some kind of function such as lower_bound (maybe if the data was stored in a BTreeMap)
</blockquote></details>

according to rust analyser, the function upper_bound is not stable, so eventually I didn't use it but left a TODO in the code.
___
*[`crates/papyrus_execution/src/lib.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrekXJ4mFOMn3abEWU:-Nd0GM6V3hPVTanzIC5R:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L154)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Return errors
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcreqOY0BHLNyKGoJFS:-Nd0OlYd86uBfyMI11SP:b-7rl0jd) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/src/lib.rs#L157)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we avoid cloning?
</blockquote></details>

done.
___
*[`crates/papyrus_rpc/src/lib.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcratLB3zPGHzztW2-j:-Nd0clIEC9sdMUNk33mW:b3kkjab) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_rpc/src/lib.rs#L105)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The second parameter should be the name of the sub-config (execution_config_file in this case).
Did you try to run the node? I think it should fail.
</blockquote></details>

when changing it  config::config_test::test_dump_default_config fails


<!-- Sent from Reviewable.io -->

2023-09-03 08:40 UTC, yair-starkware requested changes
> Reviewed 2 of 8 files at r3, 8 of 10 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 14 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_execution/src/lib.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd4ZNBJ46yZ0XhLRAlo:-Nd4ZNBJ46yZ0XhLRAlp:bng1zbd) ([raw file](https://github.com/starkware-libs/papyrus/blob/087d6382e9870289773b2fbd428c310ad267a537/crates/papyrus_execution/src/lib.rs#L73)):*
> ```XML
> 
> /// The path to the default execution config file.
> pub const DEFAULT_CONFIG_FILE: &str = "default_config.json";
> ```

Shouldn't be public



_Code quote:_
```XML
pub 
```
___
*[`crates/papyrus_execution/src/lib.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd4ZBb_CLRg7DPmnLov:-Nd4ZBb_CLRg7DPmnLow:bng1zbd) ([raw file](https://github.com/starkware-libs/papyrus/blob/087d6382e9870289773b2fbd428c310ad267a537/crates/papyrus_execution/src/lib.rs#L76)):*
> ```XML
> 
> /// Returns the absolute path of the execution config file.
> pub fn get_config_file(file_name: &str) -> File {
> ```

Shouldn't be public



_Code quote:_
```XML
pub 
```
___
*[`crates/papyrus_execution/src/lib.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP-ec76yhiQrhZ9PsJ:-NdP-ec76yhiQrhZ9PsK:b-l6mwxj) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L104)):*
> ```XML
> }
> #[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
> #[allow(missing_docs)]
> ```

remove



_Code quote:_
```XML
#[allow(missing_docs)]
```
___
*[`crates/papyrus_execution/src/lib.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP96PO2ja4UHLOZ-DB:-NdP96PO2ja4UHLOZ-DC:bng1zbd) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L107)):*
> ```XML
> /// Parameters that are needed for execution.
> // TODO(yair): Find a way to get them from the Starknet general config.
> pub struct BlockExecutionConfig {
> ```

Shouldn't be public



_Code quote:_
```XML
pub 
```
___
*[`crates/papyrus_execution/src/lib.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP4U1OCvTLFKg0vI1L:-NdP4U1OCvTLFKg0vI1M:b-1k6re9) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L109)):*
> ```XML
> pub struct BlockExecutionConfig {
>     parameters: BTreeMap<String, serde_json::Value>,
> }
> ```

Let's change this struct to be 
```
pub struct BlockExecutionConfig {
    pub fee_contract_address: ContractAddress,
    pub invoke_tx_max_n_steps: u32,
    pub validate_tx_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub step_gas_cost: u64,
    pub initial_gas_cost: u64,
    pub vm_resource_fee_cost: HashMap<String, f64>,
}
```

This way we don't need the trait anymore.



_Code quote:_
```XML
pub struct BlockExecutionConfig {
    parameters: BTreeMap<String, serde_json::Value>,
}
```
___
*[`crates/papyrus_execution/src/lib.rs` line 163 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdPB2XZ9qeLo8Tz0w3G:-NdPB2XZ9qeLo8Tz0w3H:b-kl43c0) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L163)):*
> ```XML
> 
> #[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
> #[allow(missing_docs)]
> ```

document



_Code quote:_
```XML
#[allow(missing_docs)]
```
___
*[`crates/papyrus_execution/src/lib.rs` line 184 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd5zWtKDPG-EAWHZQl_:-Nd5zWtKDPG-EAWHZQla:b6qzuad) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L184)):*
> ```XML
>         if segments.is_empty() || segments.keys().min() != Some(&BlockNumber(0)) {
>             return Err(ExecutionError::ConfigError);
>         }
> ```

I think the function should return Result<Option<&BlockExecutionConfig>, and in case the block is not covered in the configuration return Ok(None)



_Code quote:_
```XML
        let segments = &self.execution_config_segments;
        if segments.is_empty() || segments.keys().min() != Some(&BlockNumber(0)) {
            return Err(ExecutionError::ConfigError);
        }
```
___
*[`crates/papyrus_execution/src/lib.rs` line 213 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP8u0S5za1zBqnzOnH:-NdP8u0S5za1zBqnzOnI:bd62z5p) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L213)):*
> ```XML
> pub struct ExecutionConfig {
>     pub config_file_name: String,
> }
> ```

Move to the top of the file and add documentation.



_Code quote:_
```XML
#[derive(Clone, Serialize, Deserialize, Debug, PartialEq)]
#[allow(missing_docs)]
pub struct ExecutionConfig {
    pub config_file_name: String,
}
```
___
*[`crates/papyrus_execution/src/lib.rs` line 277 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd60vWN5WtJkYevgDS6:-Nd60vWN5WtJkYevgDS7:b-ongfid) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L277)):*
> ```XML
>     #[error("Charging fee is not supported yet in execution.")]
>     ChargeFeeNotSupported,
>     #[error("Config does not contain the default configuration")]
> ```

I don't understand this message... 
Note that you can add arguments to the error to provide more information



_Code quote:_
```XML
Config does not contain the default configuration
```
___
*[`crates/papyrus_rpc/src/lib.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcratLB3zPGHzztW2-j:-NdP5xiM7hyg5hU_yf1u:b-ynxbac) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_rpc/src/lib.rs#L105)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

when changing it  config::config_test::test_dump_default_config fails
</blockquote></details>

That's because you changed back the name of the struct to ExecutionConfig 
___
*[`crates/papyrus_rpc/src/lib.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP7uwCCuYu8m-h9yVN:-NdP7uwCCuYu8m-h9yVO:b4c8mtf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_rpc/src/lib.rs#L60)):*
> ```XML
>     pub starknet_url: String,
>     pub starknet_gateway_retry_config: RetryConfig,
>     pub execution_config_file: ExecutionConfig,
> ```

Rename to just `execution_config`



_Code quote:_
```XML
pub execution_config_file: ExecutionConfig,
```
___
*[`crates/papyrus_rpc/src/test_utils.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdPAls6EFrtmuCrBgP0:-NdPAls6EFrtmuCrBgP1:b-r1q7oi) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_rpc/src/test_utils.rs#L65)):*
> ```XML
>         T::new(
>             config.chain_id,
>             config.execution_config_file.try_into().unwrap(),
> ```

expect



_Code quote:_
```XML
.unwrap(),
```
___
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-Nd0kzJX04kR0c2KpP2n:b-gzk48j) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/test.json#L2)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

OK. Changed the file names to test_config.json and default_config.json.
</blockquote></details>

Move the test_config bac [...]

2023-09-05 06:29 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: 7 of 15 files reviewed, 14 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd4ZNBJ46yZ0XhLRAlo:-NdVWq_J15Ngg4MMhw_z:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/087d6382e9870289773b2fbd428c310ad267a537/crates/papyrus_execution/src/lib.rs#L73)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't be public
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd4ZBb_CLRg7DPmnLov:-NdVX-ukA26Mbn52o_Ef:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/087d6382e9870289773b2fbd428c310ad267a537/crates/papyrus_execution/src/lib.rs#L76)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't be public
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP-ec76yhiQrhZ9PsJ:-NdVX3ns6AZTCQzIS4x2:b-y62khy) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L104)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

remove
</blockquote></details>

should I document each and every param in the struct?
___
*[`crates/papyrus_execution/src/lib.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP96PO2ja4UHLOZ-DB:-NdVX_419oJ5ejJRvsNW:b-skscas) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Shouldn't be public
</blockquote></details>

used by a public struct so can't make it private alone.
___
*[`crates/papyrus_execution/src/lib.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP4U1OCvTLFKg0vI1L:-NdVXcDwAc93Rs1rPHWs:b-v44wfg) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L109)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Let's change this struct to be 
```
pub struct BlockExecutionConfig {
    pub fee_contract_address: ContractAddress,
    pub invoke_tx_max_n_steps: u32,
    pub validate_tx_max_n_steps: u32,
    pub max_recursion_depth: usize,
    pub step_gas_cost: u64,
    pub initial_gas_cost: u64,
    pub vm_resource_fee_cost: HashMap<String, f64>,
}
```

This way we don't need the trait anymore.
</blockquote></details>

done , 
no reverts!
___
*[`crates/papyrus_execution/src/lib.rs` line 163 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdPB2XZ9qeLo8Tz0w3G:-NdVXh-C4fY1cQVen00h:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L163)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

document
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 184 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd5zWtKDPG-EAWHZQl_:-NdV_fyZ53nNseH5yL95:bbtp4uj) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L184)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think the function should return Result<Option<&BlockExecutionConfig>, and in case the block is not covered in the configuration return Ok(None)
</blockquote></details>

actually it always finds the configuration as long as there is a segment for block 0 (and then it returns an error)
did you mean that I should return Ok(none), instead of Error?
It looks fine to me this way.
___
*[`crates/papyrus_execution/src/lib.rs` line 213 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP8u0S5za1zBqnzOnH:-NdVam6zCZgSVIxbPEYV:bn9rovs) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L213)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move to the top of the file and add documentation.
</blockquote></details>

done
but still need to specify missing docs for the internals of the struct. 
___
*[`crates/papyrus_execution/src/lib.rs` line 277 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd60vWN5WtJkYevgDS6:-NdV_RTy3JV78PmCruPR:b-pkoq7t) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L277)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I don't understand this message... 
Note that you can add arguments to the error to provide more information
</blockquote></details>

I have no parameters to add.  but I changed the error message, is it better now?
___
*[`crates/papyrus_rpc/src/lib.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcratLB3zPGHzztW2-j:-NdVZ4hY9Ck8pazQSXh3:bb7cwme) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_rpc/src/lib.rs#L105)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

That's because you changed back the name of the struct to ExecutionConfig
</blockquote></details>

ack
___
*[`crates/papyrus_rpc/src/lib.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP7uwCCuYu8m-h9yVN:-NdVb9Lp6OWOZVetZqIR:b-7rl0kd) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_rpc/src/lib.rs#L60)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Rename to just `execution_config`
</blockquote></details>

done
___
*[`crates/papyrus_rpc/src/test_utils.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdPAls6EFrtmuCrBgP0:-NdZ0hvx2a8tIe-6MUtw:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_rpc/src/test_utils.rs#L65)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

expect
</blockquote></details>

done
___
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-NdV6SwR0VqBawfcWcdT:b-lcdeol) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/test.json#L2)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move the test_config back into the crate folder (the real config files can remain outside).
</blockquote></details>

it makes it much more complicated for testing code,  since they use the function run_server() which get the file from the same path as the other config files. 


<!-- Sent from Reviewable.io -->

2023-09-05 07:54 UTC, yair-starkware requested changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 8 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 104 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP-ec76yhiQrhZ9PsJ:-NdZBlhoAgOF0nxD0n8b:b-hk6n51) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L104)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

should I document each and every param in the struct?
</blockquote></details>

Once private you don't have to document it
___
*[`crates/papyrus_execution/src/lib.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP96PO2ja4UHLOZ-DB:-NdZBhyj3QYCrd6mm3o5:baid7eu) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L107)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

used by a public struct so can't make it private alone.
</blockquote></details>

Oh ExecutionConfigByBlock shouldn't be public as well.
___
*[`crates/papyrus_execution/src/lib.rs` line 184 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-Nd5zWtKDPG-EAWHZQl_:-NdZJHSGAEwys0E_va0D:b63oumi) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L184)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

actually it always finds the configuration as long as there is a segment for block 0 (and then it returns an error)
did you mean that I should return Ok(none), instead of Error?
It looks fine to me this way.
</blockquote></details>

Ok resolving
___
*[`crates/papyrus_execution/src/lib.rs` line 213 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP8u0S5za1zBqnzOnH:-NdZIC875FpJb7tshOfc:b-bee0il) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L213)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

done
but still need to specify missing docs for the internals of the struct.
</blockquote></details>

Yeah, it's just 1 parameter
___
*[`crates/papyrus_execution/src/lib.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdZITY32OEzW4KN0D78:-NdZITY32OEzW4KN0D79:b-ytqzek) ([raw file](https://github.com/starkware-libs/papyrus/blob/cae4ad98319b6be2f5f6045513aca097ace85d67/crates/papyrus_execution/src/lib.rs#L106)):*
> ```XML
>     let file_full_name = Path::new(&home_dir).join("config/execution_config").join(file_name);
>     fs::File::open(file_full_name).unwrap()
> }
> ```

This can be a private method of ExecutionConfig



_Code quote:_
```XML
/// Returns the absolute path of the execution config file.
fn get_config_file(file_name: &str) -> File {
    // TODO(Omri): Find a better way to get the config file path.
    let home_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(s) => format!("{}/../..", s),
        _ => "".to_string(),
    };
    let file_full_name = Path::new(&home_dir).join("config/execution_config").join(file_name);
    fs::File::open(file_full_name).unwrap()
}
```
___
*[`crates/papyrus_execution/src/lib.rs` line 290 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdZJxc-2CgJ3ZESUUbo:-NdZJxc-2CgJ3ZESUUbp:bqrba2o) ([raw file](https://github.com/starkware-libs/papyrus/blob/cae4ad98319b6be2f5f6045513aca097ace85d67/crates/papyrus_execution/src/lib.rs#L290)):*
> ```XML
>         sequencer_address: *sequencer_address,
>         fee_token_address: execution_config.fee_contract_address,
>         vm_resource_fee_cost: execution_config.vm_resources_fee_cost.clone().into(),
> ```

I think we can avoid this cloning if the original member in the configuration is Arc<HashMap>



_Code quote:_
```XML
clone().into(),
```


<!-- Sent from Reviewable.io -->

2023-09-05 08:24 UTC, yair-starkware commented
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-NdZKl-73zlialYXiA4N:bwxdh8h) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/test.json#L2)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

it makes it much more complicated for testing code,  since they use the function run_server() which get the file from the same path as the other config files.
</blockquote></details>

doesn't it use get_test_rpc_config which calls test_execution_config()?


<!-- Sent from Reviewable.io -->

2023-09-06 08:39 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 7 unresolved discussions (waiting on @OmriEshhar1 and @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP96PO2ja4UHLOZ-DB:-Ndd3SvMEMVwlna7f8zX:bcwaldl) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Oh ExecutionConfigByBlock shouldn't be public as well.
</blockquote></details>

It is being used widely throughout the code.
let discuss f2f if this is needed since it requires a significant refactoring 
___
*[`crates/papyrus_execution/src/lib.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdZITY32OEzW4KN0D78:-Ndd2ymG-QU5kqAYoXpm:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/cae4ad98319b6be2f5f6045513aca097ace85d67/crates/papyrus_execution/src/lib.rs#L106)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

This can be a private method of ExecutionConfig
</blockquote></details>

done
___
*[`crates/papyrus_execution/src/lib.rs` line 290 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdZJxc-2CgJ3ZESUUbo:-Ndd3r-e4TujSZJNykW8:b-sa9eyg) ([raw file](https://github.com/starkware-libs/papyrus/blob/cae4ad98319b6be2f5f6045513aca097ace85d67/crates/papyrus_execution/src/lib.rs#L290)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we can avoid this cloning if the original member in the configuration is Arc<HashMap>
</blockquote></details>

done, 
it was a good time to refresh my knowledge about Arc. 
clone of the Arc pointer is fine right?
___
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-Ndd-WVG3qQDyG5N20-h:b-qckxqv) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/test.json#L2)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

doesn't it use get_test_rpc_config which calls test_execution_config()?
</blockquote></details>

The RpcConfig struct contains only the file name and not the entire execution configuration. the function run_server() takes the RpcConfig (with the file name) and reads the configuration from this file.
The file path is hard coded to be the path where all the config files are stored.


<!-- Sent from Reviewable.io -->

2023-09-06 08:57 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/src/lib.rs` line 213 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdP8u0S5za1zBqnzOnH:-NddhKJs2zpqFA6Bjk_V:b-uhpfjx) ([raw file](https://github.com/starkware-libs/papyrus/blob/a7b72939c5098b3e04d1f74e2f3c85a324a06090/crates/papyrus_execution/src/lib.rs#L213)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Yeah, it's just 1 parameter
</blockquote></details>

so it's ok now?


<!-- Sent from Reviewable.io -->

2023-09-07 11:55 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_execution/config_files/test.json` line 2 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NcrYD7q0hwfuN0KhaZp:-NdjU_nN2e3lQYZyvQiY:b67nmwy) ([raw file](https://github.com/starkware-libs/papyrus/blob/9a8bca93ef2e95c9c0f3bae9c71a2a9d7aea1d18/crates/papyrus_execution/config_files/test.json#L2)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

The RpcConfig struct contains only the file name and not the entire execution configuration. the function run_server() takes the RpcConfig (with the file name) and reads the configuration from this file.
The file path is hard coded to be the path where all the config files are stored.
</blockquote></details>

done as we discussed


<!-- Sent from Reviewable.io -->

2023-09-07 16:34 UTC, yair-starkware requested changes
> Reviewed 2 of 4 files at r7, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109)* status: all files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1)

___
*[`crates/papyrus_execution/src/execution_utils.rs` line 39 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdkSnEZ-XBKhRkAOEgy:-NdkSnEZ-XBKhRkAOEgz:bbc1em6) ([raw file](https://github.com/starkware-libs/papyrus/blob/fc3a7babd04cb28cc177cf54c0c468042c7004ba/crates/papyrus_execution/src/execution_utils.rs#L39)):*
> ```XML
> /// Returns the execution config from the config file.
> impl TryFrom<PathBuf> for ExecutionConfigByBlock {
>     type Error = serde_json::Error;
> ```

Return ExecutionError, add to it the proper variant 



_Code quote:_
```XML
serde_json::Error;
```
___
*[`crates/papyrus_execution/src/execution_utils.rs` line 42 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdkSjJB-GXCHhr4ax-j:-NdkSjJB-GXCHhr4ax-k:b-5hvea) ([raw file](https://github.com/starkware-libs/papyrus/blob/fc3a7babd04cb28cc177cf54c0c468042c7004ba/crates/papyrus_execution/src/execution_utils.rs#L42)):*
> ```XML
> 
>     fn try_from(execution_config_file: PathBuf) -> Result<Self, Self::Error> {
>         let file = File::open(execution_config_file).unwrap();
> ```

Return the error



_Code quote:_
```XML
unwrap();
```
___
*[`crates/papyrus_execution/src/lib.rs` line 290 at r6](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdZJxc-2CgJ3ZESUUbo:-NdkTX686cX2oJxnT0ay:bb77uhe) ([raw file](https://github.com/starkware-libs/papyrus/blob/cae4ad98319b6be2f5f6045513aca097ace85d67/crates/papyrus_execution/src/lib.rs#L290)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

done, 
it was a good time to refresh my knowledge about Arc. 
clone of the Arc pointer is fine right?
</blockquote></details>

Yest
___
*[`crates/papyrus_rpc/src/lib.rs` line 177 at r8](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-NdkUOGb5ynSFSNnROKg:-NdkUOGb5ynSFSNnROKh:bo9ehdh) ([raw file](https://github.com/starkware-libs/papyrus/blob/fc3a7babd04cb28cc177cf54c0c468042c7004ba/crates/papyrus_rpc/src/lib.rs#L177)):*
> ```XML
>     let methods = get_methods_from_supported_apis(
>         &config.chain_id,
>         config.execution_config.config_file_name.clone().try_into()?,
> ```

In next PR delete the ExecutionConfig struct and just make the member of the rpc configuration a file path


<!-- Sent from Reviewable.io -->

2023-09-10 07:02 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1109#-:-NdxtU650gT8ixU8EE5c:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)



<!-- Sent from Reviewable.io -->

2023-09-10 07:18 UTC, merged