chore(config): add infomative prints to the configuration validations…
starkware-libs/papyrus pull request #1188
Opened 2023-09-19 08:53 UTC by Yael-Starkware

… and exit in case of an error

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-09-19 09:56 UTC, yair-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @OmriEshhar1 and @Yael-Starkware)

___
*[`crates/papyrus_config/src/validators.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NegnUbL9wPBm_p-_Ckn:-NegnUbL9wPBm_p-_Cko:bs9b8m1) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L24)):*
> ```XML
> 
> /// Custom validation for directory existence.
> pub fn data_dir_exists(data_dir: &Path) -> Result<(), ValidationError> {
> ```

Consolidate the verification of files and dirs into a single function that checks path existence



_Code quote:_
```XML
data_dir_exists
```
___
*[`crates/papyrus_config/src/validators.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NegoU-36GHPDnAlRgoQ:-NegoU-36GHPDnAlRgoR:b-i0kvw) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L40)):*
> ```XML
> pub struct ParsedValidationError {
>     /// The path of the field that failed validation.
>     pub path: String,
> ```

param_path 



_Code quote:_
```XML
path
```
___
*[`crates/papyrus_config/src/validators.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpa23BfPObLWYdxGn:-Negpa23BfPObLWYdxGo:b-arrpo7) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L50)):*
> ```XML
> 
> /// A vector of parsing validation errors.
> pub struct ParsedValidationErrors(pub Vec<ParsedValidationError>);
> ```

Can this be another variant of the ConfigError?



_Code quote:_
```XML
/// A vector of parsing validation errors.
pub struct ParsedValidationErrors(pub Vec<ParsedValidationError>);
```
___
*[`crates/papyrus_config/src/validators.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpo1TCpZhzT8OovM5:-Negpo1TCpZhzT8OovM6:b-bse94p) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L52)):*
> ```XML
> pub struct ParsedValidationErrors(pub Vec<ParsedValidationError>);
> 
> impl TryFrom<ValidationErrors> for ParsedValidationErrors {
> ```

Why TryFrom and not From?



_Code quote:_
```XML
TryFrom
```
___
*[`crates/papyrus_config/src/validators.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negque94TBMUlAWDq30:-Negque94TBMUlAWDq31:b836dsv) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L74)):*
> ```XML
>         } else {
>             format!("{}.{}", current_path, field)
>         };
> ```

use ok_or (see Option doc)



_Code quote:_
```XML
        let new_path = if current_path.is_empty() {
            field.to_string()
        } else {
            format!("{}.{}", current_path, field)
        };
```
___
*[`crates/papyrus_node/src/main.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NegrMfI8wseaFJcEtJV:-NegrMfI8wseaFJcEtJW:b5pn4og) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_node/src/main.rs#L120)):*
> ```XML
>         }
>     }
> }
> ```

Convert to Display implementation of the struct



_Code quote:_
```XML
fn print_validation_errors(errors: ValidationErrors) {
    let parsed_errors: ParsedValidationErrors = errors.try_into().unwrap();
    for error in parsed_errors.0.iter() {
        error!(
            "Configuration validation error: The field {:?} got error {:?} for value: {:?}",
            &error.path, &error.code, &error.params
        );
        if let Some(msg) = &error.message {
            error!("{:?}", msg);
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2023-09-19 10:31 UTC, OmriEshhar1 requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/papyrus_config/src/validators.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NegzGzWCZzG1yP9ZP1_:-NegzGzWCZzG1yP9ZP1a:b-5ndii7) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L28)):*
> ```XML
>         let mut error = ValidationError::new("directory not found");
>         error.message = Some(
>             "Please create a directory at the default ./data path or specify a different path \
> ```

Put the data_dir value in the error message.
You can just say something like: ("Directory {} not found. Please create it or change the data directory configuration.", data_dir)


<!-- Sent from Reviewable.io -->

2023-09-20 12:16 UTC, OmriEshhar1 requested changes
> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemW-820_UjYy9exqM0:-NemW-820_UjYy9exqM1:b135its) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/config/config_test.rs#L85)):*
> ```XML
> 
>     // The validate function will fail if the data directory does not exist so we change the path to
>     // point to an exsting directory.
> ```

existing



_Code quote:_
```XML
exsting
```


<!-- Sent from Reviewable.io -->

2023-09-20 16:10 UTC, yair-starkware reviewed
> Reviewed 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenLMyWBzyqN3zgSiJ8:-NenLA_b0IArDWOP6g3f:boqf0ba) (no related file):*
Can you add verification that the config files exist in `update_config_map_by_custom_configs`?
I think that currently it will be mapped to the wrong error (`WriteDumpedConfig`)

___
___
*[`crates/papyrus_config/src/lib.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemS_6SE8PRBcgOIZwd:-NemS_6SE8PRBcgOIZwe:b2amjmo) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_config/src/lib.rs#L169)):*
> ```XML
>     ChangeRequiredParamType { param_path: String, required: SerializationType, given: Value },
>     #[error("The configuration validations failed.")]
>     ConfigValidation { validation_errors: Vec<validator::ValidationError> },
> ```

Why not ParsedValidationErrors?



_Code quote:_
```XML
Vec<validator::ValidationError> 
```
___
*[`crates/papyrus_config/src/validators.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpa23BfPObLWYdxGn:-NenGzu35JZoM5mfziaZ:b-t4jdq8) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L50)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

not sure, I have implemented Display and From traits for it.
</blockquote></details>

You already have a variant, just change its member (see previous comment)
___
*[`crates/papyrus_config/src/validators.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negque94TBMUlAWDq30:-NeheG6l36NDjNh0K1ru:b-mo06hy) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L74)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

I don't think there is a reason to use an option here.
</blockquote></details>

Oh it's a string, thought it is an Option, sorry...
___
*[`crates/papyrus_config/src/validators.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenIpbZCjcl1TNsiEPn:-NenIpbZCjcl1TNsiEPo:bgrlzat) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_config/src/validators.rs#L68)):*
> ```XML
> 
> // This function gets a ValidationError object and parses it recursively to a ParsedValidationError
> // object.
> ```

Consider adding to the documentation an example of input and its output



_Code quote:_
```XML
// This function gets a ValidationError object and parses it recursively to a ParsedValidationError
// object.
```
___
*[`crates/papyrus_node/src/main.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenJlOj8doHvRkzEjf9:-NenJlOj8doHvRkzEjfA:bg1dqym) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/main.rs#L122)):*
> ```XML
>         error!("{}", ParsedValidationErrors::from(errors));
>         exit(1);
>     }
> ```

Suggestion:
```
config.validate().map_err(ParsedValidationErrors).expect("invalid config");
```



_Code quote:_
```XML
    if let Err(errors) = config.validate() {
        error!("{}", ParsedValidationErrors::from(errors));
        exit(1);
    }
```
___
*[`crates/papyrus_node/src/config/config_test.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenKOnl1MHrurjRntCm:-NenKOnmALoygux0od5i:b-3vjw2o) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/config/config_test.rs#L86)):*
> ```XML
>     // The validate function will fail if the data directory does not exist so we change the path to
>     // point to an exsting directory.
>     default_config.storage.db_config.path_prefix = PathBuf::from("./crates");
> ```

Use just "." 



_Code quote:_
```XML
./crates
```


<!-- Sent from Reviewable.io -->

2023-09-28 06:00 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenLMyWBzyqN3zgSiJ8:-NfPKtBKBRZIUBdne32A:b-qujhng) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can you add verification that the config files exist in `update_config_map_by_custom_configs`?
I think that currently it will be mapped to the wrong error (`WriteDumpedConfig`)
</blockquote></details>

it doesn't really work with the validator crate because it is not a part of a struct.
I just changed the Error name to IOError. wdyt?

___
___
*[`crates/papyrus_config/src/lib.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemS_6SE8PRBcgOIZwd:-NfP5G2l25SLMyEhvFoN:b15v1hb) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_config/src/lib.rs#L169)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why not ParsedValidationErrors?
</blockquote></details>

actually this error is not used, I'm removing it
___
*[`crates/papyrus_config/src/validators.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpa23BfPObLWYdxGn:-NfPCVNWAeyqgyhxCs0g:b-5ju3ig) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L50)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You already have a variant, just change its member (see previous comment)
</blockquote></details>

I removed it (see previous comment). do you think we need it if no one uses it?
___
*[`crates/papyrus_config/src/validators.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenIpbZCjcl1TNsiEPn:-NfP7hK6BL_j2mqr3H98:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_config/src/validators.rs#L68)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider adding to the documentation an example of input and its output
</blockquote></details>

done
___
*[`crates/papyrus_node/src/main.rs` line 122 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenJlOj8doHvRkzEjf9:-NfPAEPv5KRBYUXzgLAC:b2pe6a6) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/main.rs#L122)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Suggestion:
```
config.validate().map_err(ParsedValidationErrors).expect("invalid config");
```
</blockquote></details>

I don't like the way it is printed :
thread 'main' panicked at 'invalida config: ConfigValidation { validation_errors: ParsedValidationErrors([ParsedValidationError { param_path: "storage.db_config.path_prefix", code: "file or directory not found", message: Some("Please create the file/directory or change the path in the configuration."), params: "./data" }]) }', crates/papyrus_node/src/main.rs:119:133


compared to the original code:

2023-09-28T05:06:35.019104Z ERROR Configuration error: The field "storage.db_config.path_prefix" has an error "file or directory not found" with value: "./data" 
"Please create the file/directory or change the path in the configuration." 


So I think this is a better print, but maybe it is not consistent with other error we are printing. 
___
*[`crates/papyrus_node/src/config/config_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemW-820_UjYy9exqM0:-NfPB3MFECO4qv1mHtwU:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/config/config_test.rs#L85)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

existing
</blockquote></details>

Done.
___
*[`crates/papyrus_node/src/config/config_test.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenKOnl1MHrurjRntCm:-NfPB4TECvlcpd1OIroN:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/config/config_test.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use just "."
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-09-28 06:16 UTC, OmriEshhar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware and @yair-starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemW-820_UjYy9exqM0:-NfPQfB170cefza-STvL:bfi9bne) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/config/config_test.rs#L85)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done...


<!-- Sent from Reviewable.io -->

2023-09-28 06:25 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @OmriEshhar1 and @yair-starkware)

___
*[`crates/papyrus_node/src/config/config_test.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemW-820_UjYy9exqM0:-NfPSaRIC4vCsqbfGbtZ:b-fnt23i) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_node/src/config/config_test.rs#L85)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

not done...
</blockquote></details>

done :)


<!-- Sent from Reviewable.io -->

2023-09-28 06:54 UTC, OmriEshhar1 reviewed
> Reviewed 3 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2023-09-28 07:47 UTC, yair-starkware reviewed
> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1, @Yael-Starkware, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenLMyWBzyqN3zgSiJ8:-NfPixO4CzX4PRr6Q6xk:b-4khml5) (no related file):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

it doesn't really work with the validator crate because it is not a part of a struct.
I just changed the Error name to IOError. wdyt?
</blockquote></details>

I think it can still use the `validate_path_exists`, even without using the `validate` function

___
___
*[`crates/papyrus_config/src/validators.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpa23BfPObLWYdxGn:-NfPiZa6-m2Z2zTX_Vr3:bk7ft4d) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L50)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

I removed it (see previous comment). do you think we need it if no one uses it?
</blockquote></details>

I think that we should wrap the `validate` function in our custom function that returns our own error. 
@yoavGrs WDYT?
___
*[`crates/papyrus_config/src/validators.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NfPgdSg44Xtdl3IcOIH:-NfPgdSg44Xtdl3IcOII:bwkpd22) ([raw file](https://github.com/starkware-libs/papyrus/blob/598d63ba49492c2cc3f6249902f598201a591af0/crates/papyrus_config/src/validators.rs#L79)):*
> ```XML
> // Configuration error: The field "storage.db_config.path_prefix" has an error "file or directory
> // not found" with value: "./data" "Please create the file/directory or change the path in the
> // configuration."
> ```

Something in the lining and quotation marks seems wrong. Is this precisely what is printed on the screen? 



_Code quote:_
```XML
// Example of a ParsedValidationError object printed:
// Configuration error: The field "storage.db_config.path_prefix" has an error "file or directory
// not found" with value: "./data" "Please create the file/directory or change the path in the
// configuration."
```


<!-- Sent from Reviewable.io -->

2023-09-28 07:53 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1, @yair-starkware, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenLMyWBzyqN3zgSiJ8:-NfPlObf00P2MhP4uINS:b1q0jvu) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think it can still use the `validate_path_exists`, even without using the `validate` function
</blockquote></details>

Yes, but it returns a different  error type ValidationError and not Validation Errors, this related to the question you wrote below to @yoavGrs about having a wrapper.

___
___
*[`crates/papyrus_config/src/validators.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NfPgdSg44Xtdl3IcOIH:-NfPl8o60Za_CcaGHN2G:b-ff12ya) ([raw file](https://github.com/starkware-libs/papyrus/blob/598d63ba49492c2cc3f6249902f598201a591af0/crates/papyrus_config/src/validators.rs#L79)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Something in the lining and quotation marks seems wrong. Is this precisely what is printed on the screen?
</blockquote></details>

yes, except that the msg "Please create the file/directory or change the path in the
configuration." is printed in a new line.


<!-- Sent from Reviewable.io -->

2023-09-28 08:31 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1, @yair-starkware, and @yoavGrs)

___
*[`crates/papyrus_config/src/validators.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NfPgdSg44Xtdl3IcOIH:-NfPuWu73NMKamIBppg2:bihsld1) ([raw file](https://github.com/starkware-libs/papyrus/blob/598d63ba49492c2cc3f6249902f598201a591af0/crates/papyrus_config/src/validators.rs#L79)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

yes, except that the msg "Please create the file/directory or change the path in the
configuration." is printed in a new line.
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/70628564/U3J_eN4vJfyc97LBc5-vrIZc/image.png)


<!-- Sent from Reviewable.io -->

2023-09-28 08:43 UTC, yoavGrs reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1, @Yael-Starkware, and @yair-starkware)

___
*[`crates/papyrus_config/src/validators.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpa23BfPObLWYdxGn:-NfPx5ibEmA3NcDc-yYO:b-ba7jcz) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L50)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think that we should wrap the `validate` function in our custom function that returns our own error. 
@yoavGrs WDYT?
</blockquote></details>

Sounds good to me.


<!-- Sent from Reviewable.io -->

2023-09-28 08:49 UTC, yair-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1, @Yael-Starkware, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenLMyWBzyqN3zgSiJ8:-NfPxD4I4loxgMx-0qAu:bltb7vy) (no related file):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

Yes, but it returns a different  error type ValidationError and not Validation Errors, this related to the question you wrote below to @yoavGrs about having a wrapper.
</blockquote></details>

Talked with @yoavGrs, he agrees about wrapping the Validate crate functionality with our own functions.
You can convert the Validation error to Config error after calling the function

___
___
*[`crates/papyrus_config/src/validators.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NfPgdSg44Xtdl3IcOIH:-NfPxqUR33Q4e_sAb0GV:bw846uc) ([raw file](https://github.com/starkware-libs/papyrus/blob/598d63ba49492c2cc3f6249902f598201a591af0/crates/papyrus_config/src/validators.rs#L79)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/70628564/U3J_eN4vJfyc97LBc5-vrIZc/image.png)
</blockquote></details>

Can we do something with the quotation marks (not blocking)?
And please fix the comment with the correct lining (I think you can put the text inside \``` \``` block so fmt won't fail)


<!-- Sent from Reviewable.io -->

2023-10-04 05:05 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1, @yair-starkware, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NenLMyWBzyqN3zgSiJ8:-Nft3hel1mhxXC5MOTZx:b-7rl0kd) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Talked with @yoavGrs, he agrees about wrapping the Validate crate functionality with our own functions.
You can convert the Validation error to Config error after calling the function
</blockquote></details>

done

___
___
*[`crates/papyrus_config/src/lib.rs` line 169 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NemS_6SE8PRBcgOIZwd:-Nft3jFZ2vauO7Im_t48:b-vsae7z) ([raw file](https://github.com/starkware-libs/papyrus/blob/eee7fdfb9290ee4c6327d13635613898d5629a21/crates/papyrus_config/src/lib.rs#L169)):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

actually this error is not used, I'm removing it
</blockquote></details>

It's back now
___
*[`crates/papyrus_config/src/validators.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-Negpa23BfPObLWYdxGn:-Nft3nSI5dNhHapcWKF3:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/c63ad490e6edc2c3f0dcc5938bf9a2d8821b088c/crates/papyrus_config/src/validators.rs#L50)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

done
___
*[`crates/papyrus_config/src/validators.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NfPgdSg44Xtdl3IcOIH:-Nft3ouP2iB_6uGheVtv:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/598d63ba49492c2cc3f6249902f598201a591af0/crates/papyrus_config/src/validators.rs#L79)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Can we do something with the quotation marks (not blocking)?
And please fix the comment with the correct lining (I think you can put the text inside \``` \``` block so fmt won't fail)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-04 06:54 UTC, yair-starkware requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1, @Yael-Starkware, and @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 171 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NftRU5l9fyDjCccEhjp:-NftRU5l9fyDjCccEhjq:b8xnwwc) ([raw file](https://github.com/starkware-libs/papyrus/blob/7554c8975d94add50c45012318f2c19e09dc05e3/crates/papyrus_config/src/lib.rs#L171)):*
> ```XML
>     ChangeRequiredParamType { param_path: String, required: SerializationType, given: Value },
>     #[error(transparent)]
>     ValidationError(#[from] ValidationError),
> ```

Why do we need this variant?



_Code quote:_
```XML
    #[error(transparent)]
    ValidationError(#[from] ValidationError),
```
___
*[`crates/papyrus_config/src/loading.rs` line 126 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NftSgzdCgRJWcDgt0AE:-NftSgzdCgRJWcDgt0AF:b-v6hnkr) ([raw file](https://github.com/starkware-libs/papyrus/blob/7554c8975d94add50c45012318f2c19e09dc05e3/crates/papyrus_config/src/loading.rs#L126)):*
> ```XML
> ) -> Result<(), ConfigError> {
>     for config_path in custom_config_paths {
>         validate_path_exists(&config_path)?;
> ```

Map the error to the parsed type



_Code quote:_
```XML
validate_path_exists(&config_path)?;
```
___
*[`crates/papyrus_config/src/validators.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NftRr8a-qpIAMcaVmhE:-NftRr8bAR9FCi_bmww9:bf4mrb6) ([raw file](https://github.com/starkware-libs/papyrus/blob/7554c8975d94add50c45012318f2c19e09dc05e3/crates/papyrus_config/src/validators.rs#L72)):*
> ```XML
> }
> 
> /// A wrapper function for the validator validate function that returns a ConfigError with ParsedValidationErrors.
> ```

```
/// Validates configuration structs that derive the Validate trait.
```



_Code quote:_
```XML
/// A wrapper function for the validator validate function that returns a ConfigError with ParsedValidationErrors.
```


<!-- Sent from Reviewable.io -->

2023-10-04 08:02 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: all files reviewed, 3 unresolved discussions (waiting on @OmriEshhar1, @yair-starkware, and @yoavGrs)

___
*[`crates/papyrus_config/src/lib.rs` line 171 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NftRU5l9fyDjCccEhjp:-NfteZxF2K1zz9QF-1a8:b1jfapc) ([raw file](https://github.com/starkware-libs/papyrus/blob/7554c8975d94add50c45012318f2c19e09dc05e3/crates/papyrus_config/src/lib.rs#L171)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need this variant?
</blockquote></details>

because the validate_path_exists function returns ValidationError and not ValidationErrors,  this is a different type than what config.validate() returns.
___
*[`crates/papyrus_config/src/loading.rs` line 126 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NftSgzdCgRJWcDgt0AE:-NftgH8D0P_m07Zu08n0:b2io11d) ([raw file](https://github.com/starkware-libs/papyrus/blob/7554c8975d94add50c45012318f2c19e09dc05e3/crates/papyrus_config/src/loading.rs#L126)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Map the error to the parsed type
</blockquote></details>

There is no mechanism to map it atm ( again as I explained, this function returns a different Error struct than the validate() function), and it doesn't hold the same information as the parsed type, for example, it doesn't contain the path inside the structs.
That's why I didn't think it makes sense this function here. 


<!-- Sent from Reviewable.io -->

2023-10-04 09:31 UTC, yair-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-:-Nfu0sDh5iD7bZ88-aFE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OmriEshhar1 and @yoavGrs)



<!-- Sent from Reviewable.io -->

2023-10-04 10:58 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @OmriEshhar1, @yair-starkware, and @yoavGrs)

___
*[`crates/papyrus_config/src/validators.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1188#-NftRr8a-qpIAMcaVmhE:-NfuKgvZ542bK5pcUgLi:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/7554c8975d94add50c45012318f2c19e09dc05e3/crates/papyrus_config/src/validators.rs#L72)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

```
/// Validates configuration structs that derive the Validate trait.
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-04 11:06 UTC, OmriEshhar1 approved these changes
> Reviewed 1 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)



<!-- Sent from Reviewable.io -->

2023-10-04 11:22 UTC, merged