fix: replace expect when using format strings in error message
starkware-libs/papyrus pull request #1329
Opened 2023-10-26 11:08 UTC by TzahiTaub

Replaced with unwrap_or_else so that string allocation will only accure in the errorneous case.

## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Error messages are printed with a variable name instead of its value.

## What is the new behavior?

- The value is printed.

- The error message string will only be computed and allocated in case the error case was actually reached.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-10-26 12:32 UTC, OmriEshhar1 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1329#-NhfxfFb0Z2QJ5LZssuM:-NhfxfFb0Z2QJ5LZssuN:b-pt4w5j) (no related file):*
Is it ok that we have 'unwrap' code in non-test modules?
From the little that I know about rust, 'unwrap' should only be used in tests?
(I'm not sure about using 'panic' either.)

___


<!-- Sent from Reviewable.io -->

2023-10-26 12:40 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1329#-NhfxfFb0Z2QJ5LZssuM:-NhfzCF12AIaXjAjFXJB:bewyisu) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Is it ok that we have 'unwrap' code in non-test modules?
From the little that I know about rust, 'unwrap' should only be used in tests?
(I'm not sure about using 'panic' either.)
</blockquote></details>

I don't know, but it's equivalent to `expect`- expect is `unwrap` with a custom error message. So I'm keeping the exact same behavior we had before (without the print bug).

___


<!-- Sent from Reviewable.io -->

2023-10-26 18:14 UTC, OmriEshhar1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1329#-NhfxfFb0Z2QJ5LZssuM:-NhhBOvv5Lcpi3AR4ior:b3swkgk) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I don't know, but it's equivalent to `expect`- expect is `unwrap` with a custom error message. So I'm keeping the exact same behavior we had before (without the print bug).
</blockquote></details>

just to be sure, please ask Dan or someone from his team or another rust expert.

___


<!-- Sent from Reviewable.io -->

2023-10-29 08:11 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1329#-:-NhuUBEE84l_JlqpoJxF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1329#-NhfxfFb0Z2QJ5LZssuM:-NhuSIY66C161tA1sBu8:bb6ywmx) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

just to be sure, please ask Dan or someone from his team or another rust expert.
</blockquote></details>

LGTM

___


<!-- Sent from Reviewable.io -->

2023-10-29 08:59 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1329)* status: all files reviewed, 1 unresolved discussion (waiting on @OmriEshhar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1329#-NhfxfFb0Z2QJ5LZssuM:-NhueBm7Bpc3Myc33vfH:b-896fix) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-10-29 09:32 UTC, OmriEshhar1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1329)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2023-10-29 09:58 UTC, merged