feat(storage): add a detailed default error message when inserting existing key to DB
starkware-libs/papyrus pull request #1353
Opened 2023-11-02 14:06 UTC by TzahiTaub

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

When trying to insert a key that already exists to the internal DB in papyrus_storage, an error with no info is given by default.

Issue Number: N/A

## What is the new behavior?

Table name, key, and value are logged in the new error.

-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2023-11-02 14:31 UTC, yair-starkware requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFOROB86mCXkycLW-j:-NiFOROB86mCXkycLW-k:boo87hd) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L141)):*
> ```XML
>     /// An error that occurred when tried to insert a key that already exists in a table.
>     #[error(transparent)]
>     KeyAlreadyExists(#[from] KeyAlreadyExistsError),
> ```

I think you don't need the `from` here, just hold the struct



_Code quote:_
```XML
#[from] 
```
___
*[`crates/papyrus_storage/src/db/mod.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFOw4fEcKZEhkJwX75:-NiFOw4fEcKZEhkJwX76:b-ytec8f) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L166)):*
> ```XML
>     }
> }
> impl std::error::Error for KeyAlreadyExistsError {}
> ```

Once you hold the struct in the error variant you won't need this line



_Code quote:_
```XML
impl std::error::Error for KeyAlreadyExistsError {}
```
___
*[`crates/papyrus_storage/src/db/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFQ4qJ-o5UEw3XWUJj:-NiFQ4qJ-o5UEw3XWUJk:b-gksta0) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L278)):*
> ```XML
> }
> 
> pub(crate) struct TableHandle<'env, K: StorageSerde, V: StorageSerde> {
> ```

I think we should require Debug here instead of the insert function



_Code quote:_
```XML
StorageSerde, V: StorageSerde
```


<!-- Sent from Reviewable.io -->

2023-11-02 14:31 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-:-NiFRe5E9E2xgENykpO9:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2023-11-02 14:32 UTC, yair-starkware requested changes
Added LGTM by mistake

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-:-NiFRhJEA9N72-fq1w9y:bewafa4)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2023-11-02 16:39 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFOROB86mCXkycLW-j:-NiFr_EkDzdUGLY2x6GS:b-b1uq6m) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L141)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think you don't need the `from` here, just hold the struct
</blockquote></details>

I need to implement `Display` for `KeyAlreadyExists` somehow, and I can't use the `error` attribute here, so I've implemented it on `KeyAlreadyExistsError` and I'm borrowing it with `from`. If I'll move the fields of `KeyAlreadyExistsError` to `KeyAlreadyExists` I'll lose the `new` function that translate the key and value to it's debug representation.


<!-- Sent from Reviewable.io -->

2023-11-05 11:59 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFOROB86mCXkycLW-j:-NiU9l0bAevAVVIjUxH6:b-k0b9gc) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L141)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I need to implement `Display` for `KeyAlreadyExists` somehow, and I can't use the `error` attribute here, so I've implemented it on `KeyAlreadyExistsError` and I'm borrowing it with `from`. If I'll move the fields of `KeyAlreadyExistsError` to `KeyAlreadyExists` I'll lose the `new` function that translate the key and value to it's debug representation.
</blockquote></details>

OK, done. I've kept the `KeyAlreadyExistsError` struct for its convenience `new` method.
___
*[`crates/papyrus_storage/src/db/mod.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFOw4fEcKZEhkJwX75:-NiU9vmP4jrnd5mfnpRv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L166)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Once you hold the struct in the error variant you won't need this line
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/db/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiFQ4qJ-o5UEw3XWUJj:-NiULVch3MDf2giDSelW:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e61a12fda1cbe32e862bc86c5362078a864155e3/crates/papyrus_storage/src/db/mod.rs#L278)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we should require Debug here instead of the insert function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 12:13 UTC, yair-starkware requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiUOCoV1A6WmhoMchey:-NiUOCoV1A6WmhoMchez:bac6txb) ([raw file](https://github.com/starkware-libs/papyrus/blob/1fd17572213a6f95339c4af6ca4ff2b3f84c9836/crates/papyrus_storage/src/db/mod.rs#L156)):*
> ```XML
> }
> 
> impl KeyAlreadyExistsError {
> ```

Move this code to be right after the struct


<!-- Sent from Reviewable.io -->

2023-11-05 12:16 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353)* status: all files reviewed, 1 unresolved discussion (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/db/mod.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-NiUOCoV1A6WmhoMchey:-NiUP0gi1noF6u7Tkhmp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1fd17572213a6f95339c4af6ca4ff2b3f84c9836/crates/papyrus_storage/src/db/mod.rs#L156)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Move this code to be right after the struct
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 12:26 UTC, yair-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-:-NiURm5SEo2dYrj-fz1h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2023-11-05 13:45 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353#-:-NiUiqnB7DFOSsNLeoHK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2023-11-09 15:42 UTC, yair-starkware approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1353)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2023-11-09 16:07 UTC, merged