fix(storage): fail the node run if the existing storage has a differe…
starkware-libs/papyrus pull request #1413
Opened 2023-11-15 11:11 UTC by Yael-Starkware

…nt scope than the configuration

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-11-15 11:32 UTC, OmriEshhar1 requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHj3dDCZidhXbczBpa:-NjHj3dDCZidhXbczBpb:b-ag0kx0) (no related file):*
wouldn't it be better to add a 'storage scope' entry to the storage_version table instead of figuring it out indirectly from the storage_version_blocks entry?

___
___
*[`crates/papyrus_storage/src/lib.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHh2aH2XMj1N5dwHv3:-NjHh2aH2XMj1N5dwHv4:b-t6uvnd) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bd1c568ee39b544fe8f517164fa0fb431b121b1/crates/papyrus_storage/src/lib.rs#L181)):*
> ```XML
> // In case storage version does not exist, set it to the crate version.
> // Expected to happen once - when the node is launched for the first time.
> // If in FullArchive mode, also set the blocks version.
> ```

Maybe move this comment below, to the area that implements this logic.
And change it to something like:
// Only set the blocks version if in FullArchive mode.



_Code quote:_
```XML
// If in FullArchive mode, also set the blocks version.
```
___
*[`crates/papyrus_storage/src/lib.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHiHLv-Mn4d1KQY1bm:-NjHiHLv-Mn4d1KQY1bn:b-a4c8qu) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bd1c568ee39b544fe8f517164fa0fb431b121b1/crates/papyrus_storage/src/lib.rs#L216)):*
> ```XML
>     let current_storage_version_blocks = reader.begin_ro_txn()?.get_blocks_version()?;
> 
>     if storage_scope == StorageScope::FullArchive {
> ```

consider using 'match' on storage_scope instead of if-else
___
*[`crates/papyrus_storage/src/lib.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHiNmT9UVmTmGrmBU1:-NjHiNmT9UVmTmGrmBU2:bu1f7ur) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bd1c568ee39b544fe8f517164fa0fb431b121b1/crates/papyrus_storage/src/lib.rs#L216)):*
> ```XML
>     let current_storage_version_blocks = reader.begin_ro_txn()?.get_blocks_version()?;
> 
>     if storage_scope == StorageScope::FullArchive {
> ```

Add some comments to explain the different scenarios


<!-- Sent from Reviewable.io -->

2023-11-16 06:30 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @OmriEshhar1 and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHj3dDCZidhXbczBpa:-NjLo6E416taGKZ0mmYP:bje96lo) (no related file):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

wouldn't it be better to add a 'storage scope' entry to the storage_version table instead of figuring it out indirectly from the storage_version_blocks entry?
</blockquote></details>

The storage scope doesn't have any additional information beyond the block version. 
Also I consulted with @yair-starkware about this so adding him to the PR.

___
___
*[`crates/papyrus_storage/src/lib.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHh2aH2XMj1N5dwHv3:-NjLo3YoDl-MiN4WsQWv:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bd1c568ee39b544fe8f517164fa0fb431b121b1/crates/papyrus_storage/src/lib.rs#L181)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Maybe move this comment below, to the area that implements this logic.
And change it to something like:
// Only set the blocks version if in FullArchive mode.
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHiHLv-Mn4d1KQY1bm:-NjLo47c4DP5888eHhEn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bd1c568ee39b544fe8f517164fa0fb431b121b1/crates/papyrus_storage/src/lib.rs#L216)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

consider using 'match' on storage_scope instead of if-else
</blockquote></details>

Done.
___
*[`crates/papyrus_storage/src/lib.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHiNmT9UVmTmGrmBU1:-NjLo4iY0O-bcHa-I-IP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0bd1c568ee39b544fe8f517164fa0fb431b121b1/crates/papyrus_storage/src/lib.rs#L216)):*
<details><summary><i>Previously, OmriEshhar1 wrote…</i></summary><blockquote>

Add some comments to explain the different scenarios
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-16 08:10 UTC, OmriEshhar1 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-:-NjMAdxA-SK-JoN9ZuhE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yair-starkware)



<!-- Sent from Reviewable.io -->

2023-11-16 09:00 UTC, yair-starkware requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: all files reviewed, 4 unresolved discussions (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHj3dDCZidhXbczBpa:-NjMLc4XEWokCxiNUykv:bpawcq6) (no related file):*
<details><summary><i>Previously, Yael-Starkware (yael-starkware) wrote…</i></summary><blockquote>

The storage scope doesn't have any additional information beyond the block version. 
Also I consulted with @yair-starkware about this so adding him to the PR.
</blockquote></details>

I suggest adding a function that returns the scope based on the storage_version table

___
___
*[`crates/papyrus_storage/src/lib.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjMJ9r30Y1tzbqTfyZs:-NjMJ9r30Y1tzbqTfyZt:byaqlcd) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/lib.rs#L227)):*
> ```XML
>                 ));
>             }
>         }
> ```

I disagree with this statement - we should be able to run in state-only mode on full-archive data.



_Code quote:_
```XML
        // In state-only mode, the storage should not have a block version.
        StorageScope::StateOnly => {
            if current_storage_version_blocks.is_some() {
                return Err(StorageError::StorageVersionInconcistency(
                    StorageVersionError::InconsistentStorageScope {
                        existing_scope: StorageScope::FullArchive,
                        requested_scope: StorageScope::StateOnly,
                    },
                ));
            }
        }
```
___
*[`crates/papyrus_storage/src/lib.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjMK2FQDaG3EkABJZj9:-NjMK2FQDaG3EkABJZjA:b9ap0by) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/lib.rs#L240)):*
> ```XML
>             }
>             let current_storage_version_blocks = current_storage_version_blocks
>                 .expect("Storage should have a block version for scope FullArchive");
> ```

Please convert to let-else 



_Code quote:_
```XML
            if current_storage_version_blocks.is_none() {
                return Err(StorageError::StorageVersionInconcistency(
                    StorageVersionError::InconsistentStorageScope {
                        existing_scope: StorageScope::StateOnly,
                        requested_scope: StorageScope::FullArchive,
                    },
                ));
            }
            let current_storage_version_blocks = current_storage_version_blocks
                .expect("Storage should have a block version for scope FullArchive");
```
___
*[`crates/papyrus_storage/src/version.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjMKOi11tpugVAFRR_X:-NjMKOi11tpugVAFRR_Y:b-wesdns) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/version.rs#L26)):*
> ```XML
>          {requested_scope:?}."
>     )]
>     InconsistentStorageScope { existing_scope: StorageScope, requested_scope: StorageScope },
> ```

The only case of this error should be when trying to run a full-archive node on state-only data



_Code quote:_
```XML
    #[error(
        "Storage scope {existing_scope:?} is inconsistent with the requested scope \
         {requested_scope:?}."
    )]
    InconsistentStorageScope { existing_scope: StorageScope, requested_scope: StorageScope },
```
___
*[`crates/papyrus_storage/src/version_test.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjML1PcCu4X2HSLPJpk:-NjML1PcCu4X2HSLPJpl:b-4nudpk) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/version_test.rs#L48)):*
> ```XML
> 
> #[test]
> fn test_verify_storage_version() {
> ```

Please split the test


<!-- Sent from Reviewable.io -->

2023-11-16 16:37 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: all files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjHj3dDCZidhXbczBpa:-NjNbaaA2arS9uoeQLXk:bb7f2mf) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I suggest adding a function that returns the scope based on the storage_version table
</blockquote></details>

done

___
___
*[`crates/papyrus_storage/src/lib.rs` line 227 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjMJ9r30Y1tzbqTfyZs:-NjNbUkX5shL-Dbnky_H:b8sddq9) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/lib.rs#L227)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I disagree with this statement - we should be able to run in state-only mode on full-archive data.
</blockquote></details>

ok , turned it into a warning
___
*[`crates/papyrus_storage/src/lib.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjMK2FQDaG3EkABJZj9:-NjNbIZd9iBqI4CHNvkC:bpagbrg) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/lib.rs#L240)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please convert to let-else
</blockquote></details>

this code was deleted
___
*[`crates/papyrus_storage/src/version.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjMKOi11tpugVAFRR_X:-NjN33-b98Nynp0Kzsyx:bix8al8) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/version.rs#L26)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The only case of this error should be when trying to run a full-archive node on state-only data
</blockquote></details>

ok, I converted the other error into a warning
___
*[`crates/papyrus_storage/src/version_test.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjML1PcCu4X2HSLPJpk:-NjNzc-K2aBYvoJAhoMf:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b7946339e4f0820d456c3b60a7b263e47c1e2340/crates/papyrus_storage/src/version_test.rs#L48)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please split the test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-19 08:33 UTC, yair-starkware requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: all files reviewed, 15 unresolved discussions (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaYtso8R64KDTzTiSr:-NjaYtso8R64KDTzTiSs:b-kg5861) (no related file):*
Please open a single DB transaction when possible

___
___
*[`crates/papyrus_storage/src/lib.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaaULjBaOMjfbhieQF:-NjaaULjBaOMjfbhieQG:b-ivtrr5) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L210)):*
> ```XML
>                     );
>                 }
>             }
> ```

Is this the requirement? Seems weird to me



_Code quote:_
```XML
            StorageScope::FullArchive => {
                if writer.scope == StorageScope::StateOnly {
                    writer.begin_rw_txn()?.delete_blocks_version()?.commit()?;
                    warn!(
                        "Storage was operating in full-archive mode and is now shifting to \
                         state-only mode."
                    );
                }
            }
```
___
*[`crates/papyrus_storage/src/lib.rs` line 214 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaaqVD4uCdWpZqhfwL:-NjaaqVD4uCdWpZqhfwM:b-yn73xh) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L214)):*
> ```XML
>                 // The storage cannot change from state-only to full-archive mode.
>                 if writer.scope == StorageScope::FullArchive {
>                     return Err(StorageError::StorageVersionInconcistency(
> ```

Please add log message
___
*[`crates/papyrus_storage/src/lib.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaZeNb56U9cq1teVrQ:-NjaZeNb56U9cq1teVrR:b-b566om) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L219)):*
> ```XML
>                 }
>             }
>         },
> ```

You can remove a layer of nesting by doing something like this:
```
match existing_storage_state {
  StorageState::Uninitialized => {...}
  StorageState::Initialized(StorageVersion{scope: StorageScope::StateOnly, ..}) => {...}
  StorageState::Initialized(StorageVersion{scope: StorageScope::FullArchive, ..}) => {...}
}
```




_Code quote:_
```XML
        StorageState::Initialized(StorageVersion {
            state_version: _,
            blocks_version: _,
            scope: existing_scope,
        }) => match existing_scope {
            StorageScope::FullArchive => {
                if writer.scope == StorageScope::StateOnly {
                    writer.begin_rw_txn()?.delete_blocks_version()?.commit()?;
                    warn!(
                        "Storage was operating in full-archive mode and is now shifting to \
                         state-only mode."
                    );
                }
            }
            StorageScope::StateOnly => {
                // The storage cannot change from state-only to full-archive mode.
                if writer.scope == StorageScope::FullArchive {
                    return Err(StorageError::StorageVersionInconcistency(
                        StorageVersionError::InconsistentStorageScope,
                    ));
                }
            }
        },
```
___
*[`crates/papyrus_storage/src/lib.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjabFRI4RxALqFBthAK:-NjabFRI4RxALqFBthAL:b-8f9prq) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L229)):*
> ```XML
>     blocks_version: Option<Version>,
>     scope: StorageScope,
> }
> ```

Consider making this struct an enum instead of having an optional blocks_version.



_Code quote:_
```XML
struct StorageVersion {
    state_version: Version,
    blocks_version: Option<Version>,
    scope: StorageScope,
}
```
___
*[`crates/papyrus_storage/src/lib.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaY3Jj3Sz3tpDM4FSq:-NjaY3Jj3Sz3tpDM4FSr:b66j6y7) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L235)):*
> ```XML
>     Uninitialized,
>     Initialized(StorageVersion),
> }
> ```

Consider deleting this type and returning an option of StorageVersion instead.



_Code quote:_
```XML
#[derive(Debug)]
enum StorageState {
    Uninitialized,
    Initialized(StorageVersion),
}
```
___
*[`crates/papyrus_storage/src/lib.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njabj0H0rydMB6RTniW:-Njabj0I5Q_BrbIKUwpT:beq88sf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L237)):*
> ```XML
> }
> 
> fn get_storage_state(reader: StorageReader) -> StorageResult<StorageState> {
> ```

Please rename.
I think `get_storage_version` is good once the version is an enum and the function returns an option.



_Code quote:_
```XML
get_storage_state
```
___
*[`crates/papyrus_storage/src/lib.rs` line 242 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaefuF7y-8qvrYxl7Y:-NjaefuF7y-8qvrYxl7Z:bppognk) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L242)):*
> ```XML
>     if current_storage_version_state.is_none() {
>         return Ok(StorageState::Uninitialized);
>     }
> ```

Convert to let-else (will make the later unwraps unnecessary as a bonus)



_Code quote:_
```XML
    if current_storage_version_state.is_none() {
        return Ok(StorageState::Uninitialized);
    }
```
___
*[`crates/papyrus_storage/src/lib.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njaey_M4YyVyOZgYQmh:-Njaey_M4YyVyOZgYQmi:b-8lzohr) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L251)):*
> ```XML
>         None => Ok(StorageState::Initialized(StorageVersion {
>             state_version: current_storage_version_state.unwrap(),
>             blocks_version: current_storage_version_blocks,
> ```

Make it None explicitly



_Code quote:_
```XML
current_storage_version_blocks
```
___
*[`crates/papyrus_storage/src/lib.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjacSYdAGxXp9fxHniY:-NjacSYe32S702Bv3scM:b-s79t13) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L257)):*
> ```XML
> }
> 
> // Assumes the storage has a version.
> ```

I think this comment is wrong - you do handle the case where storage is not initialized



_Code quote:_
```XML
// Assumes the storage has a version.
```
___
*[`crates/papyrus_storage/src/lib.rs` line 265 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjacpxI85PkR40TrqHL:-NjacpxI85PkR40TrqHM:b-pruyyl) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L265)):*
> ```XML
> 
>     let existing_storage_state = get_storage_state(reader)?;
>     debug!("Existing storage state: {:?}", existing_storage_state);
> ```

I think we want to merge these logs into a single log message



_Code quote:_
```XML
    debug!(
        "Crate storage version: State = {STORAGE_VERSION_STATE:} Blocks = \
         {STORAGE_VERSION_BLOCKS:}."
    );

    let existing_storage_state = get_storage_state(reader)?;
    debug!("Existing storage state: {:?}", existing_storage_state);
```
___
*[`crates/papyrus_storage/src/lib.rs` line 274 at r4](https://rev [...]

2023-11-20 09:20 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: all files reviewed, 11 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaaULjBaOMjfbhieQF:-NjbgbovDK5dfi48RxGL:b-rnrbll) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L210)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Is this the requirement? Seems weird to me
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 214 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaaqVD4uCdWpZqhfwL:-NjfS5HK5yOsUQ0zjBSc:bonzpaj) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L214)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please add log message
</blockquote></details>

done, but only if the version was initialized. Otherwise I don't know what to write.
___
*[`crates/papyrus_storage/src/lib.rs` line 219 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaZeNb56U9cq1teVrQ:-Njbgnit2_haNhW3450r:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L219)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You can remove a layer of nesting by doing something like this:
```
match existing_storage_state {
  StorageState::Uninitialized => {...}
  StorageState::Initialized(StorageVersion{scope: StorageScope::StateOnly, ..}) => {...}
  StorageState::Initialized(StorageVersion{scope: StorageScope::FullArchive, ..}) => {...}
}
```

</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 229 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjabFRI4RxALqFBthAK:-NjfTD2h7emyx3dk9oXF:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L229)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider making this struct an enum instead of having an optional blocks_version.
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 235 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaY3Jj3Sz3tpDM4FSq:-NjfTCBs5xT14VXOwPBy:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L235)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider deleting this type and returning an option of StorageVersion instead.
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 237 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njabj0H0rydMB6RTniW:-NjfTE246x1OsnTuiFV7:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L237)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please rename.
I think `get_storage_version` is good once the version is an enum and the function returns an option.
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 242 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjaefuF7y-8qvrYxl7Y:-NjfV4Ez7mJ9XXlMI8ew:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L242)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Convert to let-else (will make the later unwraps unnecessary as a bonus)
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njaey_M4YyVyOZgYQmh:-NjfVkEF4K6_YAXmiWhT:b-hq3fjd) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L251)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Make it None explicitly
</blockquote></details>

I didn't understand this comment
___
*[`crates/papyrus_storage/src/lib.rs` line 257 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjacSYdAGxXp9fxHniY:-NjfVTGR2a8D3-dEVSz5:b-pw8psq) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L257)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think this comment is wrong - you do handle the case where storage is not initialized
</blockquote></details>

I handle it by panicking , so I think it's pretty accurate.
___
*[`crates/papyrus_storage/src/lib.rs` line 265 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjacpxI85PkR40TrqHL:-NjfV_w_83BHUXNQM4Q8:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L265)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think we want to merge these logs into a single log message
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 274 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjafSAC0CMLhq9Ifair:-NjfYgHP2eiaiAXN4a8Z:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L274)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please use match guards
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/version.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njafysz1iXC6zN_doFo:-NjfYljs1hLb5fAcOAdu:b8qwgwl) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/version.rs#L95)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

I think that if the requirement is to transform the storage to a state-only, then we should delete the data as well, not just the versions
</blockquote></details>

Talked to Dan, he said to add a TODO for that.
___
*[`crates/papyrus_storage/src/version_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjahMPP5WF12hlAOao3:-NjfZ-dX638raWl2NECg:b-yo4neo) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/version_test.rs#L68)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please assert that the error is the one we expect
</blockquote></details>

can't do this easily because there is no PartialEq implementation fro some of the errors in  StorageError. 
___
*[`crates/papyrus_storage/src/version_test.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njah31n-9oTZ_NsNg43:-Njfjm0qAAM9atXzZaC8:b-fsoemf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/version_test.rs#L85)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why are there two identical calls?
</blockquote></details>

it was not identical, to scope was different, but now it is not relevant anymore so I deleted one.


<!-- Sent from Reviewable.io -->

2023-11-20 09:49 UTC, yair-starkware requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njaey_M4YyVyOZgYQmh:-Njg6Kb03dLuJ-1cyIyL:b-vp3vg) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L251)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I didn't understand this comment
</blockquote></details>

It is no longer relevant because now the version is an enum, but in your previous code `current_storage_version_blocks` would always be None here, so I would just pass None to the `blocks_version`'
___
*[`crates/papyrus_storage/src/lib.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njg2Gpq6X6EF-EZ0pyy:-Njg2Gpr1SuSP-SdSYN2:b-syrrse) ([raw file](https://github.com/starkware-libs/papyrus/blob/d4eea4c6147ecfcfdb3d2d7456ecafd893abd6bf/crates/papyrus_storage/src/lib.rs#L209)):*
> ```XML
>             // to StateOnly
>             if writer.scope == StorageScope::StateOnly {
>                 writer.begin_rw_txn()?.delete_blocks_version()?.commit()?;
> ```

Why do we need to delete the blocks version?



_Code quote:_
```XML
writer.begin_rw_txn()?.delete_blocks_version()?.commit()?;
```
___
*[`crates/papyrus_storage/src/lib.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njg5qQw0D65xAMxL9gT:-Njg5qQw0D65xAMxL9gU:b-xbizmh) ([raw file](https://github.com/starkware-libs/papyrus/blob/d4eea4c6147ecfcfdb3d2d7456ecafd893abd6bf/crates/papyrus_storage/src/lib.rs#L251)):*
> ```XML
>             state_version: current_storage_version_state,
>             blocks_version: current_storage_version_blocks.unwrap(),
>         }))),
> ```

Please move the `current_storage_version_blocks` into the pattern matching:
```
Some(current_storage_version_blocks) => Ok(Some(StorageVersion::FullArchive(FullArchiveVersion {
            state_version: current_storage_version_state,
            blocks_version: current_storage_version_blocks,
        }))),
```



_Code quote:_
```XML
        Some(_) => Ok(Some(StorageVersion::FullArchive(FullArchiveVersion {
            state_version: current_storage_version_state,
            blocks_version: current_storage_version_blocks.unwrap(),
        }))),
```
___
*[`crates/papyrus_storage/src/version_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjahMPP5WF12hlAOao3:-Njg7K704eTQBspDjCJG:b33fvhb) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/version_test.rs#L68)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

can't do this easily because there is no PartialEq implementation fro some of the errors in  StorageError.
</blockquote></details>

We use assert_matches for these cases.


<!-- Sent from Reviewable.io -->

2023-11-20 11:46 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @yair-starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 251 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njaey_M4YyVyOZgYQmh:-NjgQvBQ6OchFBgUWj23:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L251)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

It is no longer relevant because now the version is an enum, but in your previous code `current_storage_version_blocks` would always be None here, so I would just pass None to the `blocks_version`'
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/lib.rs` line 274 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjafSAC0CMLhq9Ifair:-NjgTsswAzv1DvYbi0ak:bopwbm) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/lib.rs#L274)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done
</blockquote></details>

Sorry, I hope that now I understood what you meant now.
Done
___
*[`crates/papyrus_storage/src/lib.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njg2Gpq6X6EF-EZ0pyy:-NjgP_pu0Rc8pCIfP8Hi:b1s7fiy) ([raw file](https://github.com/starkware-libs/papyrus/blob/d4eea4c6147ecfcfdb3d2d7456ecafd893abd6bf/crates/papyrus_storage/src/lib.rs#L209)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Why do we need to delete the blocks version?
</blockquote></details>

if the operator runs the node in FullArchive mode and then in StateOnly mode and then again in FullArchive mode, it should fail.  But if the block's version stays there from the first run, then it would not fail.code
___
*[`crates/papyrus_storage/src/lib.rs` line 251 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njg5qQw0D65xAMxL9gT:-NjgQsdx7g-j4mTisuOd:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/d4eea4c6147ecfcfdb3d2d7456ecafd893abd6bf/crates/papyrus_storage/src/lib.rs#L251)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Please move the `current_storage_version_blocks` into the pattern matching:
```
Some(current_storage_version_blocks) => Ok(Some(StorageVersion::FullArchive(FullArchiveVersion {
            state_version: current_storage_version_state,
            blocks_version: current_storage_version_blocks,
        }))),
```
</blockquote></details>

done
___
*[`crates/papyrus_storage/src/version_test.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-NjahMPP5WF12hlAOao3:-NjgYF5e2rpQG1DgItZK:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/a60931196fc3b70c9d42fac164fe7dfb29cb88b9/crates/papyrus_storage/src/version_test.rs#L68)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

We use assert_matches for these cases.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-20 13:57 UTC, yair-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-:-Njh0QehD2CqQqqZ1jHr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)

___
*[`crates/papyrus_storage/src/lib.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-Njg2Gpq6X6EF-EZ0pyy:-NjgywRoETFf0yzJ3rNO:b-itqsi1) ([raw file](https://github.com/starkware-libs/papyrus/blob/d4eea4c6147ecfcfdb3d2d7456ecafd893abd6bf/crates/papyrus_storage/src/lib.rs#L209)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

if the operator runs the node in FullArchive mode and then in StateOnly mode and then again in FullArchive mode, it should fail.  But if the block's version stays there from the first run, then it would not fail.code
</blockquote></details>

Please doc this


<!-- Sent from Reviewable.io -->

2023-11-21 08:09 UTC, yair-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1413#-:-NjkvI-80rnH0diJYABi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2023-11-21 08:43 UTC, merged