feat(network): add block headers protocol
starkware-libs/papyrus pull request #1553
Opened 2023-12-25 13:53 UTC by nagmo-starkware

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-12-25 13:53 UTC, nagmo-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1531** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1531?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1535** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1536** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1536?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1553** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #1537** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1537?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1534** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1532** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/1532?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/1553?utm_source=stack-comment).

2023-12-26 14:33 UTC, ShahakShama commented
*[`crates/papyrus_network/src/db_executor.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaXnqj1QiCwjMYhGhh:-NmaXnqj1QiCwjMYhGhi:bmc000n) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/db_executor.rs#L23)):*
> ```XML
> }
> 
> struct DummyDBExecutor {
> ```

Move dummy to a separate file


<!-- Sent from Reviewable.io -->

2023-12-26 14:52 UTC, ShahakShama requested changes
> Reviewed 10 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 8 of 12 files reviewed, 27 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaVUyG9WICuop9_OuB:-NmaVUyG9WICuop9_OuC:b9trfvx) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/Cargo.toml#L14)):*
> ```TOML
> derive_more.workspace = true
> futures.workspace = true
> libp2p = { workspace = true, features = ["identify", "noise", "tcp", "tokio", "yamux"] }
> ```

Consider making a feature for executables and turning these features on only when that feature is on
___
*[`crates/papyrus_network/Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaVd8m2RQUNS00VL3B:-NmaVd8nBVwDgCBu03dn:buo9nmt) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/Cargo.toml#L20)):*
> ```TOML
> starknet_api.workspace = true
> thiserror.workspace = true
> tokio = { workspace = true, features = ["full", "sync"] }
> ```

Same here
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaVnJeBNI3iu6q0X1V:-NmaVnJeBNI3iu6q0X1W:b-jelpv8) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L1)):*
> ```XML
> #[cfg(test)]
> ```

Make this file into a directory with three files: the test file, lib.rs with everything here except the behaviour, and behaviour.rs with the behaviour
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYJKs4VjGEFZviBXy:-NmaYJKs4VjGEFZviBXz:b-g4ierx) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L1)):*
> ```XML
> #[cfg(test)]
> ```

WDYT about dropping the _protocol from this file and from streamed_data_protocol
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaW8oC1gjhtQ8vtvDN:-NmaW8oC1gjhtQ8vtvDO:b-9vo3x2) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L25)):*
> ```XML
> use crate::{BlockHeader, BlockHeaderData, BlockQuery, Signature};
> 
> #[cfg_attr(test, derive(Debug))]
> ```

I'm not sure we don't want to print errors when we're not in test mode
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWE4z-vbUe1Z24Pdq:-NmaWE4z-vbUe1Z24Pdr:bkp7qko) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L26)):*
> ```XML
> 
> #[cfg_attr(test, derive(Debug))]
> pub(crate) enum SessionError {
> ```

Derive from thiserror
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWqKg0H77JhkzNAGj:-NmaWqKg0H77JhkzNAGk:bepkfji) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L27)):*
> ```XML
> #[cfg_attr(test, derive(Debug))]
> pub(crate) enum SessionError {
>     Inner(streamed_data_protocol::behaviour::SessionError),
> ```

Swap all instances of the word Inner/inner with the word StreamedData/streamed_data
If you don't like the name StreamedData, suggest a different name and I'll rename the streamed_data module
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWc-833GhjYR1ZGG4:-NmaWc-833GhjYR1ZGG5:b-k6z1we) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L32)):*
> ```XML
>     SessionClosedUnexpectedly,
>     WaitingToCompleteBatching,
>     ReceivedFin,
> ```

Not sure this is an error
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaasYg7nuCLnPzugoA:-NmaasYg7nuCLnPzugoB:bkp7qko) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L78)):*
> ```XML
> 
> #[cfg_attr(test, derive(Debug))]
> enum BehaviourInternalError {
> ```

Derive from thiserror
___
*[`crates/papyrus_network/src/db_executor.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaXvjz3K-2mp_VvDVq:-NmaXvjz3K-2mp_VvDVr:bwdl21m) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/db_executor.rs#L56)):*
> ```XML
>     }
> 
>     // fn get_next_data(&self) -> Some(BlockHeader) {
> ```

See if you can erase this
___
*[`crates/papyrus_network/src/lib.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYAT85k9RAsmVHdfd:-NmaYAT85k9RAsmVHdfe:byon7pa) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L32)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::BlockHeadersRequest> for BlockQuery {
> ```

Move to block_headers_protocol
___
*[`crates/papyrus_network/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYVkW0VNdKZIrb7Ca:-NmaYVkW0VNdKZIrb7Cb:bdd2p9v) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L63)):*
> ```XML
> 
> #[derive(Debug)]
> pub struct Signature {
> ```

Put the same TODO here ( @yair-starkware recently added signature to SN-API)
___
*[`crates/papyrus_network/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYnDIEz5dR3UzTStJ:-NmaYnDIEz5dR3UzTStK:b-dh0rfm) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L63)):*
> ```XML
> 
> #[derive(Debug)]
> pub struct Signature {
> ```

Move to block_headers_protocol
If you split the file of block_headers_protocol, create a separate files for these called objects.rs
___
*[`crates/papyrus_network/src/lib.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYdHSA9QD3ioDpJUf:-NmaYdHSA9QD3ioDpJUg:b-8ea610) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L68)):*
> ```XML
> }
> 
> // TODO(nevo): decide if we need this struct or we can covert the protobuf directly to starkent api
> ```

typo starkent -> starknet
___
*[`crates/papyrus_network/src/lib.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYpwY-2qeFGvEYolr:-NmaYpwY-2qeFGvEYols:byon7pa) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L71)):*
> ```XML
> // BlockHeader.
> #[derive(Debug)]
> pub struct BlockHeader {
> ```

Move to block_headers_protocol
___
*[`crates/papyrus_network/src/lib.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYs7q4c2_ix7xCByh:-NmaYs7q4c2_ix7xCByi:byon7pa) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L84)):*
> ```XML
> }
> 
> impl TryFrom<ConsensusSignature> for Signature {
> ```

Move to block_headers_protocol
___
*[`crates/papyrus_network/src/lib.rs` line 99 at r1](https://reviewable.io/ [...]

2023-12-26 14:57 UTC, ShahakShama reviewed
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 10 of 12 files reviewed, 26 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmabWrQ413ENAq01EJD:-NmabWrQ413ENAq01EJE:b-ymaf4a) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L113)):*
> ```XML
>     #[allow(dead_code)]
>     pub fn send_query(&mut self, query: protobuf::BlockHeadersRequest, peer_id: PeerId) {
>         let _outbound_session_id = self.inner_behaviour.send_query(query, peer_id);
> ```

Add TODO to map the data to the peer using the outbound_session_id 


<!-- Sent from Reviewable.io -->

2023-12-26 14:59 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 10 of 12 files reviewed, 26 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaVUyG9WICuop9_OuB:-Nmack5mDtcDjm7ODR0D:bb04i13) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/Cargo.toml#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider making a feature for executables and turning these features on only when that feature is on
</blockquote></details>

Also, why do you need identify?


<!-- Sent from Reviewable.io -->

2023-12-27 13:10 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 10 of 12 files reviewed, 21 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/papyrus_network/Cargo.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaVUyG9WICuop9_OuB:-NmetZ4g8iz-RIVoPhs0:b-1zlmwj) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/Cargo.toml#L14)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Also, why do you need identify?
</blockquote></details>

all of these features are needed. not sure about you first suggestion.. let's talk f2f
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaVnJeBNI3iu6q0X1V:-NmewcQVDVh80ib53hCJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Make this file into a directory with three files: the test file, lib.rs with everything here except the behaviour, and behaviour.rs with the behaviour
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaW8oC1gjhtQ8vtvDN:-Nmewg24-P3lY3TciEEZ:bmetmgy) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L25)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I'm not sure we don't want to print errors when we're not in test mode
</blockquote></details>

if there will be a case we do then the compiler will tell us to change this.. but.. since I changes to derive from "thiserror" I needed to derive from debug as well
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWE4z-vbUe1Z24Pdq:-Nmewq6W9tL6ajFQ2_OS:bb7f2mf) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L26)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Derive from thiserror
</blockquote></details>

done
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWqKg0H77JhkzNAGj:-NmexGoaAxdPxOLHtglo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Swap all instances of the word Inner/inner with the word StreamedData/streamed_data
If you don't like the name StreamedData, suggest a different name and I'll rename the streamed_data module
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmabWrQ413ENAq01EJD:-NmfD5mDAU8iK99f228l:b-r2k8o) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L113)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Add TODO to map the data to the peer using the outbound_session_id
</blockquote></details>

not sure I need to since the inner behaviour does this.. 
___
*[`crates/papyrus_network/src/db_executor.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaXnqj1QiCwjMYhGhh:-NmfDv9R-ymFm5L3I0Z_:b-x2hhia) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/db_executor.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move dummy to a separate file
</blockquote></details>

I prefer not to do this at the moment.. not sure what I'm going to do with this yet so I'm trying not to spread it around the codebase
___
*[`crates/papyrus_network/src/lib.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYAT85k9RAsmVHdfd:-NmfEXIdC_hs1CSLk2zD:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L32)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move to block_headers_protocol
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYVkW0VNdKZIrb7Ca:-NmfEfJr7IR05HVk15nV:b-neu3g8) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L63)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Put the same TODO here ( @yair-starkware recently added signature to SN-API)
</blockquote></details>

same todo as?
___
*[`crates/papyrus_network/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYnDIEz5dR3UzTStJ:-NmfK2mWAO1EmOsteiC5:bv85ft2) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L63)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move to block_headers_protocol
If you split the file of block_headers_protocol, create a separate files for these called objects.rs
</blockquote></details>

I moved it to mod.rs
___
*[`crates/papyrus_network/src/lib.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYpwY-2qeFGvEYolr:-NmfK5ZhEWeMfeTu1NXX:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L71)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move to block_headers_protocol
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYs7q4c2_ix7xCByh:-NmfK61cCt7MNND9qEfa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L84)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move to block_headers_protocol
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYsiWDbs-aq71e9qe:-NmfK6fE7verrbVFJe5t:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L99)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move to block_headers_protocol
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 120 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYtld18-rfcKSxPlu:-NmfK77N14vIJAsxunxi:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L120)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Move to block_headers_protocol
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/node.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaZLPS6aR0INgt5pgU:-NmfKJ111a52jT1i18j4:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/bin/node.rs#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></s [...]

2023-12-27 15:09 UTC, ShahakShama requested changes
> Reviewed 12 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 15 of 21 files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaYVkW0VNdKZIrb7Ca:-Nmfk8adBTf9d76W0RbK:b-qr70k6) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/lib.rs#L63)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

same todo as?
</blockquote></details>

I'll write in the moved code so you'll see it better
___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfkZbvEKOGyE4VUZOv:-NmfkZbvEKOGyE4VUZOw:b-vvjlq8) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/mod.rs#L27)):*
> ```XML
>     WaitingToCompleteBatching,
>     #[error("received fin")]
>     ReceivedFin,
> ```

Moved the comment from before: Not sure this is an error.
Also, if it is, you need to supply the fin message you've got
___
*[`crates/papyrus_network/src/messages/mod.rs` line 140 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nma_oHb4lDL6iEmaf03:-NmfoO0i2LBPQKGGa33N:b-3x1pkn) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/messages/mod.rs#L140)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

StarkHash is a StarkFelt so I convert to the lowest option..
</blockquote></details>

But this is a Hash. It makes more sense to convert it to StarkHash
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWqKg0H77JhkzNAGj:-Nmfko-wEkEjE1S1en9v:b-asmsrs) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L27)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still not done. You still have stuff like inner_behaviour, 
___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmabWrQ413ENAq01EJD:-NmfnWhJEYf2Cj4QmJIr:b-ly1yll) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L113)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

not sure I need to since the inner behaviour does this..
</blockquote></details>

The inner behaviour just returns each data coupled with the outbound_session_id it came from. Someone needs to keep this mapping for reputation (that's why a TODO will suffice)


<!-- Sent from Reviewable.io -->

2023-12-27 15:32 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 15 of 21 files reviewed, 12 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmfq5Lj71jtuRPbsMWu:-Nmfq5Lj71jtuRPbsMWv:b1w5sj2) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/mod.rs#L36)):*
> ```XML
> pub(crate) enum Event {
>     NewInboundQuery { query: BlockQuery, inbound_session_id: streamed_data::InboundSessionId },
>     RecievedData { data: BlockHeaderData, outbound_session_id: streamed_data::OutboundSessionId },
> ```

You can put the TODO I told you about mapping the outbound_session_id to peer_id here instead. In that case it will be a TODO to put peer_id instead of or in addition to the outbound session id
___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfqG2V80e4LM6OPP7N:-NmfqG2V80e4LM6OPP7O:b-pjpmxo) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/mod.rs#L42)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::BlockHeadersRequest> for BlockQuery {
> ```

The TODO from before you should add here is:
// TODO(nevo): decide if we need this struct or we can covert the protobuf directly to starknet api
// Signature.
___
*[`crates/papyrus_network/src/streamed_data/handler_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmftOUk1gX4FG8uzPKO:-NmftOUk1gX4FG8uzPKP:b-phy4al) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/streamed_data/handler_test.rs#L338)):*
> ```XML
>     for data in &dummy_data_vec {
>         #[allow(clippy::needless_borrow)]
>         // needless borrow needed here because the compiler doesn't understand that data is a ref
> ```

Let's try tomorrow f2f to get rid of this
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmfqex03Y2QiPMmJtWt:-Nmfqex03Y2QiPMmJtWu:bhn6xl3) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L85)):*
> ```XML
>     /// return false if the query id is not mapped to any session.
>     #[allow(dead_code)]
>     pub fn send_data(&mut self, data: Data, query_id: QueryId) -> bool {
> ```

Create an empty error type (an enum with a single unit variant) for this and return Result<(), ...>
See streamed_data::Behaviour::send_data for reference
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfrZy28yyENfnavUOu:-NmfrZy28yyENfnavUOv:b-7gg7gc) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L87)):*
> ```XML
>     pub fn send_data(&mut self, data: Data, query_id: QueryId) -> bool {
>         let inbound_session_id = self.query_id_to_inbound_session_id.get(&query_id);
>         if let Some(inbound_session_id) = inbound_session_id {
> ```

Use let-else to remove 1 indentation for the rest of the code
If you accept my suggestion from above, you can do `.ok_or(...)?` instead
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfsKAF6cr6O0EJj7a3:-NmfsKAF6cr6O0EJj7a4:b-f2uorh) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L88)):*
> ```XML
>         let inbound_session_id = self.query_id_to_inbound_session_id.get(&query_id);
>         if let Some(inbound_session_id) = inbound_session_id {
>             let (header_message, _block_number) = match data {
> ```

Why do you calculate block_number if you don't use it? (I assume the fact the variable is called _block_number means you don't use it)
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfsYA79hA723NXV0fi:-NmfsYA79hA723NXV0fj:b-dl7t7a) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L99)):*
> ```XML
>                 }
>                 Data::Fin { block_number } => (
>                     protobuf::block_headers_response_part::HeaderMessage::Fin(Default::default()),
> ```

Why default()? FYI AFAIK default means the empty message. IMO you can put `Unknown` here with a TODO to put the proper value
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmft8ci5QXsL2buQDb3:-Nmft8ci5QXsL2buQDb4:b-bkp1aa) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L120)):*
> ```XML
>                 #[allow(clippy::clone_on_copy)]
>                 // we need to clone here since we need self.query_id_to_inbound_session_id to be
>                 // mutable.
> ```

I think we don't need this allow(clippy). Let's try tomorrow f2f to fix this


<!-- Sent from Reviewable.io -->

2023-12-28 08:36 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 15 of 21 files reviewed, 25 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjTjeQCXulwNbFlH65:-NmjTjeQCXulwNbFlH66:b3iy1i1) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L49)):*
> ```XML
> }
> 
> pub(crate) trait BehaviourTrait {
> ```

Why does this trait exist? I agree that the behaviour needs to implement this function but why is it a trait?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 152 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjVRLY8a5OGgXvjCls:-NmjVRLY8a5OGgXvjClt:bscin0h) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L152)):*
> ```XML
>     /// returns true if the inbound session id was pending to be matched with a query id and was not
>     /// in the map before.
>     pub fn register_query_id(
> ```

Why is this function pub?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjQ3TqAUC0gFih5KY-:-NmjQ3TqAUC0gFih5KY0:bxxmd92) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L168)):*
> ```XML
>         &self,
>         header_message: &protobuf::block_headers_response_part::HeaderMessage,
>     ) -> Result<(Option<BlockHeader>, Option<Vec<Signature>>), BehaviourInternalError> {
> ```

The return type is very wierd. Why not an enum of BlockHeader and Signature?
Also, why a method and not a utility function in a different file
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 192 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjQLBsD2dyl5_Txv7r:-NmjQLBsD2dyl5_Txv7s:b-1bgk5d) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L192)):*
> ```XML
> 
>     // this function assumes that the data and header_message are each one of block header or
>     // signatures but not the same one. the function will return error if both  parameter will
> ```

double space: "both  parameter" -> "both parameter"
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjRW3JAiKTnCEgM5xw:-NmjRW3JAiKTnCEgM5xx:b-avhxs) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L194)):*
> ```XML
>     // signatures but not the same one. the function will return error if both  parameter will
>     // evaluate to none or the same type.
>     fn get_block_header_and_signatures_from_event_and_stored_data(
> ```

This function doesn't need to be in this file too
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjWqer7fI7U5ipZJ20:-NmjWqer7fI7U5ipZJ21:b929xxn) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L194)):*
> ```XML
>     // signatures but not the same one. the function will return error if both  parameter will
>     // evaluate to none or the same type.
>     fn get_block_header_and_signatures_from_event_and_stored_data(
> ```

This function name is incorrect. there are no events here
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 211 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjX-a4ANBEgsJM-EPR:-NmjS5dsA4CGdPW3wJa_:b-v14qdu) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L211)):*
> ```XML
>     }
> 
>     pub fn handle_batching(
> ```

I don't like the name batching. It will mean grouping multiple blocks to a single message in the future. Rename to pairing throughout the code
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 211 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjYQqw0nUGK09Nhckr:-NmjYQqw0nUGK09Nhcks:b-jpgu0y) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L211)):*
> ```XML
>     }
> 
>     pub fn handle_batching(
> ```

Why is this function pub
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 251 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjY51pC4wduCDykplv:-NmjY51pC4wduCDykplw:b-ctonlm) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L251)):*
> ```XML
>         outbound_session_id: OutboundSessionId,
>         ignore_event_and_return_pending: &mut bool,
>     ) -> Event {
> ```

I think there are too much functions here that do the same thing and call each other and it's unclear what each of them does. Let's retry. Return to a single function called `handle_received_data` with all the code you need and from there extract functionality to a helper function in a way that the helper functions make sense and have a good name
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 356 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjYY874-ezLOYzrgMo:-NmjYY874-ezLOYzrgMp:botcd0h) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L356)):*
> ```XML
>     ) -> Event {
>         match in_event {
>             streamed_data::behaviour::Event::NewInboundSession {
> ```

Consider importing streamed_data::behaviour::Event as StreamedDataEvent
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 369 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjYlbW1o7WK_FRF96V:-NmjYlbW1o7WK_FRF96W:b-d5zrxd) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L369)):*
> ```XML
>             streamed_data::GenericEvent::SessionClosedByPeer { session_id } => {
>                 let SessionId::OutboundSessionId(outbound_session_id) = session_id else {
>                     return Event::SessionFailed {
> ```

This is not the correct way to handle this. An InboundSession can be closed by other peer and then you just need to cancel the request from the DBExecutor
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 444 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjSclD00wADmdTJdog:-NmjSclD00wADmdTJdoh:b-pj7l8j) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L444)):*
> ```XML
>         cx: &mut Context<'_>,
>     ) -> Poll<ToSwarm<Self::ToSwarm, <Self::ConnectionHandler as ConnectionHandler>::FromBehaviour>>
>     {
> ```

Where do you poll the DB executor
___
*[`crates/papyrus_network/src/block_headers/block_headers_test.rs` line 167 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjTSlQBNTy79Zxb9LA:-NmjTSlQBNTy79Zxb9LB:btkng3s) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/block_headers_test.rs#L167)):*
> ```XML
> }
> 
> struct TestBehaviour {
> ```

You don't use this struct


<!-- Sent from Reviewable.io -->

2023-12-28 10:49 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 15 of 21 files reviewed, 21 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/block_headers_protocol.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaWqKg0H77JhkzNAGj:-NmjS3vmDHtZkIewkLML:b-c6f5ns) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/block_headers_protocol.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This is still not done. You still have stuff like inner_behaviour,
</blockquote></details>

oh got it.. I thought you were talking about the errors
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjTjeQCXulwNbFlH65:-NmjixYy4W27kBZWWN2z:b9zka3l) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L49)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why does this trait exist? I agree that the behaviour needs to implement this function but why is it a trait?
</blockquote></details>

I mock it in the test
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 85 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmfqex03Y2QiPMmJtWt:-Nmjmnvx0LrX9nm5BQjC:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L85)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Create an empty error type (an enum with a single unit variant) for this and return Result<(), ...>
See streamed_data::Behaviour::send_data for reference
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfsKAF6cr6O0EJj7a3:-NmjmwCb7ZaJBZLF4EGJ:b-jp377f) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L88)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why do you calculate block_number if you don't use it? (I assume the fact the variable is called _block_number means you don't use it)
</blockquote></details>

correct
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 99 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfsYA79hA723NXV0fi:-NmjnHUh6p_KiFjQUsL4:b741af5) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L99)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why default()? FYI AFAIK default means the empty message. IMO you can put `Unknown` here with a TODO to put the proper value
</blockquote></details>

I think in this case default is to proper value.. since fin message has just one potential variant
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 120 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmft8ci5QXsL2buQDb3:-NmjnWHg42lTgBtJfzXd:b-b5vqyp) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L120)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think we don't need this allow(clippy). Let's try tomorrow f2f to fix this
</blockquote></details>

if you have a better suggestion I'm open to it.. that's the only option I found to work
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 152 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjVRLY8a5OGgXvjCls:-NmjnxBg2pg7BbVXiyt8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L152)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is this function pub?
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 168 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjQ3TqAUC0gFih5KY-:-NmjpWvkBHNfuLhvlx1z:bweauue) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L168)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

The return type is very wierd. Why not an enum of BlockHeader and Signature?
Also, why a method and not a utility function in a different file
</blockquote></details>

it's not a utility function.. it's a part of the logic of the main function called "handle_batching" it's just long so I split it to sub functions.. I don't think it needs to move
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjRW3JAiKTnCEgM5xw:-NmjpkqqBWlVqs1EBX-O:b-s3efnn) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L194)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This function doesn't need to be in this file too
</blockquote></details>

same argument as above
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 194 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjWqer7fI7U5ipZJ20:-NmjqW1T-6uBVZha6s4k:b-cz3d4x) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L194)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This function name is incorrect. there are no events here
</blockquote></details>

the data is the event.. is it more clear now?
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 211 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjX-a4ANBEgsJM-EPR:-NmjsGg3-USfZeTOE4cn:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L211)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't like the name batching. It will mean grouping multiple blocks to a single message in the future. Rename to pairing throughout the code
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 211 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjYQqw0nUGK09Nhckr:-NmjsNypELihrEHbKzvI:b-bweynt) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L211)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Why is this function pub
</blockquote></details>

I test it directly so it needs to not be private.. changed to pub(crate)
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 251 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjY51pC4wduCDykplv:-NmjsY1dCfI78qwe9j1k:b-w3ffrm) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L251)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I think there are too much functions here that do the same thing and call each other and it's unclear what each of them does. Let's retry. Return to a single function called `handle_received_data` with all the code you need and from ther [...]

2023-12-28 11:02 UTC, ShahakShama requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 15 of 21 files reviewed, 16 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmjTjeQCXulwNbFlH65:-Nmk3g6_18aKF3C59D6h:btw5thp) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/behaviour.rs#L49)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I mock it in the test
</blockquote></details>

Why do you need to mock the specific behaviour now? You don't have anything yet that holds a specific behaviour
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmk49850rrGfIC-6PZz:-Nmk49850rrGfIC-6P_-:b-tosdaz) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2c4a5e7eca51a2ccdf0823a68d6e66a16d15ff8/crates/papyrus_network/src/block_headers/behaviour.rs#L47)):*
> ```XML
> #[derive(thiserror::Error, Debug)]
> #[error(transparent)]
> pub(crate) struct SessionIdNotFoundError(
> ```

Simply import it from streamed_data instead
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-Nmk40JK2rNl3P9OUEYM:-Nmk40JK2rNl3P9OUEYN:b-cn1msc) ([raw file](https://github.com/starkware-libs/papyrus/blob/d2c4a5e7eca51a2ccdf0823a68d6e66a16d15ff8/crates/papyrus_network/src/block_headers/behaviour.rs#L79)):*
> ```XML
>     pub fn send_query(&mut self, query: protobuf::BlockHeadersRequest, peer_id: PeerId) {
>         // TODO: keep track of the query id and the session id so that we can map between them for reputation.
>         let _outbound_session_id = self.streamed_data_behaviour.send_query(query, peer_id);
> ```

IIRC send_query can return an error. propagate it


<!-- Sent from Reviewable.io -->

2024-01-15 14:19 UTC, ShahakShama requested changes
> Reviewed 1 of 5 files at r5, 10 of 12 files at r6, 5 of 7 files at r13, 1 of 2 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 21 of 22 files reviewed, 19 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_network/Cargo.toml` line 13 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCFDeK9CpkYpTP1G9g:-NoCFDeK9CpkYpTP1G9h:bvag2pn) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/Cargo.toml#L13)):*
> ```TOML
> derive_more.workspace = true
> futures.workspace = true
> libp2p = { workspace = true, features = ["identify", "noise", "tcp", "tokio", "yamux"] }
> ```

Remove this change
___
*[`crates/papyrus_network/Cargo.toml` line 19 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCG3tdBHsMAHN6VV4Q:-NoCG1_7BvcyroO0_y7R:b1li6fz) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/Cargo.toml#L19)):*
> ```TOML
> starknet_api.workspace = true
> thiserror.workspace = true
> tokio = { workspace = true, features = ["full", "sync"] }
> ```

This as well
___
*[`crates/papyrus_network/src/db_executor.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaXnqj1QiCwjMYhGhh:-NoCGCVaEL00nr1cH3qf:b-ws0cv5) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/db_executor.rs#L23)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I prefer not to do this at the moment.. not sure what I'm going to do with this yet so I'm trying not to spread it around the codebase
</blockquote></details>

Consider again to move it now that you know what you're doing with this. You can also just put a TODO and fix it after merging if you don't want to delay the merge
___
*[`crates/papyrus_network/src/db_executor.rs` line 15 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCGSKf9Zs0wKWwghel:-NoCGSKf9Zs0wKWwghem:b-ek9clz) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/db_executor.rs#L15)):*
> ```XML
> pub struct QueryId(pub usize);
> 
> pub enum Data {
> ```

Add TODO to consider getting rid of Fin here and returning Option<Data> (And later on Option<Result<Data>>/Result<Option<Data>>)
___
*[`crates/papyrus_network/src/db_executor.rs` line 32 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCH5JOBzW14CdK0pw0:-NoCH5JPEucWTBmogA2O:b-n6m20j) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/db_executor.rs#L32)):*
> ```XML
> 
> impl DummyDBExecutor {
>     #[allow(dead_code)]
> ```

Add TODO to remove allow(dead_code)
___
*[`crates/papyrus_network/src/bin/node.rs` line 1 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCHn9cA-jPhdY_6qQC:-NoCHn9cA-jPhdY_6qQD:by97t53) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/bin/node.rs#L1)):*
> ```XML
> // Run the following two commands in different terminals:
> ```

Remove this file
___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmfkZbvEKOGyE4VUZOv:-NoCOLPKDSBC5Xb51dGN:b-y1f6dg) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/block_headers/mod.rs#L27)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Moved the comment from before: Not sure this is an error.
Also, if it is, you need to supply the fin message you've got
</blockquote></details>

Continuing this, please add a TODO to consider removing this from the errors
___
*[`crates/papyrus_network/src/block_headers/mod.rs` line 32 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCOT1R5C7ALS0_4NYR:-NoCOT1R5C7ALS0_4NYS:btdsu4) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/block_headers/mod.rs#L32)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) enum Event {
>     NewInboundQuery { query: BlockQuery, inbound_session_id: streamed_data::InboundSessionId },
> ```

Consider renaming to NewInboundSession (or adding a TODO to rename)
___
*[`crates/papyrus_network/src/messages/mod.rs` line 94 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCSMNP6AJWp9PFNaHv:-NoCSMNP6AJWp9PFNaHw:b8kivnj) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/messages/mod.rs#L94)):*
> ```XML
> }
> 
> impl From<starknet_api::block::BlockHeader> for protobuf::BlockHeader {
> ```

Can you move this to the block_headers module? It's under the same crate so it should work
Also, erase either this or the BlockHeader struct you defined there
___
*[`crates/papyrus_network/src/messages/mod.rs` line 114 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCSciC2fw5uSNvcVbZ:-NoCSciC2fw5uSNvcVb_:bb73xfv) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/messages/mod.rs#L114)):*
> ```XML
> }
> 
> impl From<starknet_api::block::BlockSignature> for protobuf::ConsensusSignature {
> ```

Same
___
*[`crates/papyrus_network/src/messages/mod.rs` line 130 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCSftb2fWe1dJiZW_O:-NoCSftb2fWe1dJiZW_P:bb2eb7v) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/messages/mod.rs#L130)):*
> ```XML
> }
> 
> impl TryFrom<protobuf::Felt252> for starknet_api::hash::StarkFelt {
> ```

These can stay here as they're common to all protocols
___
*[`crates/papyrus_network/src/streamed_data/handler_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmftOUk1gX4FG8uzPKO:-NoCUWj0-IGt3-FgDS8r:b-5edyji) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/streamed_data/handler_test.rs#L338)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Let's try tomorrow f2f to get rid of this
</blockquote></details>

let's do it
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 24 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCHxca6g5uqwvRi9uZ:-NoCHxca6g5uqwvRi9u_:b3wuc7i) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/block_headers/behaviour.rs#L24)):*
> ```XML
> #[cfg(test)]
> #[path = "behaviour_test.rs"]
> mod behaviour_test;
> ```

Add whitespace (If you disagree then just resolve this without fixing)
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 51 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCIRA7-sppM2g0QhEv:-NoCIRA7-sppM2g0QhEw:b-y636ql) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/block_headers/behaviour.rs#L51)):*
> ```XML
> impl Behaviour {
>     #[allow(dead_code)]
>     pub fn new(config: Config) -> Self {
> ```

Consider importing Config as StreamedDataConfig and renaming the variable to streamed_data_config
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 109 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCJzFl3ucwhm0kFvBX:-NoCJzFl3ucwhm0kFvBY:bbz6xxw) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/block_headers/behaviour.rs#L109)):*
> ```XML
>                     inboun [...]

2024-01-15 14:20 UTC, ShahakShama reviewed
> Reviewed 1 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: all files reviewed, 19 unresolved discussions (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2024-01-15 15:22 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: all files reviewed, 10 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/Cargo.toml` line 13 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCFDeK9CpkYpTP1G9g:-NoCZDJm4Ck7IeuMugrp:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/Cargo.toml#L13)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this change
</blockquote></details>

Done.
___
*[`crates/papyrus_network/Cargo.toml` line 19 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCG3tdBHsMAHN6VV4Q:-NoCZE0kEe2Jm-s1I1XP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/Cargo.toml#L19)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

This as well
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/bin/node.rs` line 1 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCHn9cA-jPhdY_6qQC:-NoCaCN9-8MuX4bOdUcP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/bin/node.rs#L1)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Remove this file
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/block_headers/behaviour.rs` line 51 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCIRA7-sppM2g0QhEv:-NoCaZbr1Sfs924UBm46:bhnwk7e) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/block_headers/behaviour.rs#L51)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider importing Config as StreamedDataConfig and renaming the variable to streamed_data_config
</blockquote></details>

added a todo


<!-- Sent from Reviewable.io -->

2024-01-16 08:50 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553)* status: 14 of 22 files reviewed, 8 unresolved discussions (waiting on @ShahakShama)

___
*[`crates/papyrus_network/src/db_executor.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmaXnqj1QiCwjMYhGhh:-NoGMKnG-uRcaRh75qHw:b-dyznr8) ([raw file](https://github.com/starkware-libs/papyrus/blob/1018f014a5cbddf0d6822bc1e8846b63ebfde2b0/crates/papyrus_network/src/db_executor.rs#L23)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Consider again to move it now that you know what you're doing with this. You can also just put a TODO and fix it after merging if you don't want to delay the merge
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/papyrus/1609
___
*[`crates/papyrus_network/src/messages/mod.rs` line 94 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCSMNP6AJWp9PFNaHv:-NoGRvuS8WwKguGkr4Ct:b-dyznqm) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/messages/mod.rs#L94)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Can you move this to the block_headers module? It's under the same crate so it should work
Also, erase either this or the BlockHeader struct you defined there
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/papyrus/1610
___
*[`crates/papyrus_network/src/messages/mod.rs` line 114 at r16](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NoCSciC2fw5uSNvcVbZ:-NoGRxRJBtGylmsrNWbx:b-dyznqm) ([raw file](https://github.com/starkware-libs/papyrus/blob/83accd2acb24b0d7d0bbc29ca770ec70e4794770/crates/papyrus_network/src/messages/mod.rs#L114)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/papyrus/1610
___
*[`crates/papyrus_network/src/streamed_data/handler_test.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-NmftOUk1gX4FG8uzPKO:-NoGSe1yCtOvoF6-Y2rF:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/75af95f7a2af67a13defdac1d25c9d2c0b6b5fc5/crates/papyrus_network/src/streamed_data/handler_test.rs#L338)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

let's do it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-16 09:31 UTC, ShahakShama submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-:-NoGb41v-lhU2L-Kaqa-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2024-01-16 12:10 UTC, ShahakShama approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1553#-:-NoHAaR6E9ZJmNPfYEvH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2024-01-16 14:27 UTC, merged