feat(sync): add p2p header sync
starkware-libs/papyrus pull request #1722
Opened 2024-02-20 11:21 UTC by ShahakShama

2024-02-20 15:51 UTC, yair-starkware requested changes
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: 4 of 6 files reviewed, 18 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr69rji849nDwJ_PZe2:-Nr69rji849nDwJ_PZe3:bcvr65d) (no related file):*
No reverts in P2P?

___
___
*[`crates/papyrus_network/src/lib.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr69zkz0V_4mgbPTusU:-Nr69zkz0V_4mgbPTusV:b-rtagwg) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_network/src/lib.rs#L81)):*
> ```XML
> }
> 
> #[allow(unused)]
> ```

delete



_Code quote:_
```XML
#[allow(unused)]
```
___
*[`crates/papyrus_network/src/lib.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6A0yfBKu6Sd1cJbC4:-Nr6A0yfBKu6Sd1cJbC5:b-rtagwg) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_network/src/lib.rs#L86)):*
> ```XML
> }
> 
> #[allow(unused)]
> ```

delete



_Code quote:_
```XML
#[allow(unused)]
```
___
*[`crates/papyrus_p2p_sync/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6CEX7C6qrCkxbErDE:-Nr6CEX89-sj1ASPWY2w:batg447) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/Cargo.toml#L10)):*
> ```TOML
> [dependencies]
> futures.workspace = true
> papyrus_config = { path = "../papyrus_config" }
> ```

add crate version



_Code quote:_
```TOML
 "../papyrus_config"
```
___
*[`crates/papyrus_p2p_sync/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6CVX14xs1JqNoaNBE:-Nr6CVX14xs1JqNoaNBF:bb7od0r) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/Cargo.toml#L12)):*
> ```TOML
> papyrus_config = { path = "../papyrus_config" }
> papyrus_network = { path = "../papyrus_network" }
> papyrus_storage = { path = "../papyrus_storage" }
> ```

same



_Code quote:_
```TOML
"../papyrus_storage"
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr60giV3UcUNw2lvUGo:-Nr60giV3UcUNw2lvUGp:b-3efnoo) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L33)):*
> ```XML
>                 "header_query_size",
>                 &self.header_query_size,
>                 "The size of each header query.",
> ```

The maximum amount of headers to ask from peers



_Code quote:_
```XML
"The size of each header query."
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr61OKb-sVdVw9ppstD:-Nr61OKb-sVdVw9ppstE:b-mwu9at) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L65)):*
> ```XML
>     )]
>     WrongSignaturesLength { signatures_len: usize },
>     #[error("Network has closed its channel for sending responses.")]
> ```

Consider:
response_receivers closed the channel

It will be the same error variant for all the protocols? Maybe mention that it's the headers channel



_Code quote:_
```XML
Network has closed its channel for sending responses."
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5oHeh1h-8qkzdywaO:-Nr5oHeh1h-8qkzdywaP:bxle7im) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L92)):*
> ```XML
> 
>     pub async fn run(mut self) -> Result<(), P2PSyncError> {
>         let mut current_block_number = self.storage_reader.begin_ro_txn()?.get_header_marker()?;
> ```

Consider extracting the header specific logic to a separate module
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5xbGe0oHhHFeue_Y4:-Nr5xbGe0oHhHFeue_Y5:bcsv00j) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L93)):*
> ```XML
>     pub async fn run(mut self) -> Result<(), P2PSyncError> {
>         let mut current_block_number = self.storage_reader.begin_ro_txn()?.get_header_marker()?;
>         loop {
> ```

Consider breaking the nested loop to functions
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5oorM658Clc2TdK_R:-Nr5oorM658Clc2TdK_S:bjedszy) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L99)):*
> ```XML
>                     direction: Direction::Forward,
>                     limit: self.config.header_query_size,
>                     step: 1,
> ```

Use const / config



_Code quote:_
```XML
step: 1,
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6-qjOA_-JwUXPlvIJ:-Nr6-qjOA_-JwUXPlvIK:b-rfw8dk) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L107)):*
> ```XML
>                     .expect("Failed converting usize to u64");
>             while current_block_number.0 < end_block_number {
>                 let Ok(maybe_signed_header) = timeout(
> ```

1. Add comment explaining why it's in timeout
2. Add todo to sleep at the end of each `while` iteration once we delete the timeout (so we won't take all the CPU when done syncing)



_Code quote:_
```XML
timeout
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pPoN2TEAcdh2h7Mr:-Nr5pPoN2TEAcdh2h7Ms:b-cnn5v9) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L111)):*
> ```XML
>                     self.response_receivers.signed_headers_receiver.next(),
>                 )
>                 .await
> ```

Consider implementing as a method of ResponseReceivers



_Code quote:_
```XML
                let Ok(maybe_signed_header) = timeout(
                    self.config.query_timeout,
                    self.response_receivers.signed_headers_receiver.next(),
                )
                .await
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pjlF3tU_9nkaGEdw:-Nr5pjlF3tU_9nkaGEdx:b-qn43tt) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L113)):*
> ```XML
>                 .await
>                 else {
>                     break;
> ```

log the error, check if recoverable



_Code quote:_
```XML
break;
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5ya3105rGu-y9HOxo:-Nr5ya3105rGu-y9HOxp:b-eilgcb) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L125)):*
> ```XML
>                     });
>                 }
>                 if signatures.len() != 1 {
> ```

Use const



_Code quote:_
```XML
1
```
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5yiSN-W9VeJDasgIp:-Nr5yiSN-W9VeJDasgIq:b-di940i) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L127)):*
> ```XML
>                 if signatures.len() != 1 {
>                     return Err(P2PSyncError::WrongSignaturesLength {
>                        [...]

2024-02-21 06:24 UTC, nagmo-starkware requested changes
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: 5 of 6 files reviewed, 24 unresolved discussions (waiting on @ShahakShama and @yair-starkware)

___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9Hk6eA00idpToyDQs:-Nr9Hk6eA00idpToyDQt:bms75mx) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L20)):*
> ```XML
> 
> #[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq)]
> pub struct SyncConfig {
> ```

consider P2pSyncConfig
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9IBau9Y49tVwie9cn:-Nr9IBau9Y49tVwie9co:b-cb9sic) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L32)):*
> ```XML
>             ser_param(
>                 "header_query_size",
>                 &self.header_query_size,
> ```

maybe "header_query_delta"? or something else but I don't like this name. I thought it meant the actual size (in bytes) of the query.  which made  me ponder why does this belong here
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9GofT6FaXUfLa--y0:-Nr9GofT6FaXUfLa--y1:b-j4mko6) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L40)):*
> ```XML
>                 &self.query_timeout.as_secs(),
>                 "Time in seconds to wait for query responses until we restart the query from the \
>                  last received block.",
> ```

I think the wording is too specific. I'd say "Time in seconds to wait for query responses until we mark it as failed"
what we do with the fact that is failed is not a part of the config. what if you change the error handling? can you assure that someone will go here to update this string?
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9IsBvBalhcKANFLN2:-Nr9IsBvBalhcKANFLN3:b-smnuvh) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L104)):*
> ```XML
>                 .await?;
>             let end_block_number = current_block_number.0
>                 + u64::try_from(self.config.header_query_size)
> ```

please move this conversion to the beginning of the function. if there is a bug in the config we want to catch it early
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9JvyK1p6PVUU6QkoI:-Nr9JvyK1p6PVUU6QkoJ:b-aqjn9h) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L120)):*
> ```XML
>                 };
>                 if current_block_number != block_header.block_number {
>                     return Err(P2PSyncError::HeadersUnordered {
> ```

I dont think the sync should fail on this. but I'm ok with doing it later. please add a todo
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9KGbhCPjbrUtsKG9Z:-Nr9KGbhCPjbrUtsKG9_:b-64i6f0) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L126)):*
> ```XML
>                 }
>                 if signatures.len() != 1 {
>                     return Err(P2PSyncError::WrongSignaturesLength {
> ```

same here. sync shouldn't fail


<!-- Sent from Reviewable.io -->

2024-02-21 07:24 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: 5 of 6 files reviewed, 19 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr69rji849nDwJ_PZe2:-Nr9SYoO77_JxsQ96blu:b3kre) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

No reverts in P2P?
</blockquote></details>

?

___
___
*[`crates/papyrus_network/src/lib.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr69zkz0V_4mgbPTusU:-Nr9XkUv6Q9PP1ac3-k_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_network/src/lib.rs#L81)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/lib.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6A0yfBKu6Sd1cJbC4:-Nr9XkidEdu6ZGwdjJVk:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_network/src/lib.rs#L86)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/Cargo.toml` line 10 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6CEX7C6qrCkxbErDE:-Nr9SvSL59aYJCrDwu_U:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/Cargo.toml#L10)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

add crate version
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/Cargo.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6CVX14xs1JqNoaNBE:-Nr9Svow5HAuI2W-olJ9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/Cargo.toml#L12)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr60giV3UcUNw2lvUGo:-Nr9TBgs4_VV2J9V-qjI:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L33)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The maximum amount of headers to ask from peers
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 65 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr61OKb-sVdVw9ppstD:-Nr9T_mm-s98OFBej8O0:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L65)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider:
response_receivers closed the channel

It will be the same error variant for all the protocols? Maybe mention that it's the headers channel
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5oHeh1h-8qkzdywaO:-Nr9TuZg6F1QeRJIX79b:b-f8r5tv) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L92)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider extracting the header specific logic to a separate module
</blockquote></details>

When we'll have more than 1 data type
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5xbGe0oHhHFeue_Y4:-Nr9Trnr0S2v4yWVCbuY:b-u9u0gj) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L93)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider breaking the nested loop to functions
</blockquote></details>

When it gets more complicated
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5oorM658Clc2TdK_R:-Nr9Tqfm7NO5Cg2-u0IJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L99)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use const / config
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 107 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6-qjOA_-JwUXPlvIJ:-Nr9ULH9EEt9F-uBX8r-:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L107)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

1. Add comment explaining why it's in timeout
2. Add todo to sleep at the end of each `while` iteration once we delete the timeout (so we won't take all the CPU when done syncing)
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pPoN2TEAcdh2h7Mr:-Nr9V7r27jzPwJg4uBXA:b-o5x6rs) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L111)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider implementing as a method of ResponseReceivers
</blockquote></details>

IMO this is a sync detail and ResponseReceivers is in the network crate. I can add an impl block for ResponseReceivers in the sync crate but I tend to think this is confusing
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pjlF3tU_9nkaGEdw:-Nr9VQTJ-A7PSozU8zK7:b-n017x1) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L113)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

log the error, check if recoverable
</blockquote></details>

The break here is for the inner loop. Added a comment to explain this
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5ya3105rGu-y9HOxo:-Nr9WuXQ0CoGxSnV9ETa:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L125)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use const
</blockquote></details>

Done.
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5yiSN-W9VeJDasgIp:-Nr9Wdwo922DvWlHJ_4V:b-x9p7sf) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L127)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Consider returning the signatures to help debugging
</blockquote></details>

I don't see how it will be useful
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9IBau9Y49tVwie9cn:-Nr9T5DfBgPE2mK6VdOo:bj4fvy0) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L32)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

maybe "header_query_delta"? or something else but I don't like this name. I though [...]

2024-02-21 08:39 UTC, yair-starkware requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: all files reviewed, 8 unresolved discussions (waiting on @nagmo-starkware and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr69rji849nDwJ_PZe2:-Nr9lxs31T8hmOLlRKme:b-13ddk0) (no related file):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

?
</blockquote></details>

In the central sync we check the parent hash

___
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pPoN2TEAcdh2h7Mr:-Nr9mx733WqS8LxOEloB:b-4i2xkb) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L111)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

IMO this is a sync detail and ResponseReceivers is in the network crate. I can add an impl block for ResponseReceivers in the sync crate but I tend to think this is confusing
</blockquote></details>

So make it a method of the sync
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pjlF3tU_9nkaGEdw:-Nr9nKrICVPgmsHR8HvL:biasu1d) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L113)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I still agree that a debug log is a good idea
</blockquote></details>

And I think breaking the nested for to functions will make the flow easier to follow
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5yiSN-W9VeJDasgIp:-Nr9ncb24To0EcyelMHC:b-fb4eej) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L127)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't see how it will be useful
</blockquote></details>

You will be search what these extra signatures are
___
*[`crates/papyrus_p2p_sync/src/p2p_sync_test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr65lF7-H50vBd0GHa2:-Nr9o1u3EueM8tsz6_xS:b-sqyeom) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/p2p_sync_test.rs#L36)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

I don't see a reason. Having the send channel is much more comfortable than having a mock
</blockquote></details>

But you also expect requests, the mock API gives you this functionality
___
*[`crates/papyrus_p2p_sync/src/p2p_sync_test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6BGRi9XIVThYjbRm-:-Nr9oJW76rLSE43sheE-:b-jgf6z6) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/p2p_sync_test.rs#L152)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

In the src code, yes. But in the tests I've set it to 10ms
</blockquote></details>

Use const and make it a factor of the sync timout


<!-- Sent from Reviewable.io -->

2024-02-21 11:31 UTC, ShahakShama reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: all files reviewed, 8 unresolved discussions (waiting on @nagmo-starkware and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr69rji849nDwJ_PZe2:-Nr9yzTC1T4q9YkAZaaZ:b-kstumx) (no related file):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In the central sync we check the parent hash
</blockquote></details>

Oh. Future PR. Added TODO

___
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pPoN2TEAcdh2h7Mr:-NrA-7Rk9lg_mRattdGm:biac9bg) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L111)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

So make it a method of the sync
</blockquote></details>

The timeout is going to be erased within a week. I prefer not investing time on this
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5pjlF3tU_9nkaGEdw:-NrAOCO812tl7yOV1BmX:b5gf7pt) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L113)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

And I think breaking the nested for to functions will make the flow easier to follow
</blockquote></details>

Done. (to you both)
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr5yiSN-W9VeJDasgIp:-NrA-i_w0be_GmdVwjqu:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/lib.rs#L127)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

You will be search what these extra signatures are
</blockquote></details>

Done
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9IBau9Y49tVwie9cn:-NrAQf931gi0g-f6eQzO:bb6un1j) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L32)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

better.. still not great :) 
if you want to follow the description it could be "amount_of_header_per_query" and then it's perfect
</blockquote></details>

Done
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9IsBvBalhcKANFLN2:-NrAQgpp6cByi0a3420J:b-trqvdc) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L104)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

oh right I thought it's a string for some reason. so why not put it as u64 in the config and not convert?
</blockquote></details>

In the network, Query::limit is usize
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9KGbhCPjbrUtsKG9Z:-NrA-Ww06qkgqm62spCX:bxp6qws) ([raw file](https://github.com/starkware-libs/papyrus/blob/94f0285c03f9d3634db51287a08484b5a274b47f/crates/papyrus_p2p_sync/src/lib.rs#L126)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it just  means that the selected peer is bad not that the sync should stop. we can re-query another peer
</blockquote></details>

Right now we have just 1 peer. What you're saying means that we should move this error to the network. Added TODO on the error itself
___
*[`crates/papyrus_p2p_sync/src/lib.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr9dUHF9Gh3yzpXk77i:-Nr9zktWBzxgWSFTXQNC:b-v8woxn) ([raw file](https://github.com/starkware-libs/papyrus/blob/89a7ccb11cb6ab15c965ee95c1b256cd16ad4e51/crates/papyrus_p2p_sync/src/lib.rs#L57)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

is this the todo? it's no good enough. 
1. should be also on headers unordered
2. should state not only to remove the error but also find a better way to handle this kind of error without shutting down
</blockquote></details>

It's already on headers unordered
___
*[`crates/papyrus_p2p_sync/src/p2p_sync_test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr65lF7-H50vBd0GHa2:-NrAKGuS1A84LgrRoMIW:b-a0xksa) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/p2p_sync_test.rs#L36)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

But you also expect requests, the mock API gives you this functionality
</blockquote></details>

I have a channel for requests too, and it's very comfortable using it
___
*[`crates/papyrus_p2p_sync/src/p2p_sync_test.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-Nr6BGRi9XIVThYjbRm-:-NrALCSeAhra2ZbBXf0y:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/8c67b538165b894f3addd32296ec8105e9ff6327/crates/papyrus_p2p_sync/src/p2p_sync_test.rs#L152)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

Use const and make it a factor of the sync timout
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-21 11:40 UTC, yair-starkware approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2024-02-21 11:42 UTC, yair-starkware approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722)* status: all files reviewed, 4 unresolved discussions (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2024-02-21 15:03 UTC, nagmo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1722#-:-NrBBKSD0VxQACZLLLrp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-02-22 04:49 UTC, merged