fix(network_manager): swarm receives query before established connection
starkware-libs/papyrus pull request #1834
Opened 2024-03-25 08:06 UTC by eitanm-starkware

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-03-25 09:08 UTC, nagmo-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1834)* status: all files reviewed, 19 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntokiws4kKfzHbJODoN:-Ntokiwt9IbqQ-jAgQGf:bq2owpf) (no related file):*
this PR has conflicts with main please rebase and fix

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtogZ1V6Td5untW8ysi):*
the commit message doesn't follow the commitlint configuration.
please install it locally as explained [here](https://starkwareindustries.slack.com/archives/C03CPEWBCUF/p1690450264415649)
you can see the config in the `commitlint.config.js` file in the repo
a commit message that doesn't follow the commitlint config would fail the PR merging phase
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntokw5oCh3eT0hV85aN:-Ntokw5oCh3eT0hV85aO:bjon7xe) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L99)):*
> ```XML
>         match event {
>             SwarmEvent::ConnectionEstablished { peer_id, .. } => {
>                 debug!("Connected to a peer!");
> ```

improve the debug message using the peer id info
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtolONFA_TZTrHIixD7:-NtolONG2LPRitTniIdM:big0wmx) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L248)):*
> ```XML
>     fn handle_sync_subscriber_query(&mut self, query: Query) {
>         let mut query_bytes = vec![];
>         let data_type = query.data_type;
> ```

this is stuck in the middle of the query_bytes binding and initialization. move this line up/down
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntol_-I11Xsl5aP1fjE:-Ntol_-I11Xsl5aP1fjF:bffeij1) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L249)):*
> ```XML
>         let mut query_bytes = vec![];
>         let data_type = query.data_type;
>         query.encode(&mut query_bytes).expect("failed to encode query");
> ```

this code does not need to run if the condition bellow fails so move it into the positive branch
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtolzJ91Vc-LEWeIcQk:-NtolzJ91Vc-LEWeIcQl:b-nil9o8) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L261)):*
> ```XML
>                 }
>                 Err(e) => {
>                     error!("Failed to send query to peer. Peer not connected error: {e:?}");
> ```

this is questionable if we still need this message. if you think we do it shouldn't be and error printout maybe info/debug and the phrasing can be improved given the new error handling you introduced
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 270 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntom_6w86WjbXAPKBtZ:-Ntom_6w86WjbXAPKBt_:b-tpup4n) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L270)):*
> ```XML
>     }
> 
>     fn handle_sync_subscriber_query_with_no_peer(&mut self, data_type: DataType) {
> ```

you're not handling the query, it's better to name the function with what it does



_Suggestion:_
```XML
return_fin_to_subscriber
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntomz150EtlsF_s1aPt:-Ntomz150EtlsF_s1aPu:b-qkzwlh) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L272)):*
> ```XML
>     fn handle_sync_subscriber_query_with_no_peer(&mut self, data_type: DataType) {
>         let mut data_bytes = vec![];
>         let protocol = match data_type {
> ```

again. try to not put stuff between variable binding and initialization.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtooAmU1HhbDcSNj-HN:-NtooAmU1HhbDcSNj-HO:bf90xv5) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L276)):*
> ```XML
>             DataType::StateDiff => Protocol::StateDiff,
>         };
>         Data::Fin(data_type).encode(&mut data_bytes).expect("failed to encode data");
> ```

consider improving the error message following rust guidelines: https://doc.rust-lang.org/std/error/index.html#common-message-styles



_Suggestion:_
```XML
failed to encode Data::Fin for data_type: {} ...
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntooc0MA3q4GiI28ERF:-Ntooc0MA3q4GiI28ERG:b-2guby3) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L278)):*
> ```XML
>         Data::Fin(data_type).encode(&mut data_bytes).expect("failed to encode data");
>         let (_, response_senders) =
>             self.sync_subscriber_channels.as_mut().expect("sync subscriber channels not found");
> ```

same here



_Code quote:_
```XML
sync subscriber channels not found
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtooyNK7ONVtQhAwYq0:-NtooyNLB9M7okDnzsiY:b-s490oo) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L279)):*
> ```XML
>         let (_, response_senders) =
>             self.sync_subscriber_channels.as_mut().expect("sync subscriber channels not found");
>         response_senders
> ```

a matter of style but this line and the previous one could be merged into a one liner without binding the `response_senders`.
try this and decide if you think it looks better or not. up to you.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtopOc5AkUGT5QrF7Ti:-NtopOc5AkUGT5QrF7Tj:b-y0007b) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed9c7ad0559cd5f7368b81748f63d4d20975dfc1/crates/papyrus_network/src/network_manager/test.rs#L191)):*
> ```XML
> #[tokio::test]
> async fn register_subscriber_and_use_channels() {
>     // create mocked network manager
> ```

why did you loose the comment? in tests it's useful to comment on sections explaining what you do since test are often considered a part of the documentation.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtopsH94vtrmMkCwPuD:-NtopsH94vtrmMkCwPuE:bxbwv17) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/test.rs#L203)):*
> ```XML
>         Some(PeerAddressConfig { peer_id: mock_peer_id, ..Default::default() }),
>     );
>     // create mock swarm event for connection established
> ```

should this be at the beginning?
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntoq4ZNCRzqdx91xvOs:-Ntoq4ZNCRzqd [...]

2024-03-28 11:30 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1834)* status: 0 of 4 files reviewed, 19 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntokiws4kKfzHbJODoN:-Ntppdca3c6HlJWgpd6o:b-896fix) (no related file):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

this PR has conflicts with main please rebase and fix
</blockquote></details>

Done.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtogZ1V6Td5untW8ysi):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

the commit message doesn't follow the commitlint configuration.
please install it locally as explained [here](https://starkwareindustries.slack.com/archives/C03CPEWBCUF/p1690450264415649)
you can see the config in the `commitlint.config.js` file in the repo
a commit message that doesn't follow the commitlint config would fail the PR merging phase
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntokw5oCh3eT0hV85aN:-NtpnE8FEt43-KaLssAR:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L99)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

improve the debug message using the peer id info
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtolONFA_TZTrHIixD7:-NtpnEYK8Rf8zz9aFFIe:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L248)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

this is stuck in the middle of the query_bytes binding and initialization. move this line up/down
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntol_-I11Xsl5aP1fjE:-NtpnfJl2sMEobYE53r9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L249)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

this code does not need to run if the condition bellow fails so move it into the positive branch
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 261 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtolzJ91Vc-LEWeIcQk:-NtppVgwBg-PbXMec3Cv:b-3ice27) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L261)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

this is questionable if we still need this message. if you think we do it shouldn't be and error printout maybe info/debug and the phrasing can be improved given the new error handling you introduced
</blockquote></details>

I think it gives good info, added how we are dealing with the situation
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 270 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntom_6w86WjbXAPKBtZ:-NtppUL_8b2CCqjT9auZ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L270)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

you're not handling the query, it's better to name the function with what it does
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntomz150EtlsF_s1aPt:-NtppTzmDxipy1Q9dsu_:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L272)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

again. try to not put stuff between variable binding and initialization.
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtooAmU1HhbDcSNj-HN:-NtpsPw41zwM45yAGI7R:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L276)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

consider improving the error message following rust guidelines: https://doc.rust-lang.org/std/error/index.html#common-message-styles
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntooc0MA3q4GiI28ERF:-NtpsPdj0zgX-4lsac3h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L278)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtooyNK7ONVtQhAwYq0:-NtpsbuUBF02GwqUOWQk:b-x9swai) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L279)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

a matter of style but this line and the previous one could be merged into a one liner without binding the `response_senders`.
try this and decide if you think it looks better or not. up to you.
</blockquote></details>

looks like dark magic imo
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtopOc5AkUGT5QrF7Ti:-NtpvrU9A7lpLIeT7fwl:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ed9c7ad0559cd5f7368b81748f63d4d20975dfc1/crates/papyrus_network/src/network_manager/test.rs#L191)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why did you loose the comment? in tests it's useful to comment on sections explaining what you do since test are often considered a part of the documentation.
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 203 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtopsH94vtrmMkCwPuD:-NtpvtBlCVB9ZVSPQaTO:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/test.rs#L203)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

should this be at the beginning?
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntoq4ZNCRzqdx91xvOs:-Nu3okEh5EkwkjLkS39h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/test.rs#L220)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

why do you need to spawn a new tokio task and why do you need to sleep?
also you don't join on this task so how can you know that it finished?
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 310 at r1]( [...]

2024-03-28 16:16 UTC, nagmo-starkware requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1834)* status: all files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @eitanm-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtogZ1V6Td5untW8ysi):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

refactor is wrong here. you're fixing a bug so it should be fix.
refactor implies no functional change was made
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu41knP6Q1PLFPQZbyU:-Nu41knQ4QFe7-a869HT:b-82ar4i) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/db_executor/mod.rs#L99)):*
> ```XML
>         }
>     }
>     pub fn encode<B>(self, buf: &mut B) -> Result<(), DataEncodingError>
> ```

I'm ok with the decision to have another function and not add a parameter to the existing one for that but there's lots of code duplication here. 
please extract common code into helper functions.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu424vA1kCRYuJmXUw4:-Nu424vBCNXmcBsw4gsL:bml4jby) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/db_executor/mod.rs#L99)):*
> ```XML
>         }
>     }
>     pub fn encode<B>(self, buf: &mut B) -> Result<(), DataEncodingError>
> ```

so users will know what's the difference



_Suggestion:_
```XML
encode_without_length_prefix
```
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtooAmU1HhbDcSNj-HN:-Nu42Uzb7QW_sIkmVD5x:beodn0x) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L276)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

it's not unknown data_type.. look at the code of `encode` to see what can cause the function to fail.
also as descibed in the link above this is a case where it can only fail by a bug so the message should target developers.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntooc0MA3q4GiI28ERF:-Nu43326BO9Tw2W6l6Ki:bmyqdc6) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L278)):*
<details><summary><i>Previously, eitanm-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same. but here this can really never fail since you'll get to this function through [here](https://github.com/starkware-libs/papyrus/blob/f1e9d4f9b69109b7e02a23c71624e54d9709613f/crates/papyrus_network/src/network_manager/mod.rs#L58).
a good message could be: `can't handle subscriber query before registering a subscriber`
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu44b9SAPQGqvz1MauB:-Nu44b9SAPQGqvz1MauC:b354p86) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/network_manager/mod.rs#L285)):*
> ```XML
>             .expect("Encountered unknown protocol while sending fin");
>     }
>     pub fn is_connected(&self) -> bool {
> ```

what's this?
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu4pu1ICpFgniWaa8Oa:-Nu4pu1ICpFgniWaa8Ob:b8edij5) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/network_manager/test.rs#L362)):*
> ```XML
> }
> #[tokio::test]
> async fn sync_subscriber_query_no_peer_connected() {
> ```

sync subscriber doesn't send any query in this test. the name should say something about the function being tested.



_Suggestion:_
```XML
return_fin_to_subscriber_results_in_none_for_subscribers_receiver
```


<!-- Sent from Reviewable.io -->

2024-04-01 09:52 UTC, eitanm-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1834)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtogZ1V6Td5untW8ysi):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

refactor is wrong here. you're fixing a bug so it should be fix.
refactor implies no functional change was made
</blockquote></details>

got it
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu424vA1kCRYuJmXUw4:-NuJjUf81KcnbRCmXXW8:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/db_executor/mod.rs#L99)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

so users will know what's the difference
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/db_executor/mod.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu41knP6Q1PLFPQZbyU:-NuNtiTyASjbp0d7x_oc:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/db_executor/mod.rs#L99)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I'm ok with the decision to have another function and not add a parameter to the existing one for that but there's lots of code duplication here. 
please extract common code into helper functions.
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-NtooAmU1HhbDcSNj-HN:-NuJireiAh2Aw-4EnBAz:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L276)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

it's not unknown data_type.. look at the code of `encode` to see what can cause the function to fail.
also as descibed in the link above this is a case where it can only fail by a bug so the message should target developers.
</blockquote></details>

Done.
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 278 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Ntooc0MA3q4GiI28ERF:-NuJi2AR9PAEwoM7Ukj8:b-hfghm4) ([raw file](https://github.com/starkware-libs/papyrus/blob/16d2277d895b7b15d82f9aa6f999c4e2989a9601/crates/papyrus_network/src/network_manager/mod.rs#L278)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

same. but here this can really never fail since you'll get to this function through [here](https://github.com/starkware-libs/papyrus/blob/f1e9d4f9b69109b7e02a23c71624e54d9709613f/crates/papyrus_network/src/network_manager/mod.rs#L58).
a good message could be: `can't handle subscriber query before registering a subscriber`
</blockquote></details>

Sounds good
___
*[`crates/papyrus_network/src/network_manager/mod.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu44b9SAPQGqvz1MauB:-NuJgN268f8FAA32Tr2A:b3ciwmb) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/network_manager/mod.rs#L285)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

removed - wasn't needed.
___
*[`crates/papyrus_network/src/network_manager/test.rs` line 362 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-Nu4pu1ICpFgniWaa8Oa:-NuJfzXjCe5jv0rzEyFK:b1ljmld) ([raw file](https://github.com/starkware-libs/papyrus/blob/ab295251f6b4c7104794ddff1d8ddce460885bbb/crates/papyrus_network/src/network_manager/test.rs#L362)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

sync subscriber doesn't send any query in this test. the name should say something about the function being tested.
</blockquote></details>

Done. I think adding the whole name is repetitive with the test - what is returned can be checked in the tokio select similar to the how we don't state it in other tests.


<!-- Sent from Reviewable.io -->

2024-04-01 13:00 UTC, nagmo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1834#-:-NuOjndaB_MigCO1Ts7c:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2024-04-01 13:20 UTC, merged