feat(consensus): define Context and ConsensusBlock traits
starkware-libs/papyrus pull request #1993
Opened 2024-05-15 08:37 UTC by matan-starkware

Context defines how consensus will interact with the rest of the node.

ConsensusBlock defines the interface that Consensus needs for holding onto a proposal once it is
built.

---

**Stack**:
- #1993 ⬅
- #1992

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2024-05-16 13:20 UTC, DvirYo-starkware requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 11 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0LS_EA7Yaz6tj02vj:-Ny0LS_EA7Yaz6tj02vk:bx84yqw) (no related file):*
1. All the documentation is public. Design descitions and explnation (and also todos) shouldn't be public (// instead of ///)
2. Add documentation links where you can. (like the [`Context`] example
3. From design point of view all this was agreed with Dan?

___
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0MLyd6zTrblaWo6bl:-Ny-vrOdEKh7_Hj3NQBO:b-neipn3) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L1)):*
> ```XML
> //! This file primarily contains the Context trait, which is the primary interface for the consensus
> ```

module



_Code quote:_
```XML
file
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0MluK9auVj1wqXSNX:-Ny0MluLEkFXbn2k807o:b4too2l) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L1)):*
> ```XML
> //! This file primarily contains the Context trait, which is the primary interface for the consensus
> ```

1. add a link to the Context trait. 
[`Context`]

2. I don't think the last line should be in the module documentation. I don't have strong opinion about this...



_Code quote:_
```XML
Context
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0LJ9T25FbDVV08zRs:-Ny0LJ9T25FbDVV08zRt:b-by0vwl) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L3)):*
> ```XML
> //! This file primarily contains the Context trait, which is the primary interface for the consensus
> //! module to access the rest of the node. It also contains the ConsensusBlock trait, which is used
> //! to keep the consensus module indifferent to the specific makeup of a block.
> ```

consider adding a new line between the module documentation and the imports.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0OWAY2RglfPbNKJwC:-Ny0OWAY2RglfPbNKJwD:b-9e38j1) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L6)):*
> ```XML
> use async_trait::async_trait;
> use tokio::sync::{mpsc, oneshot};
> ```

1. you wrote double to
2. consider removing the NodeId at the start of the sentence
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0RqC8Ach390lEQAEe:-Ny0RqC8Ach390lEQAEf:bnvqznd) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L34)):*
> ```XML
>     /// The proposal's round must not be included in the ID, as, beyond being a detail of
>     /// consensus, Tendermint must be able to progress a value across multiple rounds of a given
>     /// height. Including a proposal's height in ID is optional from the perspective of consensus.
> ```

add a new line here



_Code quote:_
```XML
eight. Includi
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0SR5lAe5kY8hFCE9w:-Ny0SR5lAe5kY8hFCE9x:br3hudp) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L48)):*
> ```XML
> ///
> /// Why `Send + Sync`?
> /// 1. We expect multiple components within consensus to concurrently access the context.
> ```

In the second bullet, is the object unsafe because using a clone requires the object to be Sized?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0XAV847_kGV7qHKIr:-Ny0XAV847_kGV7qHKIs:b-5opymb) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L66)):*
> ```XML
>     ///   state of the block.
>     ///
>     /// Returns:
> ```

I don't understand this.
1. If the block fails to be built, the sender of the mpsc will be dropped (or the one-shot?)
2. "Otherwise it will be dropped by consensus upon reaching a different decision." who is it here?
3. Do I understand correctly, and the last sentence describes how this function is going to be used in another place?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0YGTaCuzCRN66yOHY:-Ny0YGTb5VvphpS8QZ2-:beb2kzq) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L86)):*
> ```XML
>     /// - A receiver for the stream of the block's content.
>     ///
>     /// Returns:
> ```

also as above, I don't understand exactly your meaning here.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0U83A6NQLUzQC9kFO:-Ny0U83A6NQLUzQC9kFP:b-tzfnfh) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L98)):*
> ```XML
> 
>     /// Get the set of validators for a given height. These are the nodes that can propose and vote
>     /// on blocks.
> ```

Is there a special reason for returning a vector and not set?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0Lx9R2jdPT396py44:-Ny0Lx9R2jdPT396py45:bz2d6b5) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L104)):*
> ```XML
>     fn proposer(&self, validators: Vec<NodeId>, height: u64) -> NodeId;
> }
> ```

I assume this should fail if a trait isn't object-safe.
1. If I add non object-safe method this still compiles
2. It should be in a test module 


<!-- Sent from Reviewable.io -->

2024-05-19 11:53 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 11 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0LS_EA7Yaz6tj02vj:-NyFM-L0CRrh20pzba-c:b-sbv3sj) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. All the documentation is public. Design descitions and explnation (and also todos) shouldn't be public (// instead of ///)
2. Add documentation links where you can. (like the [`Context`] example
3. From design point of view all this was agreed with Dan?
</blockquote></details>

1. I changed most of it. Some I thought should remain public.
2. Added
3. Context yes (and with Ittay & Lior). ConsensusBlock not in detail.

___
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0MLyd6zTrblaWo6bl:-NyFX8I2-LLpz7301wHq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L1)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

module
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0MluK9auVj1wqXSNX:-NyFXDe99qVobURn4waI:b-r3fbnc) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L1)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. add a link to the Context trait. 
[`Context`]

2. I don't think the last line should be in the module documentation. I don't have strong opinion about this...
</blockquote></details>

I added links in the docs for the traits themselves. Is that ok?

And rewrote this.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0OWAY2RglfPbNKJwC:-NyFXa1H4BhX7weZ6KQ5:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L6)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. you wrote double to
2. consider removing the NodeId at the start of the sentence
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0RqC8Ach390lEQAEe:-NyFXeNp3OU2oJLJ6skP:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L34)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

add a new line here
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0SR5lAe5kY8hFCE9w:-NyFXmsK9dCurxTiuQ99:b-bdbp6b) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L48)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

In the second bullet, is the object unsafe because using a clone requires the object to be Sized?
</blockquote></details>

Yes, added that in parens.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0XAV847_kGV7qHKIr:-NyFXwApB5e_GRTmFQ2p:bt5t63z) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L66)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I don't understand this.
1. If the block fails to be built, the sender of the mpsc will be dropped (or the one-shot?)
2. "Otherwise it will be dropped by consensus upon reaching a different decision." who is it here?
3. Do I understand correctly, and the last sentence describes how this function is going to be used in another place?
</blockquote></details>

Good catch. Removed the last part.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0YGTaCuzCRN66yOHY:-NyFYAv9EYOKNDcv_GOL:bumg6b1) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L86)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

also as above, I don't understand exactly your meaning here.
</blockquote></details>

removed, for another milestone
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0U83A6NQLUzQC9kFO:-NyFYEAn4o3XoyiwxwKB:b-dpsjza) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L98)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Is there a special reason for returning a vector and not set?
</blockquote></details>

No. How do you feel about a BTreeSet?

In the future I believe we will switch to a BTreeMap anyways:
1. I expect more info to come (ie weights) for each address, so a map.
2. I think we may want a stable order for leader selection, so not hash map.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0Lx9R2jdPT396py44:-NyFYrKy386Shk4Q858q:b-3xoipl) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L104)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I assume this should fail if a trait isn't object-safe.
1. If I add non object-safe method this still compiles
2. It should be in a test module
</blockquote></details>

Updated, thanks for rechecking me.


<!-- Sent from Reviewable.io -->

2024-05-19 13:49 UTC, DvirYo-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0MluK9auVj1wqXSNX:-NyG3cF41OMXhhktTa_D:bnm7zf5) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L1)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I added links in the docs for the traits themselves. Is that ok?

And rewrote this.
</blockquote></details>

let's talk about the links.
the 1,2 bullets are not in the module doc
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0OWAY2RglfPbNKJwC:-NyG3W2y7_-TLIqpV5TO:bllsd8c) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L6)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you didn't remove the two to
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0U83A6NQLUzQC9kFO:-NyG5YAp3fOBNTVlcgyR:b-wkbdlg) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L98)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

No. How do you feel about a BTreeSet?

In the future I believe we will switch to a BTreeMap anyways:
1. I expect more info to come (ie weights) for each address, so a map.
2. I think we may want a stable order for leader selection, so not hash map.
</blockquote></details>

If it is going to change, I think for now, we should keep it as a vector, it is the simplest.
Just add a todo to consider this choice in the future.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0Lx9R2jdPT396py44:-NyG5OV12RdFDLJGvvw3:b-jgf09a) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L104)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Updated, thanks for rechecking me.
</blockquote></details>

You can delete the tests for now and add todo.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyG3okrEMn-SWTTpEi8:-NyG3okrEMn-SWTTpEi9:b-mzloqt) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d9d7423676e0455feb5b4c8247631b7d8a954a8/crates/sequencing/papyrus_consensus/src/types.rs#L29)):*
> ```XML
> // 3. We need the ability to identify the content of a proposal.
> //
> // Design Doc - https://docs.google.com/document/d/1ZJtgEcPzNW3hmzEIXNh-czY_OIEavNmXMj_4CeLA4A8/edit#heading=h.8csvpdbnvw8m
> ```

isn't this a private link?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyG3uUe4pJThk6LaLmI:-NyG3uUe4pJThk6LaLmJ:b-yyvo0p) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d9d7423676e0455feb5b4c8247631b7d8a954a8/crates/sequencing/papyrus_consensus/src/types.rs#L36)):*
> ```XML
>     // 2. Why not make `proposal_stream` generic? While this would allow a given concrete block type
>     //    to stream its content in multiple forms, this would also make `ConsensusBlock` object
>     //    unsafe, which hurts ergonomics.
> ```

I believe should be a public doc for those types
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyG68v486SFvKw6dogV:-NyG68v486SFvKw6dogW:bskm42d) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d9d7423676e0455feb5b4c8247631b7d8a954a8/crates/sequencing/papyrus_consensus/src/types.rs#L101)):*
> ```XML
>     ///
>     /// Returns:
>     /// - A receiver for the fully built block once it has been validated. If the block fails to be
> ```

what do you mean by "has been validated"? the block is build by the node itself


<!-- Sent from Reviewable.io -->

2024-05-19 13:58 UTC, DvirYo-starkware reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @matan-starkware, and @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-05-20 07:13 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0MluK9auVj1wqXSNX:-NyJmYIr--VzLcUypPzu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L1)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

let's talk about the links.
the 1,2 bullets are not in the module doc
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0OWAY2RglfPbNKJwC:-NyJm_hy3DK_r3P5r5fi:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L6)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

you didn't remove the two to
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0U83A6NQLUzQC9kFO:-NyJnsTk8b_84nxBwVQY:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L98)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

If it is going to change, I think for now, we should keep it as a vector, it is the simplest.
Just add a todo to consider this choice in the future.
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-Ny0Lx9R2jdPT396py44:-NyJntY_BX3VJgfcv4mK:b-5xaoww) ([raw file](https://github.com/starkware-libs/papyrus/blob/4021ace4d49723f36cd20e35f359a688789e62fe/crates/sequencing/papyrus_consensus/src/types.rs#L104)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

You can delete the tests for now and add todo.
</blockquote></details>

Discussed why we have the tests.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyG3okrEMn-SWTTpEi8:-NyJmaev-EtzlDTiBDA9:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d9d7423676e0455feb5b4c8247631b7d8a954a8/crates/sequencing/papyrus_consensus/src/types.rs#L29)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

isn't this a private link?
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyG3uUe4pJThk6LaLmI:-NyJmcVOATUKzm-RYFAJ:b-xr08wy) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d9d7423676e0455feb5b4c8247631b7d8a954a8/crates/sequencing/papyrus_consensus/src/types.rs#L36)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

I believe should be a public doc for those types
</blockquote></details>

I assume you mean that there should be some public doc? I added a one liner. I thought you wanted this discussion of rust type system to be private though?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyG68v486SFvKw6dogV:-NyJnII-4iQ2vxVjIvEP:b9gu2er) ([raw file](https://github.com/starkware-libs/papyrus/blob/0d9d7423676e0455feb5b4c8247631b7d8a954a8/crates/sequencing/papyrus_consensus/src/types.rs#L101)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

what do you mean by "has been validated"? the block is build by the node itself
</blockquote></details>

Rephrased


<!-- Sent from Reviewable.io -->

2024-05-20 08:04 UTC, ShahakShama requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 13 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyK-3sy4TqG8TNhDkXH:-NyK-3sy4TqG8TNhDkXI:b-oilksv) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L30)):*
> ```XML
>     //    to stream its content in multiple forms, this would also make `ConsensusBlock` object
>     //    unsafe, which hurts ergonomics.
>     type StreamT;
> ```

StreamT isn't a good name. Find a way to insert what is inside the stream in the type name (maybe ProposalStream)
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyJzelEA0RMHAlR-cjv:-NyJzelFCARhOavWnUmL:betktub) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L62)):*
> ```XML
> //    limitation of Sync to keep functions `&self` shouldn't be a problem.
> #[async_trait]
> pub trait Context: Send + Sync {
> ```

Context is a very known and used rust struct (std::task::Context)
Consider renaming
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyK0R2FB0aBkhVrSF5u:-NyK0R2FB0aBkhVrSF5v:bey0oda) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L78)):*
> ```XML
>     /// - A receiver for the fully built block once Context has finished streaming out the content
>     ///   and building it. If the block fails to be built, the Sender will be dropped by Context.
>     async fn build_block(
> ```

build_block makes me think that you are now finalizing the block after you got all you need. Maybe start_building_block?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyK0oAhAGDKOazKgInV:-NyK0oAhAGDKOazKgInW:b-p6e13f) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L95)):*
> ```XML
>     /// - A receiver for the fully built block. If a valid block cannot be built the Sender will be
>     ///   dropped by Context.
>     async fn validate_block(
> ```

Same here. start_validating_block


<!-- Sent from Reviewable.io -->

2024-05-20 11:07 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 13 unresolved discussions (waiting on @dan-starkware, @DvirYo-starkware, and @ShahakShama)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyK-3sy4TqG8TNhDkXH:-NyKcXO8E4JoHQ_CUQbG:b-j0p2sq) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L30)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

StreamT isn't a good name. Find a way to insert what is inside the stream in the type name (maybe ProposalStream)
</blockquote></details>

ProposalChunk
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyJzelEA0RMHAlR-cjv:-NyKcZaK0YDUwgXs090e:b3de4p3) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L62)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Context is a very known and used rust struct (std::task::Context)
Consider renaming
</blockquote></details>

Hmm, many people agreed upon this name; it's not just some internal name like StreamT. I, for one, had never heard of `std::task::Context` before, and I'm not certain if it is a problem for them to overlap. One other option I can think of is "OuterNode". Maybe we should chat about this though.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyK0R2FB0aBkhVrSF5u:-NyKfCZV09BnZzoQG43a:b-thtejo) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L78)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

build_block makes me think that you are now finalizing the block after you got all you need. Maybe start_building_block?
</blockquote></details>

I actually had something very close to that before that other didn't like. How about `build_proposal`?
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyK0oAhAGDKOazKgInV:-NyKfOki4YSZU5Yk3pQO:b-7l2vqi) ([raw file](https://github.com/starkware-libs/papyrus/blob/e9c335842e8af9acd77801a3b7ee3eb3f7b993c6/crates/sequencing/papyrus_consensus/src/types.rs#L95)):*
<details><summary><i>Previously, ShahakShama wrote…</i></summary><blockquote>

Same here. start_validating_block
</blockquote></details>

same response


<!-- Sent from Reviewable.io -->

2024-05-20 11:11 UTC, ShahakShama reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 10 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2024-05-20 13:07 UTC, ShahakShama submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-:-NyL6DGL2JC_CQOFx7Hq:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @dan-starkware and @DvirYo-starkware)



<!-- Sent from Reviewable.io -->

2024-05-20 13:33 UTC, DvirYo-starkware approved these changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 46 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyLA9k34ZGeFEKYMVTi:-NyLA9k34ZGeFEKYMVTj:bso7aa6) ([raw file](https://github.com/starkware-libs/papyrus/blob/d767cb99dadb67b446a522cdef3ee54cd8a8f23f/crates/sequencing/papyrus_consensus/src/types.rs#L46)):*
> ```XML
>     fn id(&self) -> u64;
> 
>     /// Returns an interator over the block's content. Since this is the proposal content we stream
> ```

fix this



_Code quote:_
```XML
interator
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 63 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyLAMch5A22LZSV8jWq:-NyLAMch5A22LZSV8jWr:b-lipqt4) ([raw file](https://github.com/starkware-libs/papyrus/blob/d767cb99dadb67b446a522cdef3ee54cd8a8f23f/crates/sequencing/papyrus_consensus/src/types.rs#L63)):*
> ```XML
> #[async_trait]
> pub trait ConsensusContext: Send + Sync {
>     // See [`ConsensusBlock::StreamT`] for why we use an associated type.
> ```

Change this to the new name



_Code quote:_
```XML
[`ConsensusBlock::StreamT`]
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyLAqtF9fX8D5cBA8D3:-NyLAqtF9fX8D5cBA8D4:b-jenqnu) ([raw file](https://github.com/starkware-libs/papyrus/blob/d767cb99dadb67b446a522cdef3ee54cd8a8f23f/crates/sequencing/papyrus_consensus/src/types.rs#L94)):*
> ```XML
>     /// - `height`: The height of the block to be built. Specifically this indicates the initial
>     ///   state of the block.
>     /// - A receiver for the stream of the block's content.
> ```

this is a return type and not a parameter



_Code quote:_
```XML
  /// - A receiver for the stream of the block's content.
```


<!-- Sent from Reviewable.io -->

2024-05-20 13:33 UTC, DvirYo-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-:-NyLCKdp7zD9HHrhq4SU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-05-20 13:39 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 94 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/1993#-NyLAqtF9fX8D5cBA8D3:-NyLDAom2UeLU83QxZfE:b-rdqw9s) ([raw file](https://github.com/starkware-libs/papyrus/blob/d767cb99dadb67b446a522cdef3ee54cd8a8f23f/crates/sequencing/papyrus_consensus/src/types.rs#L94)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

this is a return type and not a parameter
</blockquote></details>

In build_proposal this is a return type. for validate_proposal it is indeed a parameter.


<!-- Sent from Reviewable.io -->

2024-05-20 14:04 UTC, DvirYo-starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/1993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-starkware and @ShahakShama)



<!-- Sent from Reviewable.io -->

2024-05-21 08:09 UTC, merged