feat(consensus): create SingleHeightConsensus struct.
starkware-libs/papyrus pull request #2058
Opened 2024-05-26 14:26 UTC by matan-starkware

This involved some updating to the ConsensusBlock trait, mostly to better explain the design.
We implemented just the milestone 1 proposal flow for SHC.

2024-05-26 14:26 UTC, matan-starkware commented
* **#2058** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2058?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-27 14:31 UTC, DvirYo-starkware requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058)* status: all files reviewed, 8 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuCnOy9MVOUPrfxNtt:-NyuCnOy9MVOUPrfxNtu:b-roi1ip) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/lib.rs#L1)):*
> ```XML
> // TODO: Remove dead code allowance at the end of milestone 1.
> ```

In papyrus we add our name to todos. change this to TODO(matan): Remove...
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuK6Gu843pJj-zUm-b:-NyuK6Gu843pJj-zUm-c:bmfsk1f) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L35)):*
> ```XML
>     BlockT: ConsensusBlock,
> {
>     pub async fn new(
> ```

make thos functions pub(crate) and not public (I know the struct is pub(crate)
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuKqeI6UnnfdDMs_2y:-NyuKqeI6UnnfdDMs_2z:b2nq61q) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L56)):*
> ```XML
>         }
>     }
> ```

All those errors are shouldn't be return instead of panic?
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuQ3Ex8Y4YffZAhBmA:-NyuQ3Ex8Y4YffZAhBmB:b-a20ko2) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L38)):*
> ```XML
>     }
> }
> ```

This is not the same as the automock attribute? See the BaseLayerSourceTrait for example.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuRU4393RwP7H90g30:-NyuRU4393RwP7H90g31:b-spi9j5) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L121)):*
> ```XML
>     });
> 
>     // Creation calls to `context.validators`.
> ```

In private documentaion I don't see a value to the `xxx` 



_Code quote:_
```XML
 `context.validators`.
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuF-Ox0MPUZxnQObr5:-NyuF-Ox0MPUZxnQObr6:b-80s4gk) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/types.rs#L15)):*
> ```XML
> // TODO: Determine the actual type of NodeId.
> pub type NodeId = u64;
> pub type BlockId = u64;
> ```

why not using BlockNumber struct? It looks also that there is no use for this type
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuI2pM4Lmk-8fQb7F2:-NyuI2pN1PiGUo2nOQAH:bmzyo2u) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/types.rs#L73)):*
> ```XML
> #[async_trait]
> pub trait ConsensusContext: Send + Sync {
>     /// The block type built by `ConsensusContext` from a proposal.
> ```

consider make it a link
[`ConsensusContext`]



_Code quote:_
```XML
`ConsensusContext`
```
___
*[`crates/sequencing/papyrus_consensus/src/types_test.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuJ1Jm1boi1dLvl-EE:-NyuJ1Jm1boi1dLvl-EF:bf5s0mw) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/types_test.rs#L7)):*
> ```XML
> fn check_object_safety() {
>     struct _Blk {}
> ```

move this commet to the function level.
Did you delted the test for the ConsensusBlock because it is include in the ConsensusContext? if ConsensusBlock is not object safe so also ConsensusContext?


<!-- Sent from Reviewable.io -->

2024-05-28 10:46 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058)* status: 3 of 7 files reviewed, 8 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuCnOy9MVOUPrfxNtt:-NyyMDbjA8AO8bzxMHKh:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/lib.rs#L1)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

In papyrus we add our name to todos. change this to TODO(matan): Remove...
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuK6Gu843pJj-zUm-b:-NyyMcAb7qEV6gthkBJr:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L35)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

make thos functions pub(crate) and not public (I know the struct is pub(crate)
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuKqeI6UnnfdDMs_2y:-NyyN9UuEK8hTbWyG6Ou:bo0cg6g) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L56)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

All those errors are shouldn't be return instead of panic?
</blockquote></details>

This is a good point. I'll explain my thoughts:
1. I wasn't sure if we wanted to add that in the PR or a follow up. This relates to the fact that I don't know how we work with errors in Papyrus. We should VC to discuss.
2. Some of the error handling logic is different between M1 and the final. For instance, I don't know what we want to do in M1 if a proposal fails to be build or validated. In the future Tendermint handles and invalid proposal so that is not really an error.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuQ3Ex8Y4YffZAhBmA:-NyyNwakENnnv3GRNhya:bmsjv55) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L38)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This is not the same as the automock attribute? See the BaseLayerSourceTrait for example.
</blockquote></details>

I cannot use automock on ConsensusContext (tried a bunch). I did redo it though so that ConsensusBlock has automock and I implemented a mock for ConsensusContext in this file in place of automock so anyone can use it.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuRU4393RwP7H90g30:-NyyOdBZ7xi5hccfZ825:b-cdsmv3) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L121)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

In private documentaion I don't see a value to the `xxx`
</blockquote></details>

I still find it helpful as a reader even without markdown. It points to the fact that you are naming something specific in code, as opposed to just writing words about it. If you are against this, as opposed to just not seeing a point, then I can remove it. I guess consistency with the rest of papyrus is probably more important.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuF-Ox0MPUZxnQObr5:-NyyOwiF6b_tl9PqDfP9:b-9ih5e0) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/types.rs#L15)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

why not using BlockNumber struct? It looks also that there is no use for this type
</blockquote></details>

Good point, I found `BlockHash` which replaced `BlockId` and forgot to clean this up.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuI2pM4Lmk-8fQb7F2:-NyyPZGe-vcb5ZOMvPbo:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/types.rs#L73)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

consider make it a link
[`ConsensusContext`]
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/types_test.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuJ1Jm1boi1dLvl-EE:-NyyQZXt9YnJBJxoAq_3:b-8xgvp7) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/types_test.rs#L7)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

move this commet to the function level.
Did you delted the test for the ConsensusBlock because it is include in the ConsensusContext? if ConsensusBlock is not object safe so also ConsensusContext?
</blockquote></details>

1. I removed this constraint on ConsensusBlock because I didn't want to require that. I decided that directly holding the Block object was acceptable.
2. ConsensusContext remains object-safe even if it has an associated type that is not object-safe. I updated the code comment.


<!-- Sent from Reviewable.io -->

2024-05-28 13:26 UTC, DvirYo-starkware requested changes
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/lib.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuCnOy9MVOUPrfxNtt:-NyzFeprCsigNZu495gz:b-k1dzhc) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/lib.rs#L1)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. at least i don't see it done. do it in all the todos in this pr.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyuQ3Ex8Y4YffZAhBmA:-NyzJMwM8ZbclM1Y0g3H:b-itwivb) ([raw file](https://github.com/starkware-libs/papyrus/blob/adb497edfa32c873c844ccdf260ab5017b3fdf1e/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L38)):*
<details><summary><i>Previously, matan-starkware wrote…</i></summary><blockquote>

I cannot use automock on ConsensusContext (tried a bunch). I did redo it though so that ConsensusBlock has automock and I implemented a mock for ConsensusContext in this file in place of automock so anyone can use it.
</blockquote></details>

Can you explain why you cannot? lets talk about this
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyzMRDMAtQn-Ci_w2GU:-NyzMRDMAtQn-Ci_w2GV:b-guktvb) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ad368cd738b54f8148cb45f78ba22587c3d1f62/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L70)):*
> ```XML
>     let mut test_fields = setup();
>     let node_id: NodeId = 1;
>     let block_id = BlockHash(StarkFelt::try_from(0 as u128).unwrap());
> ```

cosider change this to default. or simpler way to create hash.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyzJpbz5I4thqolNOAS:-NyzJpbz5I4thqolNOAT:b-xgburh) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ad368cd738b54f8148cb45f78ba22587c3d1f62/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L74)):*
> ```XML
>     test_fields.context.expect_validators().returning(move |_| vec![node_id, 2, 3, 4]);
>     test_fields.context.expect_proposer().returning(move |_, _| node_id);
>     let block_id_clone = block_id.clone();
> ```

do you sure you need to clone here (and in other places)? block hash impl Copy
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 133 at r2](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-NyzINyuCLF7LCrdMBKc:-NyzINyuCLF7LCrdMBKd:b-tvsm8v) ([raw file](https://github.com/starkware-libs/papyrus/blob/9ad368cd738b54f8148cb45f78ba22587c3d1f62/crates/sequencing/papyrus_consensus/src/types.rs#L133)):*
> ```XML
> }
> 
> // Cannot use automock.
> ```

I don't understand why you can not use automock?


<!-- Sent from Reviewable.io -->

2024-05-30 10:06 UTC, DvirYo-starkware requested changes
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @matan-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-Nz7uil_-IR7xhm3pvkI:-Nz7uil_-IR7xhm3pvkJ:b-odmkwi) ([raw file](https://github.com/starkware-libs/papyrus/blob/b8ba0480777c73245de3435b65e5608372b24bb8/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L66)):*
> ```XML
>             .expect("failed to send proposal to peering");
>         let block = block_receiver.await.expect("failed to build block");
>         block_hash_sender.send(block.id()).expect("failed to send block hash");
> ```

Consider using only block hash or only block id



_Code quote:_
```XML
block_hash_sender.send(block.id())
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-Nz7xHg73NgHDxi385bM:-Nz7xHg73NgHDxi385bN:b-nn4sll) ([raw file](https://github.com/starkware-libs/papyrus/blob/b8ba0480777c73245de3435b65e5608372b24bb8/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L72)):*
> ```XML
>         let (_, content_receiver) = mpsc::channel(1);
>         let (block_sender, block_receiver) = oneshot::channel();
>         block_sender.send(block_clone.clone()).unwrap();
> ```

Are you sure you need to clone here?



_Code quote:_
```XML
.clone()
```
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-Nz7xmGo8b2-oySUa1PP:-Nz7xmGo8b2-oySUa1PQ:b2q68tb) ([raw file](https://github.com/starkware-libs/papyrus/blob/b8ba0480777c73245de3435b65e5608372b24bb8/crates/sequencing/papyrus_consensus/src/types.rs#L142)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

move this module to test_utils module


<!-- Sent from Reviewable.io -->

2024-05-30 10:50 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-Nz7uil_-IR7xhm3pvkI:-Nz83abfAHol93HIqHdm:b-tkjxbc) ([raw file](https://github.com/starkware-libs/papyrus/blob/b8ba0480777c73245de3435b65e5608372b24bb8/crates/sequencing/papyrus_consensus/src/single_height_consensus.rs#L66)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Consider using only block hash or only block id
</blockquote></details>

ok I'll leave BlockHash as the type and refer to it as id.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 72 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-Nz7xHg73NgHDxi385bM:-Nz83mMsEuX9basikoaz:bijzurt) ([raw file](https://github.com/starkware-libs/papyrus/blob/b8ba0480777c73245de3435b65e5608372b24bb8/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L72)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Are you sure you need to clone here?
</blockquote></details>

The compiler is :)

This actually made me decide to make TestBlock even simpler. It's now just a `u32` so we can copy.
___
*[`crates/sequencing/papyrus_consensus/src/types.rs` line 142 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-Nz7xmGo8b2-oySUa1PP:-Nz85u-v1FmUujOUBAUq:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/b8ba0480777c73245de3435b65e5608372b24bb8/crates/sequencing/papyrus_consensus/src/types.rs#L142)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

move this module to test_utils module
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-30 10:57 UTC, DvirYo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-:-Nz88V9F3QyTL2-eYrwX:bnfp4nl)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-05-30 10:58 UTC, DvirYo-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-:-Nz88ZWH8PoXDoNaHjlf:bnfp4nl)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-05-30 11:25 UTC, DvirYo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058#-:-Nz8EpZGE4J9Lu-kC0xy:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-05-30 11:52 UTC, matan-starkware reviewed
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2058)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-05-30 12:06 UTC, merged