feat(consensus): change the channel type for Peering to SingleHeightConsensus messages
starkware-libs/papyrus pull request #2069
Opened 2024-05-31 08:30 UTC by matan-starkware

This is because SHC is dropped after each height, and async_channel allows cloning the Receiver.
So the manager can hold a Receiver and clone a new one to pass to SHC for each height.

2024-05-31 08:30 UTC, matan-starkware commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2069?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2069** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2069?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2064** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2064?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2059** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2059?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#2058** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/2058?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @matan-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-03 07:03 UTC, DvirYo-starkware requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzRtU2n6WMwBYVh76Dd:-NzRtU2n6WMwBYVh76De:b-cdt0ue) (no related file):*
Why does the shc not have &mut for the receiver instead? or the receiver wrapped by RefCell? If the only reason is clone I don't think we should use in all other task communication tokio channels and only in this case something else.

I need this to continue with the manager.

___
___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 15 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzRsqDc5L77u6vjKdKx:-NzRsqDc5L77u6vjKdKy:b-xqvx0z) ([raw file](https://github.com/starkware-libs/papyrus/blob/900eb4b334a78f8ece5d0a9132e24bf3d0194b7c/crates/sequencing/papyrus_consensus/Cargo.toml#L15)):*
> ```TOML
> tokio = { workspace = true, features = ["full"] }
> thiserror.workspace = true
> async-channel = "2.3.1"
> ```

1. sort the dependencies alphabetically
2. put this in the cargo.toml of the workspace and import this from the workspace like other dependencies



_Code quote:_
```TOML
async-channel = "2.3.1"
```
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzRtInNCeXLu5EqbQkP:-NzRtInNCeXLu5EqbQkQ:b-sfj46l) ([raw file](https://github.com/starkware-libs/papyrus/blob/900eb4b334a78f8ece5d0a9132e24bf3d0194b7c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L6)):*
> ```XML
> use futures::StreamExt;
> use starknet_api::block::BlockNumber;
> use {async_channel as mpmc, tokio};
> ```

This is very confusing. You import something like it from another crate.



_Code quote:_
```XML
{async_channel as mpmc
```


<!-- Sent from Reviewable.io -->

2024-06-03 11:56 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069)* status: all files reviewed, 3 unresolved discussions (waiting on @DvirYo-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzRtU2n6WMwBYVh76Dd:-NzSwcuHDmSlTXOgOvHR:b-iw6qjh) (no related file):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

Why does the shc not have &mut for the receiver instead? or the receiver wrapped by RefCell? If the only reason is clone I don't think we should use in all other task communication tokio channels and only in this case something else.

I need this to continue with the manager.
</blockquote></details>

I went with RefCell.

___
___
*[`crates/sequencing/papyrus_consensus/Cargo.toml` line 15 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzRsqDc5L77u6vjKdKx:-NzSwj4xCDHz7Z1wCVQJ:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/900eb4b334a78f8ece5d0a9132e24bf3d0194b7c/crates/sequencing/papyrus_consensus/Cargo.toml#L15)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

1. sort the dependencies alphabetically
2. put this in the cargo.toml of the workspace and import this from the workspace like other dependencies
</blockquote></details>

Done.
___
*[`crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzRtInNCeXLu5EqbQkP:-NzSwk6W5u_-J3UNb1jq:bee8i7e) ([raw file](https://github.com/starkware-libs/papyrus/blob/900eb4b334a78f8ece5d0a9132e24bf3d0194b7c/crates/sequencing/papyrus_consensus/src/single_height_consensus_test.rs#L6)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

This is very confusing. You import something like it from another crate.
</blockquote></details>

Due to your RefCell comment I removed this entirely.


<!-- Sent from Reviewable.io -->

2024-06-03 12:36 UTC, DvirYo-starkware requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069)* status: all files reviewed, 3 unresolved discussions (waiting on @matan-starkware)

___
*[`-- commits` line 1 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzT3Rd43gE-PC28TgtE):*
change the commit message also
___
*[`Cargo.lock` line 388 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzT3auOClZc-9cS4imv:-NzT3auOClZc-9cS4imw:bxjgynx) ([raw file](https://github.com/starkware-libs/papyrus/blob/83b2624a86ed065d5e47e84a77deb647a1e37f2a/Cargo.lock#L388)):*
> ```TOML
>  "futures-core",
> ]
> ```

The lock file should not change because you didn't change any dependencies


<!-- Sent from Reviewable.io -->

2024-06-04 14:06 UTC, matan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @DvirYo-starkware)

___
*[`Cargo.lock` line 388 at r4](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-NzT3auOClZc-9cS4imv:-NzYZS7_3W45yQFEQOrN:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/e47a465c31566f3a4e55351443212fe15aabe3e7/Cargo.lock#L388)):*
<details><summary><i>Previously, DvirYo-starkware wrote…</i></summary><blockquote>

The lock file should not change because you didn't change any dependencies
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 09:54 UTC, DvirYo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-:-NzboSqH5DgZui_Z5OAr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-06-05 10:04 UTC, DvirYo-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-06-06 15:50 UTC, DvirYo-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2069#-:-NziEelF31aT8DQH9ds7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matan-starkware)



<!-- Sent from Reviewable.io -->

2024-06-06 17:07 UTC, merged