chore(helm): Add support to p2p
starkware-libs/papyrus pull request #2212
Opened 2024-07-09 15:11 UTC by idan-starkware

2024-07-09 17:41 UTC, eranreshef-starkware commented on deployments/helm/templates/deployment.yaml
> +          {{- toYaml . | nindent 12 }}
are you sure the indentation here needs to be 12?

2024-07-09 17:41 UTC, eranreshef-starkware commented on deployments/helm/templates/deployment.yaml
> +          - {{ default "10000" .Values.p2p.config.networkTcpPort | quote }}
not sure its a good idea to give default values inside the templates. if you specify the value in the default `values.yaml` you get the same result and its more explicit and readable.

2024-07-10 07:44 UTC, eranreshef-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2212#-:-O1QaU7XAfyPKIZ0VS74:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-17 07:58 UTC, eranreshef-starkware requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2212)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @idan-starkware)

___
*[`deployments/helm/values.yaml` line 11 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2212#-O1zgP0NEeCx6A_Kvw9w:-O1zgP0NEeCx6A_Kvw9x:b-8cbk8p) ([raw file](https://github.com/starkware-libs/papyrus/blob/1dc1db8ada64fb4c93db0653ff47370c87aa138d/deployments/helm/values.yaml#L11)):*
> ```YAML
> 
> # Ethereum node URL. A value for this variable is mandatory.
> base_layer_node_url: https://base_url.example.com
> ```

this config field shouldn't get a default value because there is no default value that will work globally.
___
*[`deployments/helm/values.yaml` line 96 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2212#-O1zg4cp9ASu_C6-0pgS:-O1zg4cp9ASu_C6-0pgT:bie6sro) ([raw file](https://github.com/starkware-libs/papyrus/blob/1dc1db8ada64fb4c93db0653ff47370c87aa138d/deployments/helm/values.yaml#L96)):*
> ```YAML
> pvc:
>   # Recommended size is at least 512Gi.
>   size: 1Gi
> ```

as discussed verbally yesterday, either set the recommended size or don't set a size at all. 


<!-- Sent from Reviewable.io -->

2024-07-17 10:50 UTC, idan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2212)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @eranreshef-starkware and @idan-starkware)

___
*[`deployments/helm/values.yaml` line 11 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2212#-O1zgP0NEeCx6A_Kvw9w:-O2-J3kJ-k3pnIMDAv97:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1dc1db8ada64fb4c93db0653ff47370c87aa138d/deployments/helm/values.yaml#L11)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

this config field shouldn't get a default value because there is no default value that will work globally.
</blockquote></details>

Done.
___
*[`deployments/helm/values.yaml` line 96 at r5](https://reviewable.io/reviews/starkware-libs/papyrus/2212#-O1zg4cp9ASu_C6-0pgS:-O2-J3zFAtXnzEw3naAd:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/1dc1db8ada64fb4c93db0653ff47370c87aa138d/deployments/helm/values.yaml#L96)):*
<details><summary><i>Previously, eranreshef-starkware (Eran Reshef) wrote…</i></summary><blockquote>

as discussed verbally yesterday, either set the recommended size or don't set a size at all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-17 12:03 UTC, eranreshef-starkware approved these changes
> Reviewed 4 of 6 files at r1, 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/2212)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @idan-starkware)



<!-- Sent from Reviewable.io -->

2024-07-17 12:16 UTC, merged