Remove the option to dynamically pass seed to rng generator
starkware-libs/papyrus pull request #639
Opened 2023-04-23 07:03 UTC by nagmo-starkware

dibatable lose of functionality but simplifies the code so I think it worth it.
also, there's still the ability to pass the seed as env var in order to debug when needed.

---

**Stack**:
- #638
- #637
- #636
- #635
- #634
- #633
- #632
- #631
- #630

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-05-16 06:55 UTC, yair-starkware requested changes
I'm not sure I get it - tests that previously used non-random instances will now use random instances unless we set the env variable?

> Reviewed 1 of 8 files at r12, 1 of 6 files at r15, 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/639#-:-NVYJuaS2J9CvkqYjqfe:bvbyjqs)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 192 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYH-k6DVmqTPYZm8FA:-NVYH-k6DVmqTPYZm8FB:br5r5fa) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/papyrus_gateway/src/gateway_test.rs#L192)):*
> ```XML
> 
> #[tokio::test]
> async fn verify_serialization_deserialization_of_block() {
> ```

Is this test because of the bug we found? 
If so, it should be a gateway block, not a sn_api block, otherwise, there is no need for this test.
Also, this is not related to the rest of this PR, right? 
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 201 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYHq7w8kiCRE6E1MjE:-NVYHq7w8kiCRE6E1MjF:bi1lnyl) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/papyrus_gateway/src/gateway_test.rs#L201)):*
> ```XML
> #[tokio::test]
> async fn verify_serialization_deserialization_of_body() {
>     let body: BlockBody = get_test_body(1, None, None, None);
> ```

This is a gateway body, right?
___
*[`crates/papyrus_gateway/src/transaction.rs` line 33 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYJegJ-LhetmkMuw-D:-NVYJegJ-LhetmkMuw-E:b-amd7on) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/papyrus_gateway/src/transaction.rs#L33)):*
> ```XML
> 
> #[derive(Debug, Clone, Default, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
> #[serde(deny_unknown_fields)]
> ```

Wasn't this already merged into main?
___
*[`crates/test_utils/src/lib.rs` line 85 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYIlNhCENn8RQLIUXq:-NVYIlNhCENn8RQLIUXr:b-i9jxxb) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/test_utils/src/lib.rs#L85)):*
> ```XML
>         let mut rng = rand::thread_rng();
>         rng.gen()
>     };
> ```

Consider changing this to a match statement



_Code quote:_
```XML
    let seed: u64 = if let Ok(seed_str) = env::var("SEED") {



        seed_str.parse().unwrap()
    } else {
        let mut rng = rand::thread_rng();
        rng.gen()
    };
```
___
*[`crates/test_utils/src/lib.rs` line 241 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYKvUZCbLknSmfM86X:-NVYKvUZCbLknSmfM86Y:b4nixd4) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/test_utils/src/lib.rs#L241)):*
> ```XML
> 
> // Returns a state diff with one item in each IndexMap.
> // For a random test state diff call StateDiff::get_test_instance.
> ```

Is this still true?



_Code quote:_
```XML
// For a random test state diff call StateDiff::get_test_instance.
```


<!-- Sent from Reviewable.io -->

2023-05-16 16:29 UTC, yair-starkware requested changes
@dan-starkware WDYT?
@nagmo-starkware, the seed will be printed in case of test failure, right? And the rng is a singleton per test?

> Reviewed 4 of 6 files at r16, 1 of 4 files at r19, 3 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/639#-:-NV_NT403sUy1EGo4sN_:bkakmf6)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-starkware and @nagmo-starkware)

___
*[`crates/test_utils/src/lib.rs` line 85 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYIlNhCENn8RQLIUXq:-NVYSFnQDZ0OdPfF2Qlb:b-wfti0o) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/test_utils/src/lib.rs#L85)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I don't really see how.. can you give an example?
</blockquote></details>

```
let seed: u64 = match env::var("SEED") {
    Ok(seed_str) => seed_str.parse().unwrap(),
    _ => rand::thread_rng().gen()
};
```

Another option:
```
let seed = env::var("SEED")
.and_then(|seed_str| seed_str.parse())
.unwrap_or_else(|_| rand::thread_rng().gen());
```
___
*[`crates/test_utils/src/lib.rs` line 241 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYKvUZCbLknSmfM86X:-NV_MRyr8iWi0zP-AOcT:b-4gc74e) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/test_utils/src/lib.rs#L241)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I think so since the state_diff changes still applies. the only change is how you get the random generator
</blockquote></details>

But before you created a non-random instance because the seed was 0 while now you will get a random instance from the function.


<!-- Sent from Reviewable.io -->

2023-05-17 05:39 UTC, nagmo-starkware reviewed
yes it does print if the test fails. and yes it's a singleton

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/639#-:-NVc9iDo2wZah_n54vE8:b-uy5jsj)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @dan-starkware and @yair-starkware)

___
*[`crates/test_utils/src/lib.rs` line 241 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYKvUZCbLknSmfM86X:-NVcAD9_2baFnp2zC64T:bd749p0) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/test_utils/src/lib.rs#L241)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

But before you created a non-random instance because the seed was 0 while now you will get a random instance from the function.
</blockquote></details>

I see what you mean. but read the two comments lines as if it is one comment.. same randomness was applied before. the difference is that we "fix" the stateDiff by adding a declared class with a different hash.
also, one more thing to note. Dan and I discussed adding a PR for documentation improvements of the public test utils functions once we finish with all the refactoring PRs.. so either way we'll look at it again soon. 


<!-- Sent from Reviewable.io -->

2023-05-18 10:02 UTC, yair-starkware commented
*[`crates/test_utils/src/lib.rs` line 241 at r18](https://reviewable.io/reviews/starkware-libs/papyrus/639#-NVYKvUZCbLknSmfM86X:-NViI_EGCzasZk9MenIt:b-svnvcl) ([raw file](https://github.com/starkware-libs/papyrus/blob/0e62e33c0cea95fce899a4e87285fa0795dd4220/crates/test_utils/src/lib.rs#L241)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I see what you mean. but read the two comments lines as if it is one comment.. same randomness was applied before. the difference is that we "fix" the stateDiff by adding a declared class with a different hash.
also, one more thing to note. Dan and I discussed adding a PR for documentation improvements of the public test utils functions once we finish with all the refactoring PRs.. so either way we'll look at it again soon. 
</blockquote></details>

Resolving
TBD: manual impl of get_test_instance for StateDiff for a valid instance instead of this function


<!-- Sent from Reviewable.io -->

2023-05-18 10:05 UTC, yair-starkware approved these changes
> Reviewed 1 of 1 files at r24, 1 of 1 files at r25, 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-starkware)



<!-- Sent from Reviewable.io -->

2023-05-18 10:16 UTC, merged