add middleware
starkware-libs/papyrus pull request #671
Opened 2023-05-14 12:34 UTC by nagmo-starkware

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-05-14 12:34 UTC, nagmo-starkware commented
Current dependencies on/for this PR:
* main
  * **PR #661** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/661" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #667** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/667" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #671** <a href="https://app.graphite.dev/github/pr/starkware-libs/papyrus/671" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/papyrus/671?utm_source=stack-comment).

2023-05-18 12:44 UTC, dan-starkware requested changes
> Reviewed 4 of 8 files at r1, 1 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 8 of 9 files reviewed, 8 unresolved discussions (waiting on @nagmo-starkware)

___
*[`Cargo.toml` line 72 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVijU3O5kZdIdIhpJgb:-NVijU3P5es7qu5AySW1:b-1lmt21) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/Cargo.toml#L72)):*
> ```TOML
> url = { version = "2.2.2" }
> web3 = { version = "0.18.0" }
> tower = { version = "0.4" }
> ```

Please keep sorted
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVipKWYBWzWQ4CldGVQ:-NVipKWZDyMaDe_896wR:bu07bo9) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L29)):*
> ```XML
>     let client = HttpClientBuilder::default().build(format!("http://{addr:?}")).unwrap();
>     let res: Result<RpcResult<BlockNumber>, Error> =
>         client.request("starknet_blockNumber", [""]).await;
> ```

Is this the path?
If this is a parameter list, can it be empty instead of an empty string?
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVipelJ-ryKtXX-7l8D:-NVipelJ-ryKtXX-7l8E:borreg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L40)):*
> ```XML
> }
> 
> async fn get_json_rpc_body(request: Request<Body>) -> Vec<u8> {
> ```

Please document.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 78 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVipzPA5MIhSa92nCXn:-NVipzPB9WfThSMxgJWJ:b-qtytm9) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L78)):*
> ```XML
>     let latest_version: String;
>     if let Some(latest_version_temp) = get_latest_version_id() {
>         latest_version = latest_version_temp;
> ```

let-else?
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVirD5L5CgPjacel4pj:-NVirD5L5CgPjacel4pk:bryk8us) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L91)):*
> ```XML
>         let future = async move {
>             let uri = format!("{}{}", base_uri, path);
>             println!("uri: {}", uri);
> ```

Please remove, also the next prints
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NViry3nCSG1rPttR0V2:-NViry3nCSG1rPttR0V3:bqlsr7o) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L101)):*
> ```XML
>         handles.push(handle);
>     }
>     let res = tokio::try_join!(handles.pop().unwrap(), handles.pop().unwrap());
> ```

Please fix
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 104 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVis6Pz-d6UInEYjgCr:-NVis6Pz-d6UInEYjgCs:b8iq6yg) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L104)):*
> ```XML
>     res.unwrap();
>     let rand_unknown_version: String =
>         rand::thread_rng().sample_iter(&Alphanumeric).take(5).map(char::from).collect();
> ```

No need for randomness, right?
___
*[`crates/papyrus_gateway/src/lib.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVijeVKBBxuWmkh4Oj3:-NVijeVKBBxuWmkh4Oj4:b1gaif0) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/lib.rs#L37)):*
> ```XML
> use crate::transaction::Transaction;
> 
> pub const SERVER_MAX_BODY_SIZE: u32 = 10 * 1024 * 1024;
> ```

Consider adding a comment of the size
___
*[`crates/papyrus_gateway/src/middleware.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVimtTtEMYeQo8SmtU5:-NVimtTtEMYeQo8SmtU6:b-7chfwf) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/middleware.rs#L12)):*
> ```XML
>     let (parts, body) = req.into_parts();
>     let (body_bytes, is_single) =
>         read_body(&parts.headers, body, SERVER_MAX_BODY_SIZE).await.unwrap();
> ```

Please refrain from unwrap. 
___
*[`crates/papyrus_gateway/src/middleware.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVinSIn7OPESeWLxP-T:-NVinSIn7OPESeWLxP-U:b9itir3) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/middleware.rs#L13)):*
> ```XML
>     let (body_bytes, is_single) =
>         read_body(&parts.headers, body, SERVER_MAX_BODY_SIZE).await.unwrap();
>     let new_body = if is_single {
> ```

Can we wrap the single case in a way such that we treat both cases once?
___
*[`crates/papyrus_gateway/src/middleware.rs` line 47 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVimXAs4Z9vf_XGoVQQ:-NVimXAs4Z9vf_XGoVQR:bch0wq0) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/middleware.rs#L47)):*
> ```XML
> }
> 
> fn get_prefix(path: &str) -> Result<String, BoxError> {
> ```

Consider renaming to get_version,
Consider returning a str
___
*[`crates/papyrus_gateway/src/middleware.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVimMqq0PgD70YPntQD:-NVimMqq0PgD70YPntQE:bkh3ufp) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/middleware.rs#L62)):*
> ```XML
>                     } else {
>                         return Err(BoxError::from("Invalid path, couldn't find matching version"));
>                     }
> ```

Please document and consider let-else



_Code quote:_
```XML
                    if let Some((version_id, _)) =
                        VERSION_CONFIG.iter().find(|(verison_id, version_state)| {
                            *verison_id == version && *version_state != VersionState::Deprecated
                        })
                    {
                        (*version_id).to_string()
                    } else {
                        return Err(BoxError::from("Invalid path, couldn't find matching version"));
                    }
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NViluzy8WG7pQuyPkRq:-NViluzy8WG7pQuyPkRr:bmxa3y5) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/middleware.rs#L64)):*
> ```XML
>                     }
>                 } else {
>                     latest_version_id
> ```

Consider error in this case.
___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVio_72CrjP5UsvZGI_:-NVio_72CrjP5UsvZGIa:b-6y3wom) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/api/version_config.rs#L21)):*
> ```XML
> pub const VERSION_CONFIG: &[(&str, VersionState)] = &[(VERSION_0_3_0, VersionState::Latest)];
> 
> pub fn get_latest_version_id() -> Option<String> {
> ```

Can this be static and always return Some? (no need for option?)


<!-- Sent from Reviewable.io -->

2023-05-21 14:15 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 1 of 10 files reviewed, 5 unresolved discussions (waiting on @dan-starkware)

___
*[`Cargo.toml` line 72 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVijU3O5kZdIdIhpJgb:-NViv3IUC39W0RJfKccu:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/Cargo.toml#L72)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please keep sorted
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVipKWYBWzWQ4CldGVQ:-NViw4hk2Hgtx6ePQ3TQ:b1rvejn) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L29)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Is this the path?
If this is a parameter list, can it be empty instead of an empty string?
</blockquote></details>

it's the params. it has to be empty string. in the list it must have a type that implements the ToRpcParams trait. 
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 91 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVirD5L5CgPjacel4pj:-NVixL8D1j3mb5mg2QqV:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L91)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please remove, also the next prints
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NViry3nCSG1rPttR0V2:-NViz-sQ8gP2dUXHbz_h:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/gateway_test.rs#L101)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please fix
</blockquote></details>

Done.
___
*[`crates/papyrus_gateway/src/middleware.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NVimtTtEMYeQo8SmtU5:-NVjOXPV6V04gU2n4zVb:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/113a7b04f547f8f1bcb5f2d97a7c530b89f66f0a/crates/papyrus_gateway/src/middleware.rs#L12)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please refrain from unwrap. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-23 19:48 UTC, dan-starkware requested changes
> Reviewed 4 of 7 files at r5, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @nagmo-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 1 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW98AlR9VJeFRAJDvz2:-NW98AlR9VJeFRAJDvz3:b-33gidc) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L1)):*
> ```XML
> use std::panic;
> ```

Please add negative test-cases. Might be better to add a TODO in this PR and open a separate PR for these.
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW7pNLwAHRzLVo61F6e:-NW7pNLwAHRzLVo61F6f:b-nbs35z) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L29)):*
> ```XML
>     let res: Result<RpcResult<BlockNumber>, Error> =
>         client.request("starknet_blockNumber", [""]).await;
>     let _expected_error = ErrorObjectOwned::from(JsonRpcError::NoBlocks);
> ```

Why the underscore?



_Suggestion:_
```XML
expected_error
```
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW7pTnL0HTEKFVNzO55:-NW7pTnL0HTEKFVNzO56:b-oe787t) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L36)):*
> ```XML
> }
> 
> /// Given an HTTP request, using the "read_body" function from jsonrpsee library,
> ```

Regular comment? Can you check if there's a related convention?



_Suggestion:_
```XML
//
```
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 93 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW97j6J6_FUfXJCSPzD:-NW97j6J6_FUfXJCSPzE:undefined) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L93)):*
> ```XML
>     }
>     let _res = join_all(handles).await;
>     let rand_unknown_version = "not_a_valid_version";
> ```





_Suggestion:_
```XML
unknown_version
```
___
*[`crates/papyrus_gateway/src/lib.rs` line 37 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8nn2Y2743Zd6yG87G:-NW8nn2Y2743Zd6yG87H:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/lib.rs#L37)):*
> ```XML
> use crate::transaction::Transaction;
> 
> /// Const for limiting the size of a supported transaction body to 10MB
> ```

Consider



_Suggestion:_
```XML
/// Maximum size of a supported transaction body - 10MB.
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 8 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW96HA67OoNOZr8x5b8:-NW96HA67OoNOZr8x5b9:borreg2) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L8)):*
> ```XML
> use crate::SERVER_MAX_BODY_SIZE;
> 
> pub async fn proxy_request(req: Request<Body>) -> Result<Request<Body>, BoxError> {
> ```

Please document.
___
*[`crates/papyrus_gateway/src/middleware.rs` line 16 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW9686H2lacAYT25PX0:-NW9686H2lacAYT25PX1:brv6pjy) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L16)):*
> ```XML
>         Ok(res) => res,
>         Err(err) => return Err(BoxError::from(err)),
>     };
> ```

Consider



_Suggestion:_
```XML
    let (body_bytes, is_single) =
        read_body(&parts.headers, body, SERVER_MAX_BODY_SIZE).await.map_err(BoxError::from)?;
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW94X0C3bM3zuJkBM7q:-NW94X0C3bM3zuJkBM7r:bp4yty7) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L49)):*
> ```XML
>         true => vec_body.iter().map(|body| body.as_ref().unwrap()).collect::<Vec<_>>(),
>         false => return Err(BoxError::from("Method name has unexpected format")),
>     };
> ```

Consider something like this



_Suggestion:_
```XML
       .collect::<Result<Vec<_>, _>>();
    let Ok(vec_body) = vec_body else {
            return Err(BoxError::from("Method name has unexpected format"))
    };
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 53 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW96thO3iLnxdpDHUCr:-NW96thO3iLnxdpDHUCs:bct1d5p) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L53)):*
> ```XML
>         true => serde_json::to_vec(&vec_body[0]),
>         false => serde_json::to_vec(&vec_body),
>     };
> ```

Consider moving this logic to the outer scope (where we're already matching `is_single`)



_Code quote:_
```XML
    let serialized = match is_single {
        true => serde_json::to_vec(&vec_body[0]),
        false => serde_json::to_vec(&vec_body),
    };
```
___
*[`crates/papyrus_gateway/src/middleware.rs` line 65 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW97IoY-9fUv1uZ74Uh:-NW97IoY-9fUv1uZ74Ui:bpjjiam) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L65)):*
> ```XML
> 
> fn get_version_as_prefix(path: &str) -> Result<&str, BoxError> {
>     let latest_version_id = get_latest_version_id();
> ```

Consider eliminating this local variable.



_Code quote:_
```XML
let latest_version_id = get_latest_version_id();
```
___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 33 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8keWO6ySRJ1ev5vKI:-NW8keWO6ySRJ1ev5vKJ:b8yzq0v) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/version_config.rs#L33)):*
> ```XML
>     }
>     // this would never be returned, it's just for compilations purposes (if n == 0).
>     ""
> ```

Would something like this work?



_Suggestion:_
```XML
    unreachable!("VERSION_CONFIG should always contain a latest version");
```
___
*[`crates/papyrus_gateway/src/api/version_config_test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8lq3FESrh17KNonjr:-NW8lq3FESrh17KNonjs:bvmmpab) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/version_config_test.rs#L29)):*
> ```XML
>     let expected_latest_version_id = VERSION_0_3_0;
>     let res = get_latest_version_id();
>     assert_eq!(expected_latest_version_id, res);
> ```

I'm not a fan of high'ish-maintenance tests.
Consider just calling the function (and implicitly verify that we don't panic).
___
*[`crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs` line 556 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8mZ7E3g4rTa0-m8LN:-NW8mZ7E3g4rTa0-m8LO:btnx904) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs#L556)):*
> ```XML
>         .call::<_, TransactionReceiptWithStatus>(
>             "starknet_V0_3_0_getTransactionReceipt",
>             [TransactionHash(StarkHash::from(1_u128))],
> ```

Not very important, but consider (same below)



_Suggestion:_
```XML
1_u8
```


<!-- Sent from Reviewable.io -->

2023-05-24 08:53 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 1 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW98AlR9VJeFRAJDvz2:-NWBwuhO-ZN-V0dvXTz8:bxomkqv) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Please add negative test-cases. Might be better to add a TODO in this PR and open a separate PR for these.
</blockquote></details>

negative test case for what? I didn't understand
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW7pNLwAHRzLVo61F6e:-NWBVjSaCT4jPI_QzFn-:b-lwmhvq) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L29)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Why the underscore?
</blockquote></details>

doesn't compile without. because it's only used in the assert the compiler thinks it's unused:
```
warning: unused variable: `expected_error`
  --> crates/papyrus_gateway/src/gateway_test.rs:29:9
   |
29 |     let expected_error = ErrorObjectOwned::from(JsonRpcError::NoBlocks);
   |         ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_expected_error`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `expected_error`
  --> crates/papyrus_gateway/src/gateway_test.rs:31:42
   |
31 |         Err(err) => assert_matches!(err, expected_error),
   |                                          ^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_expected_error`
```
___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW7pTnL0HTEKFVNzO55:-NWBKaUdAM-nzE5_t49V:bz1wxn3) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L36)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Regular comment? Can you check if there's a related convention?
</blockquote></details>

no convention per-se.. there is a guideline of what good docs are and where you need it but not what to do when it's not mandatory (like private functions for example). it seems like the tendency is to welcome "over documentation" which I think makes sense.
here's a discussion [link](https://internals.rust-lang.org/t/style-guide-for-comments/8995) and a part from the docs [link](https://doc.rust-lang.org/rustdoc/write-documentation/what-to-include.html)
___
*[`crates/papyrus_gateway/src/middleware.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW94X0C3bM3zuJkBM7q:-NWBNswfDajdTf-o3Bh8:b9lv4fs) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L49)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider something like this
</blockquote></details>

maybe I'm missing something but I don't understand how it would work. the point it to unwrap all the items contained in the vector after checking that they are `Ok` and not `Err`. I would expect that the boolean evaluation of a vector to be true if it is not empty not if the values inside are not errors..
I tried to look for it on google but couldn't find it.. maybe I'm wrong
___
*[`crates/papyrus_gateway/src/middleware.rs` line 53 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW96thO3iLnxdpDHUCr:-NWBOXC50cVZOe7RwZai:b-dvgcxo) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L53)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Consider moving this logic to the outer scope (where we're already matching `is_single`)
</blockquote></details>

that was my original plan but it means I need to return a reference to an object that belongs to this function so I'll have to do a lot of changes to the code to support it and I don't think it worth it. It will make the code worse in terms of readability
___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 33 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8keWO6ySRJ1ev5vKI:-NWBPH-i-CIba_7sBxWx:bbfl3e7) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/version_config.rs#L33)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Would something like this work?
</blockquote></details>

actually didn't know it was an option.. good to know.
unfortunately I can't use it here since it is not supported in a const function:
`Arguments::<'a>::new_v1 is not yet stable as a const fn`
___
*[`crates/papyrus_gateway/src/api/version_config_test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8lq3FESrh17KNonjr:-NWBT_jE35R0EVOu7Kw-:b-7l12cu) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/version_config_test.rs#L29)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

I'm not a fan of high'ish-maintenance tests.
Consider just calling the function (and implicitly verify that we don't panic).
</blockquote></details>

I tend to agree but what would happen if you add a new version and forget to put it as latest? then nothing will stop you from pushing it to production. 
let's find an alternative solution.. what if we put here a test that just makes sure the function doesn't panic (i.e there is a latest version)
and in the version test itself (`v0_3_0_test.rs` in this case) a test that will check that it is currently latest and will need to be updated once when we have a new version?
that is still some maintenance but less and we keep the completeness of the test suite.

actually I think if we do that it will be complete only if we add another test that reads the `api` folder and looks for all the versions it can find and make sure each on of them has a corresponding record in the `version_config`. I can try to add a test like that.

what do you think? do you have another idea?
___
*[`crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs` line 556 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8mZ7E3g4rTa0-m8LN:-NWBUoVdE_7Ft0qpxbj8:b-kapnk1) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/v0_3_0/v0_3_0_test.rs#L556)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

Not very important, but consider (same below)
</blockquote></details>

I don't get it.. but sure if it compiles..


<!-- Sent from Reviewable.io -->

2023-05-24 10:09 UTC, dan-starkware commented
*[`crates/papyrus_gateway/src/gateway_test.rs` line 1 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW98AlR9VJeFRAJDvz2:-NWCC4tG1GiDsLCidb03:bwv22mb) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L1)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

negative test case for what? I didn't understand
</blockquote></details>

middleware (version/path related)


<!-- Sent from Reviewable.io -->

2023-05-24 10:15 UTC, dan-starkware commented
*[`crates/papyrus_gateway/src/middleware.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW94X0C3bM3zuJkBM7q:-NWCDPMe6sNcl0ydjB8j:b-e7ntrk) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/middleware.rs#L49)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

maybe I'm missing something but I don't understand how it would work. the point it to unwrap all the items contained in the vector after checking that they are `Ok` and not `Err`. I would expect that the boolean evaluation of a vector to be true if it is not empty not if the values inside are not errors..
I tried to look for it on google but couldn't find it.. maybe I'm wrong
</blockquote></details>

collect(can take anything iterable (Result is iterable)
See the last example [here](https://doc.rust-lang.org/std/iter/trait.Iterator.html#examples-29)


<!-- Sent from Reviewable.io -->

2023-05-24 10:26 UTC, dan-starkware commented
*[`crates/papyrus_gateway/src/api/version_config_test.rs` line 29 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW8lq3FESrh17KNonjr:-NWCHj2cE5Wcl6qqo0jT:b-o4lkkr) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/api/version_config_test.rs#L29)):*
<details><summary><i>Previously, nagmo-starkware wrote…</i></summary><blockquote>

I tend to agree but what would happen if you add a new version and forget to put it as latest? then nothing will stop you from pushing it to production. 
let's find an alternative solution.. what if we put here a test that just makes sure the function doesn't panic (i.e there is a latest version)
and in the version test itself (`v0_3_0_test.rs` in this case) a test that will check that it is currently latest and will need to be updated once when we have a new version?
that is still some maintenance but less and we keep the completeness of the test suite.

actually I think if we do that it will be complete only if we add another test that reads the `api` folder and looks for all the versions it can find and make sure each on of them has a corresponding record in the `version_config`. I can try to add a test like that.

what do you think? do you have another idea?
</blockquote></details>

Consider defining the latest version at `version_config` and derive evrything else from there. 


<!-- Sent from Reviewable.io -->

2023-05-24 10:28 UTC, dan-starkware reviewed
> Reviewed 3 of 7 files at r9, 1 of 3 files at r11, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2023-05-24 12:12 UTC, nagmo-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @dan-starkware)

___
*[`crates/papyrus_gateway/src/gateway_test.rs` line 1 at r7](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NW98AlR9VJeFRAJDvz2:-NWCZcKqCWrfna3YaoaL:b-896fix) ([raw file](https://github.com/starkware-libs/papyrus/blob/382e26647ec6f72befcfe960eaa92c98cf070c9c/crates/papyrus_gateway/src/gateway_test.rs#L1)):*
<details><summary><i>Previously, dan-starkware wrote…</i></summary><blockquote>

middleware (version/path related)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-24 14:42 UTC, dan-starkware reviewed
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 9 of 10 files reviewed, all discussions resolved

___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 20 at r13](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NWD9y0s1HLrfXJdvpDb:-NWD9y0s1HLrfXJdvpDc:b-mo9mh1) ([raw file](https://github.com/starkware-libs/papyrus/blob/d540413045a5e34ea13d1af79ab3b5b992172aac/crates/papyrus_gateway/src/api/version_config.rs#L20)):*
> ```XML
> 
> pub const VERSION_0_3_0: &str = "V0_3_0";
> pub const LATEST_VERSION_ID: &str = VERSION_0_3_0;
> ```

Move up & document (this should point to the latest version...)



_Code quote:_
```XML
pub const LATEST_VERSION_ID: &str = VERSION_0_3_0;
```
___
*[`crates/papyrus_gateway/src/api/version_config.rs` line 22 at r13](https://reviewable.io/reviews/starkware-libs/papyrus/671#-NWDB3ES5lspAyBzeMbC:-NWDB3ES5lspAyBzeMbD:byyeikc) ([raw file](https://github.com/starkware-libs/papyrus/blob/d540413045a5e34ea13d1af79ab3b5b992172aac/crates/papyrus_gateway/src/api/version_config.rs#L22)):*
> ```XML
> pub const LATEST_VERSION_ID: &str = VERSION_0_3_0;
> pub const VERSION_CONFIG: &[(&str, VersionState)] =
>     &[(LATEST_VERSION_ID, VersionState::Latest), (VERSION_0_3_0, VersionState::Supported)];
> ```

Move before the versions themselves (after the latest one)



_Code quote:_
```XML
pub const VERSION_CONFIG: &[(&str, VersionState)] =
    &[(LATEST_VERSION_ID, VersionState::Latest), (VERSION_0_3_0, VersionState::Supported)];
```


<!-- Sent from Reviewable.io -->

2023-05-29 06:43 UTC, dan-starkware reviewed
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: 10 of 11 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-29 06:44 UTC, dan-starkware approved these changes
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/papyrus/671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nagmo-starkware)



<!-- Sent from Reviewable.io -->

2023-05-29 08:23 UTC, merged